import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import JSZip from 'file:///C:/Users/kurob/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/jszip/lib/index.js';
import {exportTuitionRoster} from '../js/tuition-export-roster.js';
import {buildTuitionCardsXlsx,tuitionCards} from '../js/tuition-card-export.js';
const now=new Date('2026-09-30T05:00:00Z');
const source={month:'2026-09',sourceRow:1,labels:['Tên trẻ','Số buổi đăng ký T08','Số buổi vắng','Số buổi đã bù','Số buổi không bù','Tổng số buổi học','Ghi chú','Hoàn lại',null,'Tổng học phí'],values:['Bé An',18,4,null,null,null,'Ghi chú cũ','học bù 4 buổi',null,4640000],feeLabels:[null,'Số buổi đăng ký T09/2026',null,null,null,null,'HP 1 buổi','Học phí tháng','Ghi chú',null],fees:[null,16,null,null,null,null,290000,4640000,null,null]};
const data={accounts:[{id:'a',studentId:'a',displayName:'Bé An',history:[source],months:{}}],students:[{id:'a',fullName:'Bé An',active:true},{id:'b',fullName:'Bé mới',active:true},{id:'old',fullName:'Đã nghỉ',active:false,stoppedDate:'2026-09-08'},{id:'waiting',active:false,enrollmentStatus:'waiting'}],templates:[{studentId:'a',active:true,dayOfWeek:0,startTime:'08:00',endTime:'09:00'}],sessions:[],weeks:[],holidays:[]};
const before=JSON.stringify(data),roster=data.students.map((person,index)=>({person,number:index+1})),accounts=exportTuitionRoster(data,'2026-10',roster,now);
assert.deepEqual(accounts.map(a=>a.studentId),['a','b']);
assert.ok(exportTuitionRoster(data,'2026-09',roster,now).some(a=>a.studentId==='old'));
assert.deepEqual(tuitionCards(accounts[0],'2026-10',data,now).map(c=>c.month),['2026-10','2026-09']);
assert.deepEqual(tuitionCards(accounts[0],'2026-10',data,now)[1].source,source);
const template=JSON.parse(await fs.readFile(new URL('../assets/tuition-card-layout.json',import.meta.url),'utf8'));
const blob=buildTuitionCardsXlsx(template,accounts,data,'2026-10',now),zip=await JSZip.loadAsync(await blob.arrayBuffer());
const sheet=await zip.file('xl/worksheets/sheet1.xml').async('string'),secondSheet=await zip.file('xl/worksheets/sheet2.xml').async('string'),book=await zip.file('xl/workbook.xml').async('string');
for(const xml of [sheet,secondSheet])assert.match(xml,/<sheetView[^>]*zoomScale="70"[^>]*zoomScaleNormal="100"/);
assert.match(sheet,/<col min="1" max="1" width="24"/);
assert.match(book,/name="Bé An"/);assert.match(book,/name="Bé mới"/);assert.match(sheet,/học bù 4 buổi/);assert.match(sheet,/<v>4640000<\/v>/);assert.match(sheet,/A6:A8/);assert.match(sheet,/B8/);assert.match(sheet,/ISNUMBER\(B8\)/);
assert.equal(JSON.stringify(data),before);
await fs.writeFile('D:/2DUnityGame/.codex/tuition-export-qa/cards-test.xlsx',new Uint8Array(await blob.arrayBuffer()));
console.log('Tuition cards: roster, missing accounts, stopped dates, month order, source preservation, sheet names, formulas and merges passed');
