import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import JSZip from 'file:///C:/Users/kurob/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/jszip/lib/index.js';
import {buildTuitionXlsx,tuitionExportRow} from '../js/tuition-export.js';
const now=new Date('2026-12-31T12:00:00+07:00'),account={id:'a',studentId:'s',displayName:'An',rosterNumber:8,months:{'2026-12':{unitFee:300000,adjustment:100000,note:'=1+1'}},history:[]};
const data={students:[{id:'s',fullName:'=Tên <bé> & An',active:true,makeupBalance:4}],weeks:[],templates:[{studentId:'s',dayOfWeek:0,startTime:'08:00',endTime:'09:00',active:true}],sessions:[],holidays:[]};
const next=tuitionExportRow(account,'2027-01',data,now);
const attendanceData={...data,sessions:[{studentId:'s',dateKey:'2026-12-10',startTime:'08:00',endTime:'09:00',type:'makeup',status:'makeup_completed'},{studentId:'s',dateKey:'2026-12-11',startTime:'08:00',endTime:'09:00',type:'regular',status:'absent'},{studentId:'s',dateKey:'2026-12-12',startTime:'08:00',endTime:'09:00',type:'regular',status:'attended'}]};
const priorAttendance=tuitionExportRow(account,'2027-01',attendanceData,now);
assert.equal(priorAttendance.madeUp,1);assert.equal(priorAttendance.actual,2);assert.equal(priorAttendance.registered,4);
assert.equal(next.registered,4);assert.equal(next.unitFee,300000);assert.equal(next.adjustment,0);assert.equal(next.total,1200000);assert.equal(next.previous,4);
const unlinked={id:'u',displayName:'Bé chưa liên kết',history:[],months:{}};
assert.equal(tuitionExportRow(unlinked,'2027-01',data,now).total,undefined);
const source={...unlinked,history:[{month:'2026-12',sourceRow:1,values:['Bé',9,2,1,0,8,'Ghi chú',null,null,2500000],fees:[null,10,null,null,null,null,300000,3000000,'Giảm trừ',null]}]};
const original=tuitionExportRow(source,'2026-12',data,now);assert.equal(original.total,2500000);assert.equal(original.fixedAmounts,true);
const template=JSON.parse(await fs.readFile(new URL('../assets/tuition-export-layout.json',import.meta.url),'utf8'));
const blob=buildTuitionXlsx(template,[account,source],data,'2026-12',now),zip=await JSZip.loadAsync(await blob.arrayBuffer());
const current=await zip.file('xl/worksheets/sheet1.xml').async('string'),forecast=await zip.file('xl/worksheets/sheet2.xml').async('string');
assert.match(forecast,/THÁNG 01\/2027/);assert.match(forecast,/Đăng ký T12\/2026/);
assert.match(current,/<c r="L6"[^>]*t="inlineStr"><is><t xml:space="preserve">=1\+1/);
assert.match(current,/&lt;bé&gt; &amp; An/);
assert.match(current,/<c r="K7"[^>]*><v>2500000<\/v><\/c>/,'Imported source totals are preserved');
assert.ok(!current.includes('<f>=1+1'));
console.log('Tuition export: year boundary, rate inheritance, no carried discount, missing linkage, source preservation and formula injection safety passed.');
