import { chromium } from "file:///C:/Users/kurob/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs";
import {T9_TEACHER_SOURCE,T9_TEMPLATE_SOURCE} from "../js/t9-templates.js";
import {planRosterReconciliation} from "../js/roster-reconcile.js";

const sourceStudents=new Map();for(const item of T9_TEMPLATE_SOURCE)if(!sourceStudents.has(item.studentKey))sourceStudents.set(item.studentKey,{id:item.studentIdHint,fullName:item.studentName,active:true,makeupBalance:0});
const reconciliationFixture=[...sourceStudents.values(),{id:"duplicate-duy-thong",fullName:"Duy Thông",active:true,makeupBalance:1},{id:"duplicate-dau",fullName:"Dâu",active:true,makeupBalance:0},{id:"duplicate-dan",fullName:"Dần",active:true,makeupBalance:0},{id:"stale-ben-sang",fullName:"BEN SÁNG",active:true,makeupBalance:0},{id:"stale-duc-thanh",fullName:"ĐỨC THÀNH",active:true,makeupBalance:0}];
const reconciliationPlan=planRosterReconciliation(reconciliationFixture,T9_TEMPLATE_SOURCE);
if(reconciliationPlan.desired.length!==62||reconciliationPlan.keepers.length!==62||reconciliationPlan.missing.length)throw new Error("Danh sách T9 chưa giữ đúng 62 học sinh sau khi gộp Dâu/Thiên Mỹ");
if(JSON.stringify(reconciliationPlan.stale.map(item=>item.studentName).sort())!==JSON.stringify(["BEN SÁNG","ĐỨC THÀNH"]))throw new Error("Không xác định đúng học sinh đã rời danh sách tháng 9");
if(!reconciliationPlan.duplicates.some(item=>item.studentName==="Duy Thông"&&item.keeperName==="Gấu")||!reconciliationPlan.duplicates.some(item=>item.studentName==="Dâu"&&item.keeperName==="THIÊN MỸ")||!reconciliationPlan.duplicates.some(item=>item.studentName==="Dần"&&item.keeperName==="TRIẾT"))throw new Error("Quy tắc gộp Duy Thông/Gấu, Dâu/Thiên Mỹ hoặc Dần/Triết chưa đúng");
if(reconciliationPlan.desired.some(item=>item.scheduleCount<1))throw new Error("Có học sinh tháng 9 không được phân lịch");
if(T9_TEMPLATE_SOURCE.length!==250||T9_TEACHER_SOURCE.length!==9||!T9_TEACHER_SOURCE.some(item=>item.id==="teacher-sheet5-diem"&&item.fullName==="Cô Điểm"))throw new Error("Nguồn T9 (2) chưa có đủ 250 lịch và 9 giáo viên");
const contractTeachers=new Map(T9_TEACHER_SOURCE.map(item=>[item.id,item]));
if(contractTeachers.get("teacher-sheet5-tien")?.birthday!=="2003-11-11"||contractTeachers.get("teacher-sheet5-tien")?.phone!=="0856772057"||contractTeachers.get("teacher-sheet5-thuy")?.birthday!=="2004-05-29"||contractTeachers.get("teacher-sheet5-thuy")?.phone!=="0934033418"||contractTeachers.get("teacher-sheet5-ngoc")?.phone!=="0395884168"||contractTeachers.get("teacher-sheet5-duong")?.phone!=="0947955452"||contractTeachers.get("teacher-sheet5-han")?.phone!=="0797023751"||contractTeachers.get("teacher-sheet5-mai")?.phone!=="0983250755"||contractTeachers.get("teacher-sheet5-quynh")?.phone!=="0937759101")throw new Error("Thông tin ngày sinh/SĐT giáo viên theo hợp đồng chưa đúng");
if(contractTeachers.get("teacher-sheet5-ngan")?.birthday!=="2003-06-09"||Object.hasOwn(contractTeachers.get("teacher-sheet5-ngan"),"phone")||contractTeachers.get("teacher-sheet5-diem")?.birthday!=="1995-05-09"||Object.hasOwn(contractTeachers.get("teacher-sheet5-diem"),"phone"))throw new Error("Hồ sơ Cô Ngân/Cô Điểm phải giữ trống SĐT khi ảnh nguồn không có dữ liệu");
if(contractTeachers.get("teacher-sheet5-duong")?.color!=="#ff9900"||contractTeachers.get("teacher-sheet5-ngan")?.color!=="#fce5cd"||contractTeachers.get("teacher-sheet5-mai")?.color!=="#cc0000"||contractTeachers.get("teacher-sheet5-diem")?.color!=="#00ff00")throw new Error("Bảng màu giáo viên chưa khớp chú giải T9 (2)");
const scheduleFor=(studentKey,dayOfWeek,startTime)=>T9_TEMPLATE_SOURCE.find(item=>item.studentKey===studentKey&&item.dayOfWeek===dayOfWeek&&item.startTime===startTime);
for(const day of [0,2,4])if(scheduleFor("MIE",day,"16:00")?.teacherId!=="teacher-sheet5-ngan"||scheduleFor("TIGER",day,"16:00")?.teacherId!=="teacher-sheet5-han"||scheduleFor("THIÊN PHÚC",day,"17:00")?.teacherId!=="teacher-sheet5-ngan"||scheduleFor("GIA",day,"19:00")?.teacherId!=="teacher-sheet5-ngan")throw new Error("Lịch T2/T4/T6 chưa đúng màu giáo viên mới");
for(const day of [1,3,5])if(scheduleFor("THẢO MY",day,"15:00")?.teacherId!=="teacher-sheet5-diem"||scheduleFor("TIGER",day,"16:00")?.teacherId!=="teacher-sheet5-ngan")throw new Error("Lịch T3/T5/T7 chưa đúng màu giáo viên mới");
if(scheduleFor("TUỆ MINH",5,"18:00")?.teacherId!=="teacher-sheet5-mai"||scheduleFor("MON NGUYÊN",5,"09:00")?.teacherId!=="teacher-sheet5-han"||scheduleFor("ĐÌNH BẢO",5,"16:00")?.teacherId!=="teacher-sheet5-quynh"||scheduleFor("DŨNG",5,"19:00")?.teacherId!=="teacher-sheet5-quynh")throw new Error("Lịch gốc thứ Bảy bị ghi đè bởi các ca đổi tạm trong T9 (2)");
if(!["DÂU TÂY","SU HÀO","PHÚC AN"].every(key=>sourceStudents.has(key))||["THU LEE","BÁ PHÚC","PHÚC"].some(key=>sourceStudents.has(key)))throw new Error("Danh sách học sinh thêm/xóa theo T9 (2) chưa đúng");
if(sourceStudents.has("DÂU")||T9_TEMPLATE_SOURCE.filter(item=>item.studentKey==="THIÊN MỸ").length!==3||![1,3,5].every(day=>scheduleFor("THIÊN MỸ",day,"17:00")?.teacherId==="teacher-sheet5-tien"))throw new Error("Dâu chưa được gộp đúng vào lịch Thiên Mỹ T3/T5/T7 17:00–18:00");
if(sourceStudents.has("HOÀNG PHÚC")||T9_TEMPLATE_SOURCE.filter(item=>item.studentKey==="HÀ CHÂU").length!==3||![1,3,5].every(day=>scheduleFor("HÀ CHÂU",day,"17:00")?.teacherId==="teacher-sheet5-han"))throw new Error("Lịch Hoàng Phúc chưa được chuyển hoàn toàn sang HÀ CHÂU");
if(T9_TEMPLATE_SOURCE.filter(item=>item.studentKey==="SU HÀO").length!==6||![0,1,2,3,4,5].every(day=>scheduleFor("SU HÀO",day,"08:00")?.teacherId==="teacher-sheet5-tien"))throw new Error("Lịch Su Hào chưa khớp sáu ô màu Cô Tiên trong T9 (2)");
if(scheduleFor("MAI ANH",5,"08:00")?.teacherId!=="teacher-sheet5-quynh"||![0,2,4,5].every(day=>scheduleFor("GIA HUY BẮP",day,"09:00")?.teacherId==="teacher-sheet5-quynh"))throw new Error("Các ô hồng của Mai Anh/Gia Huy - Bắp chưa được gán đúng Cô Quỳnh");
if(!T9_TEMPLATE_SOURCE.some(item=>item.studentKey==="XOÀI"&&item.dayOfWeek===0&&item.teacherId==="teacher-sheet5-mai")||T9_TEMPLATE_SOURCE.filter(item=>item.studentKey==="VY").length!==3)throw new Error("Lịch màu giáo viên của Xoài hoặc quy tắc bỏ ca Vy lẻ chưa đúng");

const browser = await chromium.launch({
  headless: true,
  executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe",
});
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.addInitScript(() => {
  localStorage.setItem("happychild:theme", "light");
  const NativeDate = Date;
  const fixedNow = new NativeDate("2026-08-14T12:00:00+07:00").getTime();
  class FixedDate extends NativeDate {
    constructor(...args) { super(...(args.length ? args : [fixedNow])); }
    static now() { return fixedNow; }
  }
  window.Date = FixedDate;
});
const errors = [];
page.on("pageerror", error => errors.push(error.message));

const authMock = `
export const login=async()=>{};
export const logout=async()=>{};
export const authErrorMessage=e=>e?.message||"error";
export const watchAuth=callback=>{setTimeout(()=>callback({uid:"test-user",email:"test@example.com"},{displayName:"Người kiểm thử",role:"authenticated",active:true}),0);return()=>{}};
`;
const storeMock = `
const ts=value=>({seconds:Math.floor(new Date(value).getTime()/1000),toDate:()=>new Date(value)});
const student={id:"student-1",fullName:"Bé An",shortName:"An",color:"#e879a9",active:true,makeupBalance:1,parentPhone:"",birthday:"2020-08-13"};
const student2={id:"student-2",fullName:"Bé Bình",shortName:"Bình",color:"#4f86e8",active:true,makeupBalance:1,parentPhone:"",birthday:"2020-08-14"};
const archivedStudent={id:"student-archived",fullName:"BEN SÁNG",shortName:"Ben",color:"#94a3b8",active:false,archived:true,archivedReason:"Không còn trong T9",makeupBalance:0,parentPhone:"",birthday:"2020-08-15"};
const teacher={id:"teacher-1",fullName:"Cô Ngân",shortName:"Cô Ngân",color:"#7c5ce7",active:true,phone:""};
const teacher2={id:"teacher-2",fullName:"Cô Mai",shortName:"Cô Mai",color:"#20a779",active:true,phone:""};
const week={id:"week-2026-08-10",weekNumber:1,label:"Tuần 1 (10/08/2026–16/08/2026)",startDate:ts("2026-08-10T12:00:00"),endDate:ts("2026-08-16T12:00:00"),status:"active"};
const template={id:"template-1",studentId:student.id,teacherId:teacher.id,dayOfWeek:0,startTime:"13:00",endTime:"14:00",capacity:1,active:true,note:""};
const templatePeer={...template,id:"template-2",studentId:student2.id,note:"Mang sách"};
const templateTeacher2={...template,id:"template-3",studentId:student2.id,teacherId:teacher2.id,dayOfWeek:1,startTime:"15:00",endTime:"16:00"};
const templateSameTimeTeacher2={...template,id:"template-4",studentId:student2.id,teacherId:teacher2.id,note:"Cùng giờ khác cô"};
const session={id:"session-1",studentId:student.id,teacherId:teacher.id,date:ts("2026-08-10T12:00:00"),dateKey:"2026-08-10",dayOfWeek:0,startTime:"13:00",endTime:"14:00",capacity:1,type:"regular",status:"absent",note:"Xin nghỉ"};
const recurringStudentSessions=[{...session,id:"session-1-wed",date:ts("2026-08-12T12:00:00"),dateKey:"2026-08-12",dayOfWeek:2,status:"attended",note:""},{...session,id:"session-1-fri",date:ts("2026-08-14T12:00:00"),dateKey:"2026-08-14",dayOfWeek:4,status:"scheduled",note:""}];
const groupedRegularPeers=Array.from({length:5},(_,index)=>({...session,id:"session-regular-"+(index+2),studentId:"slot-student-"+(index+2),status:"scheduled",note:""}));
const sameTimeTeacher2={...session,id:"same-time-teacher-2",studentId:"slot-student-teacher-2",teacherId:teacher2.id,status:"scheduled",note:""};
const earlySlotSession={...session,id:"early-slot-session",studentId:"early-slot-student",startTime:"09:00",endTime:"10:00",status:"scheduled",note:""};
const lateSlotSession={...session,id:"late-slot-session",studentId:"late-slot-student",startTime:"15:00",endTime:"16:00",status:"scheduled",note:""};
const filledSlotRegulars=Array.from({length:6},(_,index)=>({...session,id:"filled-regular-"+(index+1),studentId:"filled-student-"+(index+1),date:ts("2026-08-11T12:00:00"),dateKey:"2026-08-11",dayOfWeek:1,status:index===0?"absent":"scheduled",note:index===0?"Xin nghỉ":""}));
const filledSlotMakeup={...session,id:"filled-makeup",studentId:"makeup-student",date:ts("2026-08-11T12:00:00"),dateKey:"2026-08-11",dayOfWeek:1,capacity:20,type:"makeup",status:"makeup_scheduled",note:"Học bù vào chỗ trống"};
const attack='"><img id="stored-xss-marker" src=x onerror="window.__storedXss=1">';
const maliciousTemplate={id:'template-xss" onclick="window.__storedXss=2',studentId:student.id,teacherId:teacher.id,dayOfWeek:6,startTime:attack,endTime:attack,capacity:1,active:true,note:""};
const maliciousSession={id:'session-xss" onclick="window.__storedXss=3',studentId:student2.id,teacherId:teacher.id,date:ts("2026-08-16T12:00:00"),dateKey:"2026-08-16",dayOfWeek:6,startTime:attack,endTime:attack,capacity:1,type:attack,status:'scheduled" onmouseover="window.__storedXss=4',note:""};
const reportSession={...session,id:"report-1",status:"attended",capacity:7};
const reportSession2={...reportSession,id:"report-2",studentId:student2.id};
const note={id:"note-1",dateKey:"2026-08-13",title:"Mang sách",details:"Nhắc phụ huynh mang sách."};
const formCreated=ts("2026-04-01T12:00:00");
const studentForm={id:"form-1",studentId:student.id,teacherId:teacher.id,formLink:"https://docs.google.com/forms/d/e/example/viewform",formTitle:"Bé An 8/6 - 8/9",courseStart:"8/6",courseEnd:"8/9",coursePeriod:"8/6-8/9",resultRecordedDate:"2026-08-13",teacherHours:1.5,note:"Đã ghi nhận",displayOrder:1,sourceRow:3,createdAt:formCreated,linkHistory:[{formLink:"https://docs.google.com/forms/d/e/old-goal/viewform",formTitle:"Mục tiêu cũ của Bé An",coursePeriod:"1/3-1/6",archivedAt:ts("2026-06-02T12:00:00")}]};
const incompleteStudentForm={id:"form-2",studentId:student2.id,teacherId:teacher2.id,formLink:"https://docs.google.com/forms/d/e/missing/viewform",formTitle:"",courseStart:"",courseEnd:"",coursePeriod:"",resultRecordedDate:"2026-08-14",teacherHours:0,note:"Thiếu tiêu đề",displayOrder:2,sourceRow:4,createdAt:formCreated};
const noLinkStudentForm={id:"form-3",studentId:student2.id,teacherId:teacher.id,formLink:"",formTitle:"Bé Bình 1/1 - 1/2",courseStart:"1/1",courseEnd:"1/2",coursePeriod:"1/1-1/2",resultRecordedDate:"",teacherHours:1,note:"Thiếu link",displayOrder:3,sourceRow:5,createdAt:formCreated};
const manualStudentForm={id:"form-4",studentId:student.id,teacherId:teacher2.id,formLink:"https://docs.google.com/forms/d/e/manual/viewform",formTitle:"Bé An khóa mùa hè",courseStart:"10/6",courseEnd:"10/9",coursePeriod:"10/6-10/9",resultRecordedDate:"",teacherHours:1,note:"Khoảng ngày nhập tay",displayOrder:4,sourceRow:6,createdAt:formCreated};
const invalidYearStudentForm={id:"form-5",studentId:student2.id,teacherId:teacher.id,formLink:"https://docs.google.com/forms/d/e/tiger/viewform",formTitle:"Tiger 16/6 - 16/9/206",courseStart:"16/6",courseEnd:"16/9",coursePeriod:"16/6-16/9",resultRecordedDate:"",teacherHours:1,note:"Năm tiêu đề cần xác nhận",displayOrder:5,sourceRow:7,createdAt:formCreated};
const lateRecordedStudentForm={id:"form-6",studentId:student.id,teacherId:teacher.id,formLink:"https://docs.google.com/forms/d/e/late/viewform",formTitle:"Bé An 1/1/2026 - 1/2/2026",courseStart:"1/1/2026",courseEnd:"1/2/2026",coursePeriod:"1/1/2026-1/2/2026",resultRecordedDate:"2026-02-02",teacherHours:1,note:"Ghi muộn một ngày",displayOrder:6,sourceRow:8,createdAt:formCreated};
const dueTodayStudentForm={id:"form-7",studentId:student2.id,teacherId:teacher2.id,formLink:"https://docs.google.com/forms/d/e/today/viewform",formTitle:"Bé Bình 14/5/2026 - 14/8/2026",courseStart:"14/5/2026",courseEnd:"14/8/2026",coursePeriod:"14/5/2026-14/8/2026",resultRecordedDate:"",teacherHours:1,note:"Đến hạn hôm nay",displayOrder:7,sourceRow:9,createdAt:formCreated};
const beforeStartStudentForm={id:"form-8",studentId:student.id,teacherId:teacher.id,formLink:"https://docs.google.com/forms/d/e/before-start/viewform",formTitle:"Bé An 1/5/2026 - 1/8/2026",courseStart:"1/5/2026",courseEnd:"1/8/2026",coursePeriod:"1/5/2026-1/8/2026",resultRecordedDate:"2026-04-30",teacherHours:1,note:"Ngày ghi nhận sai",displayOrder:8,sourceRow:10,createdAt:formCreated};
export const subscribe=(name,cb)=>{setTimeout(()=>cb(name==="students"?[student,student2,archivedStudent]:name==="teachers"?[teacher,teacher2]:name==="scheduleTemplates"?[template,templatePeer,templateTeacher2,templateSameTimeTeacher2,maliciousTemplate]:name==="weeks"?[week]:[]),0);return()=>{}};
export const subscribeSessions=(id,cb)=>{setTimeout(()=>cb([earlySlotSession,session,...recurringStudentSessions,...groupedRegularPeers,sameTimeTeacher2,...filledSlotRegulars,filledSlotMakeup,lateSlotSession,maliciousSession]),0);return()=>{}};
export const subscribeNotes=cb=>{setTimeout(()=>cb([note]),0);return()=>{}};
export const subscribeStudentForms=cb=>{setTimeout(()=>cb([studentForm,incompleteStudentForm,noLinkStudentForm,manualStudentForm,invalidYearStudentForm,lateRecordedStudentForm,dueTodayStudentForm,beforeStartStudentForm]),0);return()=>{}};
export const subscribeRecentAudit=cb=>{setTimeout(()=>cb([]),0);return()=>{}};
export const subscribeTransactions=cb=>{setTimeout(()=>cb([]),0);return()=>{}};
export const saveStudent=async()=>{};
export const saveTeacher=async()=>{};
export const saveTeacherLeave=async()=>{};
export const deleteTeacherLeave=async()=>{};
export const saveTemplate=async data=>{window.__savedTemplate=data};
export const saveNote=async()=>{};
export const saveHoliday=async()=>({id:"holiday-1",updated:0});
export const deleteHoliday=async()=>0;
export const saveStudentForm=async data=>{window.__savedStudentForm=data};
export const saveSession=async()=>{window.__saveSessionCalls=(window.__saveSessionCalls||0)+1};
export const deleteStudent=async()=>{};
export const deleteTeacher=async()=>{};
export const deleteSession=async()=>{};
export const deleteWeek=async()=>{};
export const deleteStudentForm=async()=>{};
export const deleteMakeupTransaction=async()=>{};
export const purgeAllData=async()=>0;
export const removeRecord=async()=>{};
export const createWeek=async()=>week.id;
export const finalizeWeekSummary=async(id,summary)=>{window.__finalizedWeek={id,summary}};
export const updateSessionStatus=async()=>{};
export const markHolidayRange=async()=>({updated:0,total:0});
export const autoCompleteElapsedSessions=async(id,sessions,user,now)=>{window.__autoCompleteCalls=(window.__autoCompleteCalls||0)+1;window.__autoCompletePayload={id,sessionCount:sessions.length,now:now instanceof Date};return {updated:0,failed:[]}};
export const getTeacherAvailability=id=>id==="teacher-2"?({available:false,reason:"Giáo viên đã có lịch khác trùng giờ.",occupied:0,capacity:1}):({available:true,reason:"",occupied:5,capacity:6});
export const addMakeupSession=async()=>{};
export const seedData=async()=>{};
export const loadMonthReport=async()=>[reportSession,reportSession2];
export const loadStudentHistory=async id=>id===student.id?[session,{...session,id:"history-attended",status:"attended",note:"Hoàn thành tốt",weekId:week.id,weekNumber:week.weekNumber,weekLabel:week.label,weekStartDate:week.startDate,weekEndDate:week.endDate}]:[];
export const loadWeekSchedule=async()=>[earlySlotSession,session,...recurringStudentSessions,...groupedRegularPeers,sameTimeTeacher2,lateSlotSession];
export const loadTeacherWeekSchedule=async id=>id===teacher.id?[{...session,weekId:week.id,weekNumber:week.weekNumber,weekLabel:week.label,weekStartDate:week.startDate,weekEndDate:week.endDate}]:[];
export const normalizeAllScheduleHours=async()=>({templates:0,sessions:0,weeks:0});
export const syncScheduleTemplatesFromSource=async templates=>({templates:templates.length,updated:0,deleted:0,createdStudents:[]});
export const reconcileStudentRosterFromSource=async()=>({students:2,removed:[],archived:[],merged:[],stale:[],duplicates:[]});
`;

await page.route("**/happychild/js/auth.js*", route => route.fulfill({ contentType: "text/javascript", body: authMock }));
await page.route("**/happychild/js/store.js*", route => route.fulfill({ contentType: "text/javascript", body: storeMock }));
await page.goto("http://127.0.0.1:8080/happychild/", { waitUntil: "networkidle" });
await page.waitForSelector("#appView:not(.hidden)");
await page.waitForFunction(()=>Boolean(window.__autoCompleteCalls));
const autoCompletePayload=await page.evaluate(()=>window.__autoCompletePayload);
if (autoCompletePayload.id!=="week-2026-08-10" || !autoCompletePayload.sessionCount || !autoCompletePayload.now) throw new Error("Hệ thống chưa tự kiểm tra các buổi đã qua giờ sau khi tải lịch");
const elapsedTargets=await page.evaluate(async()=>{const {elapsedSessionTarget}=await import("/happychild/js/utils.js?v=20260826-5");const now=new Date("2026-08-14T12:00:00");return [elapsedSessionTarget({type:"regular",status:"scheduled",dateKey:"2026-08-14",endTime:"11:59"},now),elapsedSessionTarget({type:"makeup",status:"makeup_scheduled",dateKey:"2026-08-13",endTime:"18:00"},now),elapsedSessionTarget({type:"regular",status:"absent",dateKey:"2026-08-13",endTime:"18:00"},now),elapsedSessionTarget({type:"regular",status:"scheduled",dateKey:"2026-08-14",endTime:"12:01"},now)]});
if (JSON.stringify(elapsedTargets)!==JSON.stringify(["attended","makeup_completed",null,null])) throw new Error("Quy tắc tự hoàn thành buổi học theo thời gian chưa đúng");
const parsedScheduleTimes=await page.evaluate(async()=>{const {parseScheduleTimeRange}=await import("/happychild/js/utils.js?v=20260829-1");return ["8h-10h","9h","3h","4-5h","5h5-6h5","7h15-8h15","3 giờ đến 8h15","8h15","18h10-19h10","19h15-20h15"].map(parseScheduleTimeRange)});
const expectedScheduleTimes=[["08:00","10:00"],["09:00","10:00"],["15:00","16:00"],["16:00","17:00"],["17:00","18:00"],["19:00","20:00"],["15:00","20:00"],["08:00","09:00"],["18:00","19:00"],["19:00","20:00"]];
if (JSON.stringify(parsedScheduleTimes)!==JSON.stringify(expectedScheduleTimes)) throw new Error("Quy tắc nhận diện giờ sáng/PM hoặc ca một giờ chưa đúng");
if (await page.locator('.brand-logo.small img[src*="happychild-logo.jpg"]').count() !== 1) throw new Error("Logo Happy Child chưa xuất hiện ở thanh bên");
if (!(await page.locator('.brand-logo.small img').evaluate(image=>image.complete&&image.naturalWidth>0))) throw new Error("Tệp logo Happy Child không tải được");
await page.waitForSelector("#briefingDialog[open]");
if (await page.locator("#briefingBody .brief-day").count() !== 2) throw new Error("Popup không đủ Hôm nay/Ngày mai");
await page.click("#briefingDone");
if (await page.locator("#themeToggleBtn").count() !== 1) throw new Error("Header thiếu nút chuyển chế độ sáng/tối");
if (await page.locator("#themeToggleBtn").getAttribute("aria-pressed") !== "false") throw new Error("Nút giao diện không phản ánh chế độ sáng ban đầu");
await page.click("#themeToggleBtn");
if (await page.locator("html").getAttribute("data-theme") !== "dark" || await page.locator("#themeToggleBtn").getAttribute("aria-pressed") !== "true") throw new Error("Không chuyển được sang chế độ tối");
if (await page.evaluate(()=>localStorage.getItem("happychild:theme")) !== "dark") throw new Error("Chế độ tối chưa được lưu trên trình duyệt");
if ((await page.locator(".topbar").evaluate(element=>getComputedStyle(element).backgroundColor)) === "rgb(255, 255, 255)") throw new Error("Header vẫn dùng nền trắng trong chế độ tối");
if(process.env.HAPPYCHILD_DARK_BRIEFING_SCREENSHOT){await page.evaluate(()=>document.querySelector("#briefingDialog").showModal());await page.screenshot({path:process.env.HAPPYCHILD_DARK_BRIEFING_SCREENSHOT,fullPage:true});await page.click("#briefingDone")}
if (process.env.HAPPYCHILD_DARK_SCREENSHOT){await page.click('a[href="#templates"]');await page.waitForSelector(".template-day-group");await page.screenshot({path:process.env.HAPPYCHILD_DARK_SCREENSHOT,fullPage:true})}
await page.click("#themeToggleBtn");

await page.click('a[href="#calendar"]');
await page.waitForSelector(".student-week-schedule");
if (await page.locator("#calendarStudentSearch").count() !== 1) throw new Error("Lịch tuần thiếu tìm kiếm theo tên học sinh");
await page.fill("#calendarStudentSearch", "Bé Bình");
if (!(await page.locator("#content").textContent()).includes("Kết quả cho “Bé Bình”")) throw new Error("Tìm lịch học sinh không kích hoạt chế độ lọc");
if (await page.locator('[data-session="session-1"]').count()) throw new Error("Tìm lịch vẫn hiển thị buổi của học sinh khác");
if (await page.locator('.weekly-student-row[data-student-id="student-2"]').count() !== 1) throw new Error("Tìm lịch chưa đưa đúng học sinh về một dòng duy nhất");
await page.click("#clearCalendarSearch");
const timeCluster=page.locator('.student-schedule-cluster[data-time-slot="13:00|14:00"]');
const timeClusterText=await timeCluster.textContent();
if (await timeCluster.count() !== 1 || !["Cô Ngân","Cô Mai"].every(name=>timeClusterText.includes(name))) throw new Error("Lịch tuần chưa lấy khung giờ làm nhóm chính và liệt kê đủ giáo viên bên trong");
if (await timeCluster.locator(".weekly-student-row").count() < 7) throw new Error("Các bé cùng khung giờ chưa được xếp liền nhau");
const orderedSlots=await page.locator(".student-schedule-cluster .cluster-title strong").allTextContents();
if (JSON.stringify(orderedSlots.slice(0,3))!==JSON.stringify(["09:00–10:00","13:00–14:00","15:00–16:00"]) || orderedSlots.at(-1)!=="Chưa xác định giờ") throw new Error("Các khung giờ chưa được xếp từ sớm đến muộn như T9.xlsx");
const anRow=page.locator('.weekly-student-row[data-student-id="student-1"]');
const anRowText=await anRow.textContent();
if (await anRow.count() !== 1 || !["T2","T4","T6","Nghỉ"].every(label=>anRowText.includes(label))) throw new Error("Một bé chưa được gom thành một dòng có đủ ngày, giờ và trạng thái");
if (await anRow.locator(".student-schedule-pattern").count() !== 1 || await anRow.locator(".weekly-day-session").count() !== 3) throw new Error("Các buổi cùng giờ/cùng cô của một bé chưa được gộp vào cùng một cụm");
const fixedDayGrid=await anRow.locator(".student-pattern-days").evaluate(grid=>({display:getComputedStyle(grid).display,columns:getComputedStyle(grid).gridTemplateColumns.split(" ").length,occupied:[...grid.querySelectorAll(":scope > .weekly-day-cell")].map(cell=>Boolean(cell.querySelector(".weekly-day-session"))),days:[...grid.querySelectorAll(":scope > .weekly-day-cell")].map(cell=>cell.dataset.day)}));
if (fixedDayGrid.display!=="grid" || fixedDayGrid.columns!==7 || JSON.stringify(fixedDayGrid.days)!==JSON.stringify(["0","1","2","3","4","5","6"])) throw new Error("Lịch tuần chưa giữ lưới cố định đủ 7 cột từ T2 đến CN");
if (JSON.stringify(fixedDayGrid.occupied)!==JSON.stringify([true,false,true,false,true,false,false])) throw new Error("Ngày không có tiết đang bị dồn trái thay vì để trống đúng cột");
if (await page.locator('.weekly-student-row[data-student-id="student-2"]').count() !== 1) throw new Error("Một học sinh có nhiều buổi đang bị lặp thành nhiều dòng");
const sessionHardening=await page.evaluate(()=>{const card=[...document.querySelectorAll("[data-session]")].find(element=>element.dataset.session.startsWith("session-xss")),pattern=card?.closest(".student-schedule-pattern"),timeText=pattern?.querySelector(".student-pattern-info strong")?.textContent||"";return {marker:Boolean(document.querySelector("#stored-xss-marker")),executed:Boolean(window.__storedXss),found:Boolean(card),safeStatus:card?.classList.contains("scheduled"),inlineHandler:card?.hasAttribute("onclick")||card?.hasAttribute("onmouseover"),text:card?.textContent||"",timeText}});
if (sessionHardening.marker || sessionHardening.executed || !sessionHardening.found || !sessionHardening.safeStatus || sessionHardening.inlineHandler) throw new Error("Stored-XSS từ dữ liệu buổi học chưa được chặn");
if (sessionHardening.text.includes("<img") || sessionHardening.timeText.includes("<img") || !sessionHardening.timeText.includes("Chưa xác định giờ")) throw new Error("Giờ học không hợp lệ chưa được thay bằng giá trị an toàn dễ hiểu");
if (await page.locator("#deleteWeekBtn").count() !== 1) throw new Error("Thiếu nút xóa tuần");
const slotTeacherColor=await page.locator('[data-session="session-1"]').evaluate(element=>getComputedStyle(element.closest(".student-schedule-pattern")).getPropertyValue("--teacher").trim().toLowerCase());
if (slotTeacherColor !== "#7c5ce7") throw new Error("Lịch của học sinh chưa dùng màu của giáo viên");
const dayTeacherStripe=await page.locator('[data-session="session-1"]').evaluate(element=>getComputedStyle(element,"::before").backgroundColor.replace(/\s+/g,""));
if (dayTeacherStripe !== "rgb(124,92,231)") throw new Error("Nút thứ học chưa in trực tiếp màu của giáo viên");
const teacher2ChildColor=await page.locator('[data-session="same-time-teacher-2"]').evaluate(element=>getComputedStyle(element.closest(".student-schedule-pattern")).getPropertyValue("--teacher").trim().toLowerCase());
if (teacher2ChildColor !== "#20a779") throw new Error("Lịch cùng giờ khác cô chưa giữ đúng màu giáo viên");
await anRow.locator(".open-week-student").click();
await page.waitForSelector("#studentProfileDialog[open]");
if (!(await page.locator("#studentProfileTitle").textContent()).includes("Bé An")) throw new Error("Bấm tên bé trong lịch chưa mở đúng hồ sơ học tập");
if (await page.locator(".profile-makeup-planner").count() !== 1 || await page.locator(".makeup-slot-option").count() < 1) throw new Error("Hồ sơ học sinh chưa có bộ chọn học bù theo khung giờ tuần hiện tại");
if (await page.locator('.makeup-teacher-choice[data-teacher="teacher-1"].is-available').count() < 1 || await page.locator('.makeup-teacher-choice[data-teacher="teacher-2"].is-busy').count() < 1) throw new Error("Danh sách giáo viên chưa làm nổi bật cô rảnh và làm mờ cô bận");
await page.locator(".profile-makeup-planner>summary").click();
await page.locator('.makeup-teacher-choice[data-teacher="teacher-1"].is-available').first().click();
await page.waitForSelector("#formDialog[open]");
if ((await page.locator("#dialogTitle").textContent()).trim() !== "Sắp xếp lịch học bù" || !(await page.locator("#dialogBody").textContent()).includes("Giáo viên đang rảnh")) throw new Error("Bấm giáo viên rảnh chưa mở popup sắp xếp học bù");
await page.click("#dialogCancel");
await page.click("#studentProfileClose");
await page.evaluate(()=>scrollTo(0,0));
if (process.env.HAPPYCHILD_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_SCREENSHOT,fullPage:true});
await page.click('[data-session="session-1"]');
await page.waitForSelector("#sessionDrawer:not(.hidden)");
if (await page.locator("#sessionDrawer").getAttribute("role") !== "dialog" || !(await page.locator("#closeDrawer").evaluate(button=>button===document.activeElement))) throw new Error("Drawer chi tiết chưa có ngữ nghĩa dialog hoặc chưa nhận focus");
await page.keyboard.press("Escape");
await page.waitForFunction(()=>document.querySelector("#sessionDrawer")?.classList.contains("hidden"));
if (!(await page.locator('[data-session="session-1"]').evaluate(card=>card===document.activeElement))) throw new Error("Đóng drawer chưa trả focus về buổi học");
await page.click('[data-session="session-1"]');
await page.waitForSelector("#sessionDrawer:not(.hidden)");
await page.click(".makeup-candidate");
await page.waitForSelector("#formDialog[open]");
if (await page.locator('select[name="teacherId"] option:not(:disabled)').count() !== 1) throw new Error("Danh sách giáo viên trống không đúng");
if (await page.locator('select[name="teacherId"] option:disabled').count() !== 1) throw new Error("Không hiển thị giáo viên đang bận");
if (!(await page.locator("#dialogBody").textContent()).includes("5/6 chỗ đang dùng")) throw new Error("Form học bù chưa hiển thị đúng sức chứa gộp");
await page.click("#dialogCancel");
await anRow.locator(".weekly-student-add").click();
await page.waitForSelector("#formDialog[open]");
if ((await page.inputValue('input[name="capacity"]')) !== "1") throw new Error("Thêm lịch thường vào khung gộp đã lấy sai tổng capacity thay vì mặc định 1");
if ((await page.inputValue('select[name="studentId"]')) !== "student-1") throw new Error("Nút thêm cạnh học sinh chưa chọn sẵn đúng bé");
await page.click("#dialogCancel");
await page.click("#addSessionTop");
await page.waitForSelector("#formDialog[open]");
if (await page.locator('select[name="studentId"]').count() !== 1) throw new Error("Thiếu chọn học sinh trong form buổi học");
if (await page.locator('select[name="teacherId"]').count() !== 1) throw new Error("Thiếu chọn giáo viên trong form buổi học");
await page.click("#dialogCancel");
if ((await page.evaluate(()=>window.__saveSessionCalls||0)) !== 0) throw new Error("Nút Hủy đã gọi lưu dữ liệu");

await page.click("#addSessionTop");
await page.fill('input[name="startTime"]', "13:00");
await page.fill('input[name="endTime"]', "14:00");
await page.click("#dialogSubmit");
await page.waitForFunction(()=>window.__saveSessionCalls===1);

await page.click('a[href="#teachers"]');
await page.waitForSelector("#addTeacher");
if (await page.locator(".delete-teacher").count() !== 2) throw new Error("Thiếu thùng rác giáo viên");
if (await page.locator(".teacher-roster-group").count() !== 2) throw new Error("Trang giáo viên chưa nhóm danh sách học sinh theo từng cô");
if (await page.locator(".teacher-roster-group[open]").count() !== 1) throw new Error("Danh sách giáo viên chưa mặc định chỉ mở một nhóm");
if ((await page.locator('[data-teacher-id="teacher-1"] .teacher-student-count').textContent()).trim() !== "2 học sinh") throw new Error("Số học sinh của cô chưa được tổng hợp đúng từ lịch mẫu");
if ((await page.locator('[data-teacher-id="teacher-1"] [data-roster-student-id="student-1"] strong').textContent()).trim() !== "Bé An") throw new Error("Thiếu học sinh trong nhóm giáo viên phụ trách");
if ((await page.locator('[data-teacher-id="teacher-1"] .roster-number').first().textContent()).trim() !== "1") throw new Error("STT cục bộ trong nhóm giáo viên không bắt đầu từ 1");
await page.fill("#teacherRosterSearch", "Bé Bình");
if (await page.locator(".teacher-roster-group:visible").count() !== 1 || (await page.locator("#teacherRosterResultCount").textContent()).trim() !== "1 giáo viên") throw new Error("Tìm học sinh trên trang Giáo viên không lọc đúng cô phụ trách");
await page.fill("#teacherRosterSearch", "");
await page.setViewportSize({width:375,height:800});
const teacherMobileLayout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,columns:getComputedStyle(document.querySelector(".teacher-student-grid")).gridTemplateColumns}));
if (teacherMobileLayout.overflow>1 || teacherMobileLayout.columns.split(" ").length!==1) throw new Error("Danh sách giáo viên bị tràn hoặc chưa về một cột trên mobile");
const mobileThemeButton=await page.locator("#themeToggleBtn").evaluate(button=>({visible:button.getBoundingClientRect().width>=36,label:getComputedStyle(button.querySelector(".theme-toggle-label")).display,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}));
if(!mobileThemeButton.visible||mobileThemeButton.label!=="none"||mobileThemeButton.overflow>1)throw new Error("Nút chế độ tối trên header mobile bị ẩn hoặc gây tràn ngang");
await page.setViewportSize({width:1440,height:900});
await page.locator('[data-teacher-id="teacher-1"] .teacher-profile-strip').click();
await page.waitForSelector('#studentProfileDialog[open] #teacherLeaveBtn');
if (!(await page.locator("#studentProfileBody").textContent()).includes("Lịch sử nghỉ phép")) throw new Error("Hồ sơ giáo viên thiếu lịch sử nghỉ phép");
await page.click("#teacherLeaveBtn");
await page.waitForSelector('#formDialog[open] input[name="fullDay"]');
if (await page.locator('input[name="startDate"]').count() !== 1 || await page.locator('input[name="endDate"]').count() !== 1) throw new Error("Form nghỉ phép giáo viên thiếu khoảng ngày");
await page.uncheck('input[name="fullDay"]');
if (await page.locator('.teacher-leave-time:not([hidden]) input[type="time"]').count() !== 2) throw new Error("Form nghỉ một buổi chưa hiện giờ bắt đầu và kết thúc");
await page.click("#dialogCancel");
await page.click("#teacherLeaveBtn");
await page.fill('input[name="startDate"]', "2026-08-12");
await page.fill('input[name="endDate"]', "2026-08-12");
await page.check('input[name="fullDay"]');
await page.click("#dialogSubmit");
await page.waitForFunction(()=>document.querySelector("#dialogTitle")?.textContent.includes("Xếp cô dạy thay"));
if (await page.locator(".teacher-replacement-row").count() !== 1 || !(await page.locator(".teacher-replacement-row").textContent()).includes("Bé An")) throw new Error("Nghỉ phép chưa liệt kê đúng học sinh cần xếp cô dạy thay");
if (await page.locator('.teacher-replacement-row select option[value="teacher-1"]').count()) throw new Error("Danh sách dạy thay vẫn chứa chính giáo viên xin nghỉ");
await page.click("#dialogCancel");
await page.click("#studentProfileClose");
await page.click("#addTeacher");
await page.waitForSelector('input[name="fullName"]');
if (await page.locator('input[name="birthday"]').count() !== 1) throw new Error("Form giáo viên thiếu ngày sinh");
await page.click("#dialogClose");

await page.click('a[href="#students"]');
await page.waitForSelector("#addStudent");
if (await page.locator(".delete-student").count() !== 2) throw new Error("Thiếu thùng rác học sinh");
if(await page.locator('[data-student-id="student-archived"]').count()|| (await page.locator("#content").textContent()).includes("BEN SÁNG"))throw new Error("Học sinh đã loại khỏi T9 vẫn xuất hiện trong danh sách hiện hành");
const initialStudentNumbers=await page.locator(".student-table tbody tr[data-student-id] .student-index").allTextContents();
if (initialStudentNumbers.join(",") !== "1,2") throw new Error("Học sinh chưa được đánh STT global liên tục");
if ((await page.locator('[data-student-id="student-1"] [data-label="Giáo viên dạy"]').textContent()).trim() !== "Cô Ngân") throw new Error("Trang Học sinh chưa hiển thị đúng giáo viên từ Link Form");
if (await page.locator(".student-table tr.is-incomplete").count() !== 2 || !(await page.locator(".student-profile-warning").textContent()).includes("2")) throw new Error("Hồ sơ học sinh thiếu thông tin chưa được báo đỏ và tổng hợp");
if (!(await page.locator('[data-student-id="student-1"] .student-missing-text').textContent()).includes("SĐT phụ huynh")) throw new Error("Cảnh báo đỏ chưa nêu rõ trường thông tin học sinh còn thiếu");
await page.selectOption("#studentProfileFilter", "incomplete");
if (await page.locator(".student-table tbody tr[data-student-id]:visible").count() !== 2) throw new Error("Bộ lọc học sinh thiếu thông tin không đúng");
await page.selectOption("#studentProfileFilter", "all");
await page.selectOption("#studentTeacherFilter", "teacher-2");
if (await page.locator(".student-table tbody tr[data-student-id]:visible").count() !== 1) throw new Error("Bộ lọc giáo viên trên trang Học sinh không đúng");
if ((await page.locator(".student-table tbody tr[data-student-id]:visible").getAttribute("data-student-index")) !== "2") throw new Error("Lọc giáo viên đã đánh lại STT thay vì giữ số global");
await page.selectOption("#studentTeacherFilter", "all");
if ((await page.locator("#studentResultCount").textContent()).trim() !== "2 học sinh") throw new Error("Bộ đếm học sinh không khôi phục sau khi bỏ lọc");
if (process.env.HAPPYCHILD_STUDENTS_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_STUDENTS_SCREENSHOT,fullPage:true});
await page.locator('.student-table tbody tr[data-student-id="student-1"]').click();
await page.waitForSelector("#studentProfileDialog[open]");
await page.waitForFunction(()=>document.querySelector("#studentProfileBody")?.textContent.includes("Hoàn thành tốt"));
const profileText=await page.locator("#studentProfileBody").textContent();
if (!profileText.includes("Tuần hiện tại") || !profileText.includes("Tháng hiện tại") || !profileText.includes("Tất cả thời gian")) throw new Error("Hồ sơ học sinh thiếu ba phạm vi tổng hợp");
if (await page.locator("#studentProfileBody details.profile-week[open]").count() !== 1) throw new Error("Hồ sơ học sinh chưa xổ tuần hiện tại mặc định");
if (process.env.HAPPYCHILD_PROFILE_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_PROFILE_SCREENSHOT,fullPage:true});
await page.click("#studentProfileClose");
await page.setViewportSize({width:375,height:800});
const studentMobileLayout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,display:getComputedStyle(document.querySelector(".student-table tbody tr[data-student-id]")).display,label:getComputedStyle(document.querySelector('.student-table td[data-label="Giáo viên dạy"]'),"::before").content}));
if (studentMobileLayout.overflow>1 || studentMobileLayout.display!=="grid" || !studentMobileLayout.label.includes("Giáo viên dạy")) throw new Error("Danh sách học sinh bị tràn hoặc thiếu nhãn card trên mobile");
await page.setViewportSize({width:1440,height:900});
await page.click("#addStudent");
if (await page.locator('input[name="birthday"]').count() !== 1) throw new Error("Form học sinh thiếu ngày sinh");
await page.click("#dialogCancel");

await page.click('a[href="#forms"]');
await page.waitForSelector("#addStudentForm");
if (await page.locator(".form-teacher-group").count() !== 2) throw new Error("Link Form chưa nhóm theo giáo viên");
if (await page.locator(".form-teacher-group[open]").count() !== 1) throw new Error("Danh sách Link Form desktop chưa mặc định thu gọn");
if (await page.locator(".delete-student-form").count() !== 8) throw new Error("Thiếu thùng rác Link Form");
if (await page.locator(".form-page-warning").count() !== 1) throw new Error("Thiếu cảnh báo Link Form chưa có tiêu đề/thời gian");
if (!(await page.locator(".form-page-warning").textContent()).includes("3")) throw new Error("Không cảnh báo đủ mục thiếu link/năm hợp lệ");
if (await page.locator('.form-link[target="_blank"][rel~="noopener"]').count() !== 7) throw new Error("Link Form không mở an toàn ở tab mới");
if (!(await page.locator('.form-row[data-id="form-1"] td[data-label="Link"]').textContent()).includes("Link 1") || !(await page.locator('.form-row[data-id="form-1"] td[data-label="Link"]').textContent()).includes("Mục tiêu cũ")) throw new Error("Link Form chưa hiển thị lịch sử mục tiêu cũ");
if ((await page.locator('.form-row[data-id="form-2"] td[data-label="TG GV"]').textContent()).trim() !== "—") throw new Error("TG GV bằng 0 chưa hiển thị dạng trống");
const resultSummary=await page.locator(".form-result-kpi strong").allTextContents();
if (resultSummary.join(",") !== "8,2,1,3,2") throw new Error(`Tổng kết kết quả sai: ${resultSummary.join(",")}`);
if (await page.locator(".form-result-cell.result-late").count() !== 2) throw new Error("Không tô đúng hai ô kết quả trễ");
if (!(await page.locator('.form-row[data-id="form-3"] .form-result-cell').textContent()).includes("Cô trễ kết quả") || !(await page.locator('.form-row[data-id="form-3"] .form-result-cell').textContent()).includes("Chưa ghi nhận")) throw new Error("Thiếu cảnh báo đỏ cho Form quá hạn chưa ghi nhận");
if (!(await page.locator('.form-row[data-id="form-6"] .form-result-cell').textContent()).includes("trễ 1 ngày")) throw new Error("Ngày ghi nhận sau hạn chưa tính đúng số ngày trễ");
if (!(await page.locator('.form-row[data-id="form-1"] .form-result-cell').textContent()).includes("Đúng hạn")) throw new Error("Ngày ghi nhận trước hạn chưa được đánh dấu đúng hạn");
if (!(await page.locator('.form-row[data-id="form-7"] .form-result-cell').textContent()).includes("Đến hạn hôm nay")) throw new Error("Hạn đúng hôm nay bị tính trễ");
if (!(await page.locator('.form-row[data-id="form-2"] .form-result-cell').textContent()).includes("Cần kiểm tra")) throw new Error("Form thiếu ngày kết thúc chưa có trạng thái riêng");
if (!(await page.locator('.form-row[data-id="form-8"] .form-result-cell').textContent()).includes("trước ngày bắt đầu")) throw new Error("Ngày ghi nhận trước ngày bắt đầu chưa bị chặn");
if ((await page.locator('[data-teacher-group="teacher-1"] .form-late-visible-count').textContent()).trim() !== "2") throw new Error("Tổng trễ theo giáo viên không đúng");
const formTeacherColor=await page.locator('[data-teacher-group="teacher-1"]').evaluate(element=>getComputedStyle(element).getPropertyValue("--teacher").trim().toLowerCase());
if (formTeacherColor !== "#7c5ce7") throw new Error("Nhóm Link Form chưa dùng màu giáo viên");
await page.fill("#studentFormSearch", "Bé An 8/6");
if ((await page.locator(".form-row:visible").count()) !== 1) throw new Error("Tìm kiếm Link Form không lọc đúng học sinh");
await page.fill("#studentFormSearch", "");
await page.selectOption("#studentFormTeacherFilter", "teacher-2");
if ((await page.locator(".form-row:visible").count()) !== 3) throw new Error("Bộ lọc giáo viên Link Form không đúng");
await page.selectOption("#studentFormTeacherFilter", "all");
await page.selectOption("#studentFormResultFilter", "late");
if ((await page.locator(".form-row:visible").count()) !== 2 || !(await page.locator("#studentFormResultCount").textContent()).includes("2/8")) throw new Error("Bộ lọc trễ kết quả hoặc bộ đếm không đúng");
await page.selectOption("#studentFormResultFilter", "all");
if (process.env.HAPPYCHILD_FORMS_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_FORMS_SCREENSHOT,fullPage:true});

await page.click('.form-row[data-id="form-5"] .edit-student-form');
if ((await page.inputValue('input[name="courseStart"]')) !== "16/6" || (await page.inputValue('input[name="courseEnd"]')) !== "16/9" || (await page.inputValue('input[name="coursePeriod"]')) !== "16/6-16/9") throw new Error("Form Tiger không giữ đúng ngày/tháng đã tách để xác nhận");
const tigerHint=await page.locator("#formPeriodHint").textContent();
if (!tigerHint.includes("tạm giữ ngày/tháng") || tigerHint.includes("đã được xóa")) throw new Error("Thông báo Tiger mâu thuẫn với thời gian đang hiển thị");
await page.click("#dialogCancel");

await page.click('.form-row[data-id="form-1"] .edit-student-form');
await page.fill('input[name="formTitle"]', "Bé An không có khoảng ngày");
if ((await page.inputValue('input[name="courseStart"]')) !== "" || (await page.inputValue('input[name="courseEnd"]')) !== "" || (await page.inputValue('input[name="coursePeriod"]')) !== "") throw new Error("Đổi tiêu đề đã giữ sai thời gian tự động cũ");
if (!(await page.locator("#formPeriodHint").textContent()).includes("đã được xóa")) throw new Error("Thiếu cảnh báo đã xóa thời gian tự động cũ");
await page.evaluate(()=>{window.__savedStudentForm=null});
await page.click("#dialogSubmit");
await page.waitForFunction(()=>Boolean(window.__savedStudentForm));
const clearedStudentForm=await page.evaluate(()=>window.__savedStudentForm);
if (clearedStudentForm.courseStart || clearedStudentForm.courseEnd || clearedStudentForm.coursePeriod) throw new Error("Payload vẫn lưu thời gian tự động cũ sau khi đổi tiêu đề");

await page.click('.form-row[data-id="form-4"] .edit-student-form');
if (!(await page.locator("#formPeriodHint").textContent()).includes("thủ công")) throw new Error("Không nhận diện khoảng thời gian nhập thủ công");
await page.fill('input[name="formTitle"]', "Bé An khóa hè đã đổi tên");
if ((await page.inputValue('input[name="courseStart"]')) !== "10/6" || (await page.inputValue('input[name="courseEnd"]')) !== "10/9" || (await page.inputValue('input[name="coursePeriod"]')) !== "10/6-10/9") throw new Error("Đổi tiêu đề làm mất thời gian nhập thủ công");
if (!(await page.locator("#formPeriodHint").textContent()).includes("giữ thời gian nhập thủ công")) throw new Error("Thiếu nhãn giữ thời gian thủ công");
await page.click("#dialogCancel");

await page.evaluate(()=>{window.__savedStudentForm=null});
await page.click("#addStudentForm");
await page.waitForSelector('input[name="formTitle"]');
if ((await page.inputValue('input[name="resultRecordedDate"]')) !== "") throw new Error("Form mới tự điền sai ngày ghi nhận");
if (!(await page.locator("#formPeriodHint").textContent()).includes("tiêu đề Form")) throw new Error("Form Link thiếu hướng dẫn nhập tiêu đề");
await page.fill('input[name="formTitle"]', "Nam Hy 8/6 - 8/9");
if ((await page.inputValue('input[name="courseStart"]')) !== "8/6") throw new Error("Không tự tách ngày bắt đầu từ tiêu đề Form");
if ((await page.inputValue('input[name="courseEnd"]')) !== "8/9") throw new Error("Không tự tách ngày kết thúc từ tiêu đề Form");
if (!(await page.inputValue('input[name="coursePeriod"]')).includes("8/6") || !(await page.inputValue('input[name="coursePeriod"]')).includes("8/9")) throw new Error("Không tự điền thời gian Link Form");
await page.fill('input[name="formLink"]', "https://docs.google.com/forms/d/e/new-form/viewform");
await page.fill('input[name="teacherHours"]', "1.5");
await page.click("#dialogSubmit");
await page.waitForFunction(()=>Boolean(window.__savedStudentForm));
const savedStudentForm=await page.evaluate(()=>window.__savedStudentForm);
if (savedStudentForm.formLink !== "https://docs.google.com/forms/d/e/new-form/viewform") throw new Error("Không lưu đúng formLink");
if (savedStudentForm.courseStart !== "8/6" || savedStudentForm.courseEnd !== "8/9" || !savedStudentForm.coursePeriod.includes("8/9")) throw new Error("Payload Link Form thiếu thời gian đã tách");
if (!savedStudentForm.studentId || !savedStudentForm.teacherId) throw new Error("Payload Link Form thiếu liên kết học sinh/giáo viên");

await page.click('a[href="#templates"]');
await page.waitForSelector("#addTemplate");
if (await page.locator(".delete-template").count() !== 5) throw new Error("Thiếu thùng rác lịch mẫu");
if (await page.locator(".template-day-group").count() !== 3) throw new Error("Lịch mẫu chưa được nhóm theo thứ");
if (await page.locator(".template-slot-group").count() !== 3) throw new Error("Lịch mẫu chưa gộp đúng mỗi khung giờ thành một dropdown");
if (await page.locator(".template-teacher-group").count() !== 4) throw new Error("Lịch mẫu thiếu nhóm giáo viên bên trong khung giờ");
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Lịch mẫu chưa mặc định thu gọn hoàn toàn");
const mondayTemplateSlot=page.locator('.template-day-group[data-template-day="0"] .template-slot-group[data-start="13:00"][data-end="14:00"]');
if (await mondayTemplateSlot.count() !== 1 || await mondayTemplateSlot.locator(".template-teacher-group").count() !== 2) throw new Error("Hai cô cùng giờ chưa nằm trong một dropdown khung giờ");
const mondayTemplateSummary=await mondayTemplateSlot.locator("summary").textContent();
if (!mondayTemplateSummary.includes("Cô Ngân") || !mondayTemplateSummary.includes("Cô Mai") || !mondayTemplateSummary.includes("3 học sinh")) throw new Error("Tóm tắt lịch mẫu thiếu giờ, cô hoặc tổng học sinh");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "5/5 lịch") throw new Error("Bộ đếm lịch mẫu ban đầu không đúng");
if (!(await page.locator('.template-student-row[data-template-id="template-1"] .template-capacity').textContent()).includes("1 chỗ/lịch")) throw new Error("Lịch mẫu không hiển thị sức chứa mặc định 1 chỗ/lịch");
const templateTeacherColor=await mondayTemplateSlot.locator('.template-teacher-group[data-teacher="teacher-1"]').evaluate(element=>getComputedStyle(element).getPropertyValue("--teacher").trim());
if (templateTeacherColor.toLowerCase() !== "#7c5ce7") throw new Error("Khung lịch mẫu không dùng màu giáo viên");
const templateChildColor=await page.locator('.template-student-row[data-template-id="template-4"]').evaluate(element=>getComputedStyle(element).getPropertyValue("--student").trim().toLowerCase());
if (templateChildColor !== "#20a779") throw new Error("Màu học sinh trong lịch mẫu chưa theo giáo viên của từng buổi");
if (process.env.HAPPYCHILD_TEMPLATES_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_TEMPLATES_SCREENSHOT,fullPage:true});
await page.fill("#templateSearch","Bé Bình");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "3/5 lịch" || await page.locator('.template-student-row:not([hidden])').count() !== 3) throw new Error("Tìm học sinh trong lịch mẫu không đúng");
if (await page.locator('.template-day-group:not([hidden])[open]').count() !== 2 || await page.locator('.template-slot-group:not([hidden])[open]').count() !== 2) throw new Error("Tìm lịch mẫu không tự mở đúng ngày và khung giờ");
if (process.env.HAPPYCHILD_TEMPLATES_FILTERED_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_TEMPLATES_FILTERED_SCREENSHOT,fullPage:true});
await page.fill("#templateSearch","");
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Xóa bộ lọc chưa thu gọn lại lịch mẫu");
await page.selectOption("#templateTeacherFilter","teacher-2");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "2/5 lịch") throw new Error("Lọc lịch mẫu theo giáo viên không đúng");
await page.selectOption("#templateDayFilter","0");
await page.fill("#templateSearch","Bé Bình");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "1/5 lịch" || await page.locator('.template-day-group:not([hidden])[open]').count() !== 1 || await page.locator('.template-slot-group:not([hidden])[open]').count() !== 1) throw new Error("Kết hợp tìm kiếm, giáo viên và thứ chưa lọc/mở đúng khung giờ");
if (await mondayTemplateSlot.locator('.template-teacher-group[data-teacher="teacher-1"]:not([hidden])').count()) throw new Error("Nhóm cô không khớp vẫn hiện sau khi lọc kết hợp");
await page.fill("#templateSearch","");
await page.selectOption("#templateTeacherFilter","all");
await page.selectOption("#templateDayFilter","6");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "1/5 lịch") throw new Error("Lọc lịch mẫu theo thứ không đúng");
await page.selectOption("#templateDayFilter","all");
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Lịch mẫu không thu gọn sau khi xóa toàn bộ bộ lọc");
await page.click("#expandTemplateGroups");
if (await page.locator(".template-day-group[open]").count() !== 3 || await page.locator(".template-slot-group[open]").count() !== 3) throw new Error("Nút Mở tất cả lịch mẫu không hoạt động");
await page.click("#collapseTemplateGroups");
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Nút Thu gọn lịch mẫu không hoạt động");
const templateHardening=await page.evaluate(()=>{const button=[...document.querySelectorAll(".edit-template")].find(element=>element.dataset.id.startsWith("template-xss")),row=button?.closest(".template-student-row");return {marker:Boolean(document.querySelector("#stored-xss-marker")),executed:Boolean(window.__storedXss),found:Boolean(button),inlineHandler:button?.hasAttribute("onclick"),text:row?.textContent||""}});
if (templateHardening.marker || templateHardening.executed || !templateHardening.found || templateHardening.inlineHandler || templateHardening.text.includes("<img")) throw new Error("Stored-XSS từ lịch mẫu chưa được chặn");
await page.evaluate(()=>{window.__savedTemplate=null});
await page.click("#addTemplate");
if (await page.locator('select[name="teacherId"]').count() !== 1) throw new Error("Lịch mẫu thiếu giáo viên");
await page.selectOption('select[name="studentId"]',"student-2");
await page.selectOption('select[name="dayOfWeek"]',"2");
await page.click("#dialogSubmit");
await page.waitForFunction(()=>Boolean(window.__savedTemplate));
const savedGroupedTemplate=await page.evaluate(()=>window.__savedTemplate);
if (savedGroupedTemplate.capacity !== 1 || savedGroupedTemplate.studentId !== "student-2") throw new Error("Lịch mẫu cùng khung giờ chưa giữ capacity mặc định 1");

await page.click('a[href="#notes"]');
await page.waitForSelector("#addNote");
if (await page.locator(".delete-note").count() !== 1) throw new Error("Thiếu thùng rác ghi chú");
await page.click("#addNote");
if (await page.locator('textarea[name="details"]').count() !== 1) throw new Error("Form ghi chú thiếu chi tiết");
await page.click("#dialogCancel");

await page.click('a[href="#reports"]');
await page.waitForFunction(()=>document.querySelector("#content")?.textContent.includes("Bé Bình"));
const teacherReport=await page.locator(".report-table").nth(1).textContent();
if (!teacherReport.includes("1 giờ") || teacherReport.includes("2 giờ")) throw new Error("Giờ giáo viên bị nhân theo số học sinh");
if (teacherReport.includes("lớp")) throw new Error("Báo cáo tháng của giáo viên vẫn hiển thị số lớp thay vì chỉ hiển thị giờ");
const teacherHeaders=(await page.locator(".report-table").nth(1).locator("thead th").allTextContents()).map(text=>text.replace("#","").trim());
if (teacherHeaders[2]!=="Đã xếp" || teacherHeaders[3]!=="Tổng giờ" || teacherHeaders[4]!=="Buổi dạy bù" || await page.locator(".teacher-total-hours").count() !== 2) throw new Error("Báo cáo giáo viên thiếu cột Đã xếp, Tổng giờ hoặc Buổi dạy bù");
if ((await page.locator(".teacher-total-hours").first().textContent()).trim() !== "5 giờ") throw new Error("Tổng giờ giáo viên chưa được tính từ lịch mẫu theo số ngày trong tháng");
if (await page.locator(".column-help").count() !== 11) throw new Error("Các cột số liệu trong báo cáo chưa có đủ dấu # giải thích");
if (await page.locator(".column-help").first().evaluate(button=>getComputedStyle(button,"::before").content) !== '"!"') throw new Error("Ký hiệu giải thích cột chưa hiển thị dấu !");
const plannedHelp=page.locator('th:has-text("Đã xếp") .column-help').last();
await plannedHelp.click();
if (await plannedHelp.getAttribute("aria-expanded") !== "true" || !(await plannedHelp.getAttribute("data-help")).includes("dạy thay")) throw new Error("Dấu # của cột Đã xếp chưa mở đúng giải thích công thức");
await plannedHelp.press("Tab");
const reportSectionOrder=await page.locator(".report-sections>section").evaluateAll(items=>items.map(item=>({title:item.querySelector("h2")?.textContent,order:Number(getComputedStyle(item).order)})).sort((a,b)=>a.order-b.order).map(item=>item.title));
if (reportSectionOrder[0]!=="Giáo viên") throw new Error("Báo cáo tháng chưa đưa phần Giáo viên lên trên Học sinh");
if (await page.locator("#manageReportHolidays").count() !== 1) throw new Error("Báo cáo tháng thiếu nút Nghỉ lễ");
await page.click("#manageReportHolidays");
await page.waitForSelector("#studentProfileDialog[open] #addReportHoliday");
if (!(await page.locator("#studentProfileBody").textContent()).includes("Các ngày lễ trong tháng")) throw new Error("Nút Nghỉ lễ chưa mở popup quản lý đồng bộ");
await page.click("#studentProfileClose");
if (await page.locator(".manage-teacher-leave").count() !== 2) throw new Error("Báo cáo tháng thiếu nút quản lý nghỉ phép cạnh giáo viên");
if (await page.locator(".report-teacher-leave-action .badge").count() !== 2 || (await page.locator(".report-teacher-leave-action .badge").first().textContent()).trim() !== "0 ngày") throw new Error("Báo cáo tháng thiếu số ngày nghỉ cạnh nút nghỉ phép");
await page.locator(".manage-teacher-leave").first().click();
await page.waitForSelector("#studentProfileDialog[open] #addMonthlyTeacherLeave");
if (!(await page.locator("#studentProfileBody").textContent()).includes("Các ngày nghỉ trong tháng")) throw new Error("Popup nghỉ phép chưa hiển thị danh sách quản lý theo tháng");
await page.click("#addMonthlyTeacherLeave");
await page.waitForSelector('#formDialog[open] input[name="fullDay"]:checked');
if (await page.locator('.teacher-leave-time:not([hidden])').count()) throw new Error("Thêm nghỉ phép chưa mặc định chọn nghỉ cả ngày");
await page.click("#dialogCancel");
await page.click("#studentProfileClose");

await page.click('a[href="#month"]');
await page.waitForSelector(".month-birthday-card");
const monthText=await page.locator("#content").textContent();
if (!monthText.includes("Lịch sinh nhật") || !monthText.includes("2 người") || !monthText.includes("Bé An") || !monthText.includes("Bé Bình")) throw new Error("Trang Tháng này tổng hợp sinh nhật chưa đúng");
if (await page.locator("#addHolidayMonth").count() !== 1 || !monthText.includes("Ngày lễ trong tháng")) throw new Error("Trang Tháng này thiếu quản lý thêm/sửa/xóa nhiều ngày lễ");
if (process.env.HAPPYCHILD_MONTH_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_MONTH_SCREENSHOT,fullPage:true});

await page.setViewportSize({ width: 390, height: 844 });
await page.evaluate(()=>document.querySelector("#briefingDialog").showModal());
await page.click("#briefingDone");
await page.evaluate(()=>{location.hash="calendar"});
await page.waitForSelector(".student-week-schedule");
const mobileCalendarLayout=await page.locator(".student-week-schedule").evaluate(root=>{const row=root.querySelector(".weekly-student-row"),pattern=root.querySelector(".student-schedule-pattern"),cluster=root.querySelector(".student-schedule-cluster");return {overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,row:row?.getBoundingClientRect().width||0,pattern:pattern?.getBoundingClientRect().width||0,cluster:cluster?.getBoundingClientRect().width||0}});
if (mobileCalendarLayout.overflow>1 || mobileCalendarLayout.row>mobileCalendarLayout.cluster+1 || mobileCalendarLayout.pattern>mobileCalendarLayout.row+1) throw new Error("Danh sách lịch học sinh trên mobile bị tràn ngang");
if (await page.locator(".weekly-day-session").count() < 2) throw new Error("Các ngày học không hiển thị dạng nút gọn trên mobile");
const mobileFixedDays=await page.locator('.weekly-student-row[data-student-id="student-1"] .student-pattern-days').evaluate(grid=>({columns:getComputedStyle(grid).gridTemplateColumns.split(" ").length,days:[...grid.children].map(cell=>cell.dataset.day),scrollable:grid.scrollWidth>grid.clientWidth}));
if (mobileFixedDays.columns!==7 || JSON.stringify(mobileFixedDays.days)!==JSON.stringify(["0","1","2","3","4","5","6"]) || !mobileFixedDays.scrollable) throw new Error("Lưới ngày cố định trên mobile chưa cuộn ngang đúng bên trong lịch");
await page.evaluate(()=>scrollTo(0,0));
if (process.env.HAPPYCHILD_CALENDAR_MOBILE_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_CALENDAR_MOBILE_SCREENSHOT,fullPage:true});
await page.evaluate(()=>{location.hash="forms"});
await page.waitForSelector(".form-teacher-group");
if (await page.locator(".form-teacher-group[open]").count() !== 1) throw new Error("Nhóm Link Form mobile chưa thu gọn");
const mobileResultLayout=await page.locator('.form-row[data-id="form-1"]').evaluate(row=>{const cell=row.querySelector(".form-result-cell");return {row:row.getBoundingClientRect().width,cell:cell.getBoundingClientRect().width,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}});
if (mobileResultLayout.overflow>1 || mobileResultLayout.cell<mobileResultLayout.row*.9) throw new Error("Ô kết quả mobile chưa chiếm toàn chiều rộng hoặc bị tràn ngang");
await page.evaluate(()=>{location.hash="templates"});
await page.waitForSelector(".template-student-row",{state:"attached"});
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Lịch mẫu mobile chưa mặc định thu gọn hoàn toàn");
await page.fill("#templateSearch","Mang sách");
if (await page.locator(".template-day-group[open]").count() !== 1 || await page.locator(".template-slot-group[open]").count() !== 1) throw new Error("Tìm lịch mẫu mobile không tự mở đúng ngày và giờ");
const mobileTemplateLayout=await page.locator('.template-student-row[data-template-id="template-2"]').evaluate(row=>({row:row.getBoundingClientRect().width,parent:row.parentElement.getBoundingClientRect().width,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}));
if (mobileTemplateLayout.overflow>1 || mobileTemplateLayout.row>mobileTemplateLayout.parent+1) throw new Error("Lịch mẫu mobile bị tràn ngang");
if (process.env.HAPPYCHILD_TEMPLATES_MOBILE_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_TEMPLATES_MOBILE_SCREENSHOT,fullPage:true});

{
  await page.setViewportSize({width:1440,height:900});
  if(await page.locator("html").getAttribute("data-theme")!=="dark")await page.click("#themeToggleBtn");
  const audit={};
  for(const view of ["dashboard","month","calendar","students","teachers","forms","templates","makeup","reports","notes","history","settings"]){
    await page.evaluate(value=>{location.hash=value},view);await page.waitForTimeout(60);
    await page.evaluate(()=>document.querySelectorAll("#content details").forEach(item=>item.open=true));
    if(view==="forms"&&process.env.HAPPYCHILD_DARK_FORMS_SCREENSHOT)await page.screenshot({path:process.env.HAPPYCHILD_DARK_FORMS_SCREENSHOT,fullPage:true});
    audit[view]=await page.evaluate(()=>[...document.querySelectorAll("#content *")].filter(element=>{const rect=element.getBoundingClientRect(),style=getComputedStyle(element),match=style.backgroundColor.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return rect.width*rect.height>220&&style.display!=="none"&&style.visibility!=="hidden"&&match&&Number(match[1])>220&&Number(match[2])>220&&Number(match[3])>220}).slice(0,80).map(element=>({tag:element.tagName.toLowerCase(),id:element.id,cls:element.className,text:(element.textContent||"").trim().slice(0,45),bg:getComputedStyle(element).backgroundColor})));
  }
  await page.evaluate(()=>document.querySelector("#briefingDialog").showModal());
  audit.briefing=await page.evaluate(()=>[...document.querySelectorAll("#briefingDialog *")].filter(element=>{const rect=element.getBoundingClientRect(),match=getComputedStyle(element).backgroundColor.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return rect.width*rect.height>220&&match&&Number(match[1])>220&&Number(match[2])>220&&Number(match[3])>220}).map(element=>({tag:element.tagName.toLowerCase(),id:element.id,cls:element.className,text:(element.textContent||"").trim().slice(0,45),bg:getComputedStyle(element).backgroundColor})));
  await page.click("#briefingDone");const lightSurfaces=Object.entries(audit).filter(([,items])=>items.length);if(lightSurfaces.length)throw new Error("Chế độ tối còn bề mặt sáng: "+JSON.stringify(Object.fromEntries(lightSurfaces)));if(process.env.HAPPYCHILD_DARK_AUDIT)console.log("DARK_AUDIT "+JSON.stringify(audit));await page.click("#themeToggleBtn");
}

const racePage=await browser.newPage({viewport:{width:1200,height:800}});
const raceErrors=[];
racePage.on("pageerror",error=>raceErrors.push(error.message));
const raceStoreMock=storeMock
  .replace(/const week=\{[^\n]+\};/, 'const week={id:"week-2026-08-10",weekNumber:1,label:"Tuần 1 (10/08/2026–16/08/2026)",startDate:ts("2026-08-10T12:00:00"),endDate:ts("2026-08-16T12:00:00"),status:"active"};\nconst week2={id:"week-2026-08-17",weekNumber:2,label:"Tuần 2 (17/08/2026–23/08/2026)",startDate:ts("2026-08-17T12:00:00"),endDate:ts("2026-08-23T12:00:00"),status:"active"};')
  .replace(/const session=\{[^\n]+\};/, match=>`${match}\nconst sessionB={...session,id:"session-b",date:ts("2026-08-17T12:00:00"),dateKey:"2026-08-17",dayOfWeek:0,status:"scheduled",note:"Tuần B"};`)
  .replace(/export const subscribe=\(name,cb\)=>\{[^\n]+\};/, 'export const subscribe=(name,cb)=>{setTimeout(()=>cb(name==="students"?[student,student2]:name==="teachers"?[teacher,teacher2]:name==="scheduleTemplates"?[template]:name==="weeks"?[week,week2]:[]),0);return()=>{}};')
  .replace(/export const subscribeSessions=\(id,cb\)=>\{[^\n]+\};/, 'let firstWeekCallback; export const subscribeSessions=(id,cb)=>{if(id===week.id){firstWeekCallback=cb;setTimeout(()=>cb([session]),0)}else{setTimeout(()=>firstWeekCallback?.([{...session,id:"stale-week-a"}]),250);setTimeout(()=>cb([sessionB]),700)}return()=>{}};')
  .replace('export const deleteWeek=async()=>{};', 'export const deleteWeek=async(id,sessions)=>{window.__deleteWeekCalls=(window.__deleteWeekCalls||0)+1;window.__deletedWeek={id,sessionIds:sessions.map(item=>item.id)}};');
await racePage.route("**/happychild/js/auth.js*",route=>route.fulfill({contentType:"text/javascript",body:authMock}));
await racePage.route("**/happychild/js/store.js*",route=>route.fulfill({contentType:"text/javascript",body:raceStoreMock}));
await racePage.goto("http://127.0.0.1:8080/happychild/#calendar",{waitUntil:"domcontentloaded"});
await racePage.waitForSelector("#briefingDialog[open]");
await racePage.click("#briefingDone");
await racePage.waitForSelector("#deleteWeekBtn:not([disabled])");
await racePage.selectOption("#weekSelect","week-2026-08-17");
if ((await racePage.inputValue("#weekSelect"))!=="week-2026-08-17") throw new Error("Chuyển tuần chậm không giữ đúng weekId mới");
if (!(await racePage.locator("#deleteWeekBtn").isDisabled()) || !(await racePage.locator("#addSessionTop").isDisabled()) || !(await racePage.locator(".week-sessions-loading").count())) throw new Error("Tuần mới chưa khóa thao tác khi sessions đang tải");
await racePage.locator("#deleteWeekBtn").dispatchEvent("click");
if (await racePage.evaluate(()=>window.__deleteWeekCalls||0)) throw new Error("Guard xóa tuần cho phép chạy trước snapshot");
await racePage.waitForTimeout(350);
if (!(await racePage.locator("#deleteWeekBtn").isDisabled()) || !(await racePage.locator(".week-sessions-loading").count())) throw new Error("Callback tuần cũ đã mở khóa nhầm tuần mới");
await racePage.waitForSelector("#deleteWeekBtn:not([disabled])",{timeout:3000});
if (!(await racePage.locator('[data-session="session-b"]').count()) || await racePage.locator('[data-session="stale-week-a"]').count()) throw new Error("Snapshot tuần mới bị trộn với callback tuần cũ");
if (await racePage.locator("#finalizeWeekBtn").count() !== 1 || !(await racePage.locator(".week-summary-card").textContent()).includes("cần chốt số liệu")) throw new Error("Tuần đã qua chưa hiển thị nút chốt và bản xem trước thống kê");
if (process.env.HAPPYCHILD_WEEK_SUMMARY_SCREENSHOT) await racePage.screenshot({path:process.env.HAPPYCHILD_WEEK_SUMMARY_SCREENSHOT,fullPage:true});
racePage.once("dialog",dialog=>dialog.accept());
await racePage.click("#finalizeWeekBtn");
await racePage.waitForFunction(()=>Boolean(window.__finalizedWeek));
const finalizedWeek=await racePage.evaluate(()=>window.__finalizedWeek);
if (finalizedWeek.id!=="week-2026-08-17" || finalizedWeek.summary.counts.total!==1 || finalizedWeek.summary.counts.learned!==1 || finalizedWeek.summary.counts.scheduled!==0 || !finalizedWeek.summary.sourceFingerprint) throw new Error("Payload chốt tuần chưa tự tính buổi đã qua giờ là đã học");
racePage.once("dialog",dialog=>dialog.accept());
await racePage.click("#deleteWeekBtn");
await racePage.waitForFunction(()=>window.__deleteWeekCalls===1);
const deletedWeek=await racePage.evaluate(()=>window.__deletedWeek);
if (deletedWeek.id!=="week-2026-08-17" || JSON.stringify(deletedWeek.sessionIds)!==JSON.stringify(["session-b"])) throw new Error("Xóa tuần dùng sai weekId hoặc danh sách sessions");
if (raceErrors.length) throw new Error(`Race page errors: ${raceErrors.join(" | ")}`);
await racePage.close();

const seedPage=await browser.newPage({viewport:{width:1100,height:760}});
const seedErrors=[];
seedPage.on("pageerror",error=>seedErrors.push(error.message));
const ownerAuthMock=authMock.replace('uid:"test-user"','uid:"EplnbxgWTaal9N5QgflBWaT1LWG3"');
const delayedEmptyStoreMock=storeMock
  .replace(/export const subscribe=\(name,cb\)=>\{[^\n]+\};/, 'export const subscribe=(name,cb)=>{const delay=name==="students"?700:name==="teachers"?900:0;setTimeout(()=>cb([]),delay);return()=>{}};')
  .replace(/export const subscribeStudentForms=cb=>\{[^\n]+\};/, 'export const subscribeStudentForms=cb=>{setTimeout(()=>cb([]),1100);return()=>{}};');
await seedPage.route("**/happychild/js/auth.js*",route=>route.fulfill({contentType:"text/javascript",body:ownerAuthMock}));
await seedPage.route("**/happychild/js/store.js*",route=>route.fulfill({contentType:"text/javascript",body:delayedEmptyStoreMock}));
await seedPage.goto("http://127.0.0.1:8080/happychild/#settings",{waitUntil:"domcontentloaded"});
await seedPage.waitForSelector("#appView:not(.hidden)");
if (await seedPage.locator("#seedBtn").count()) throw new Error("Nút seed xuất hiện trước khi subscriptions tải xong");
await seedPage.waitForSelector("#seedBtn",{timeout:5000});
if (seedErrors.length) throw new Error(`Seed page errors: ${seedErrors.join(" | ")}`);
await seedPage.close();

const bootTimeoutPage=await browser.newPage({viewport:{width:1000,height:700}});
await bootTimeoutPage.addInitScript(()=>{const nativeSetTimeout=window.setTimeout.bind(window);window.setTimeout=(callback,delay,...args)=>nativeSetTimeout(callback,delay===15000?50:delay,...args)});
await bootTimeoutPage.route("**/happychild/js/auth.js*",route=>route.fulfill({contentType:"text/javascript",body:'export const login=async()=>{};export const logout=async()=>{};export const authErrorMessage=()=>"";export const watchAuth=()=>()=>{};'}));
await bootTimeoutPage.route("**/happychild/js/store.js*",route=>route.fulfill({contentType:"text/javascript",body:storeMock}));
await bootTimeoutPage.goto("http://127.0.0.1:8080/happychild/",{waitUntil:"domcontentloaded"});
await bootTimeoutPage.waitForFunction(()=>document.querySelector("#loading")?.textContent.includes("Chưa tải được HappyChild"));
if (!(await bootTimeoutPage.locator("#loading button").count())) throw new Error("Khởi động lỗi chưa hiện nút tải lại");
await bootTimeoutPage.close();

if (errors.length) throw new Error(`Page errors: ${errors.join(" | ")}`);
console.log(JSON.stringify({status:"ok",checks:132,saveSessionCalls:await page.evaluate(()=>window.__saveSessionCalls||0)}));
await browser.close();
