import { chromium } from "file:///C:/Users/kurob/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs";

const browser = await chromium.launch({
  headless: true,
  executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe",
});
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.addInitScript(() => {
  const NativeDate = Date;
  const fixedNow = new NativeDate("2026-08-14T12:00:00+07:00").getTime();
  class FixedDate extends NativeDate {
    constructor(...args) { super(...(args.length ? args : [fixedNow])); }
    static now() { return fixedNow; }
  }
  window.Date = FixedDate;
});
const errors = [];
page.on("pageerror", error => errors.push(error.message));

const authMock = `
export const login=async()=>{};
export const logout=async()=>{};
export const authErrorMessage=e=>e?.message||"error";
export const watchAuth=callback=>{setTimeout(()=>callback({uid:"test-user",email:"test@example.com"},{displayName:"Người kiểm thử",role:"authenticated",active:true}),0);return()=>{}};
`;
const storeMock = `
const ts=value=>({seconds:Math.floor(new Date(value).getTime()/1000),toDate:()=>new Date(value)});
const student={id:"student-1",fullName:"Bé An",shortName:"An",color:"#e879a9",active:true,makeupBalance:1,parentPhone:"",birthday:"2020-08-13"};
const student2={id:"student-2",fullName:"Bé Bình",shortName:"Bình",color:"#4f86e8",active:true,makeupBalance:1,parentPhone:"",birthday:"2020-08-14"};
const teacher={id:"teacher-1",fullName:"Cô Ngân",shortName:"Cô Ngân",color:"#7c5ce7",active:true,phone:""};
const teacher2={id:"teacher-2",fullName:"Cô Mai",shortName:"Cô Mai",color:"#20a779",active:true,phone:""};
const week={id:"week-2026-08-10",weekNumber:1,label:"Tuần 1 (10/08/2026–16/08/2026)",startDate:ts("2026-08-10T12:00:00"),endDate:ts("2026-08-16T12:00:00"),status:"active"};
const template={id:"template-1",studentId:student.id,teacherId:teacher.id,dayOfWeek:0,startTime:"13:00",endTime:"14:00",capacity:1,active:true,note:""};
const templatePeer={...template,id:"template-2",studentId:student2.id,note:"Mang sách"};
const templateTeacher2={...template,id:"template-3",studentId:student2.id,teacherId:teacher2.id,dayOfWeek:1,startTime:"15:00",endTime:"16:00"};
const templateSameTimeTeacher2={...template,id:"template-4",studentId:student2.id,teacherId:teacher2.id,note:"Cùng giờ khác cô"};
const session={id:"session-1",studentId:student.id,teacherId:teacher.id,date:ts("2026-08-10T12:00:00"),dateKey:"2026-08-10",dayOfWeek:0,startTime:"13:00",endTime:"14:00",capacity:1,type:"regular",status:"absent",note:"Xin nghỉ"};
const groupedRegularPeers=Array.from({length:5},(_,index)=>({...session,id:"session-regular-"+(index+2),studentId:"slot-student-"+(index+2),status:"scheduled",note:""}));
const sameTimeTeacher2={...session,id:"same-time-teacher-2",studentId:student2.id,teacherId:teacher2.id,status:"scheduled",note:""};
const filledSlotRegulars=Array.from({length:6},(_,index)=>({...session,id:"filled-regular-"+(index+1),studentId:"filled-student-"+(index+1),date:ts("2026-08-11T12:00:00"),dateKey:"2026-08-11",dayOfWeek:1,status:index===0?"absent":"scheduled",note:index===0?"Xin nghỉ":""}));
const filledSlotMakeup={...session,id:"filled-makeup",studentId:"makeup-student",date:ts("2026-08-11T12:00:00"),dateKey:"2026-08-11",dayOfWeek:1,capacity:20,type:"makeup",status:"makeup_scheduled",note:"Học bù vào chỗ trống"};
const attack='"><img id="stored-xss-marker" src=x onerror="window.__storedXss=1">';
const maliciousTemplate={id:'template-xss" onclick="window.__storedXss=2',studentId:student.id,teacherId:teacher.id,dayOfWeek:6,startTime:attack,endTime:attack,capacity:1,active:true,note:""};
const maliciousSession={id:'session-xss" onclick="window.__storedXss=3',studentId:student2.id,teacherId:teacher.id,date:ts("2026-08-16T12:00:00"),dateKey:"2026-08-16",dayOfWeek:6,startTime:attack,endTime:attack,capacity:1,type:attack,status:'scheduled" onmouseover="window.__storedXss=4',note:""};
const reportSession={...session,id:"report-1",status:"attended",capacity:7};
const reportSession2={...reportSession,id:"report-2",studentId:student2.id};
const note={id:"note-1",dateKey:"2026-08-13",title:"Mang sách",details:"Nhắc phụ huynh mang sách."};
const formCreated=ts("2026-04-01T12:00:00");
const studentForm={id:"form-1",studentId:student.id,teacherId:teacher.id,formLink:"https://docs.google.com/forms/d/e/example/viewform",formTitle:"Bé An 8/6 - 8/9",courseStart:"8/6",courseEnd:"8/9",coursePeriod:"8/6-8/9",resultRecordedDate:"2026-08-13",teacherHours:1.5,note:"Đã ghi nhận",displayOrder:1,sourceRow:3,createdAt:formCreated};
const incompleteStudentForm={id:"form-2",studentId:student2.id,teacherId:teacher2.id,formLink:"https://docs.google.com/forms/d/e/missing/viewform",formTitle:"",courseStart:"",courseEnd:"",coursePeriod:"",resultRecordedDate:"2026-08-14",teacherHours:0,note:"Thiếu tiêu đề",displayOrder:2,sourceRow:4,createdAt:formCreated};
const noLinkStudentForm={id:"form-3",studentId:student2.id,teacherId:teacher.id,formLink:"",formTitle:"Bé Bình 1/1 - 1/2",courseStart:"1/1",courseEnd:"1/2",coursePeriod:"1/1-1/2",resultRecordedDate:"",teacherHours:1,note:"Thiếu link",displayOrder:3,sourceRow:5,createdAt:formCreated};
const manualStudentForm={id:"form-4",studentId:student.id,teacherId:teacher2.id,formLink:"https://docs.google.com/forms/d/e/manual/viewform",formTitle:"Bé An khóa mùa hè",courseStart:"10/6",courseEnd:"10/9",coursePeriod:"10/6-10/9",resultRecordedDate:"",teacherHours:1,note:"Khoảng ngày nhập tay",displayOrder:4,sourceRow:6,createdAt:formCreated};
const invalidYearStudentForm={id:"form-5",studentId:student2.id,teacherId:teacher.id,formLink:"https://docs.google.com/forms/d/e/tiger/viewform",formTitle:"Tiger 16/6 - 16/9/206",courseStart:"16/6",courseEnd:"16/9",coursePeriod:"16/6-16/9",resultRecordedDate:"",teacherHours:1,note:"Năm tiêu đề cần xác nhận",displayOrder:5,sourceRow:7,createdAt:formCreated};
const lateRecordedStudentForm={id:"form-6",studentId:student.id,teacherId:teacher.id,formLink:"https://docs.google.com/forms/d/e/late/viewform",formTitle:"Bé An 1/1/2026 - 1/2/2026",courseStart:"1/1/2026",courseEnd:"1/2/2026",coursePeriod:"1/1/2026-1/2/2026",resultRecordedDate:"2026-02-02",teacherHours:1,note:"Ghi muộn một ngày",displayOrder:6,sourceRow:8,createdAt:formCreated};
const dueTodayStudentForm={id:"form-7",studentId:student2.id,teacherId:teacher2.id,formLink:"https://docs.google.com/forms/d/e/today/viewform",formTitle:"Bé Bình 14/5/2026 - 14/8/2026",courseStart:"14/5/2026",courseEnd:"14/8/2026",coursePeriod:"14/5/2026-14/8/2026",resultRecordedDate:"",teacherHours:1,note:"Đến hạn hôm nay",displayOrder:7,sourceRow:9,createdAt:formCreated};
const beforeStartStudentForm={id:"form-8",studentId:student.id,teacherId:teacher.id,formLink:"https://docs.google.com/forms/d/e/before-start/viewform",formTitle:"Bé An 1/5/2026 - 1/8/2026",courseStart:"1/5/2026",courseEnd:"1/8/2026",coursePeriod:"1/5/2026-1/8/2026",resultRecordedDate:"2026-04-30",teacherHours:1,note:"Ngày ghi nhận sai",displayOrder:8,sourceRow:10,createdAt:formCreated};
export const subscribe=(name,cb)=>{setTimeout(()=>cb(name==="students"?[student,student2]:name==="teachers"?[teacher,teacher2]:name==="scheduleTemplates"?[template,templatePeer,templateTeacher2,templateSameTimeTeacher2,maliciousTemplate]:name==="weeks"?[week]:[]),0);return()=>{}};
export const subscribeSessions=(id,cb)=>{setTimeout(()=>cb([session,...groupedRegularPeers,sameTimeTeacher2,...filledSlotRegulars,filledSlotMakeup,maliciousSession]),0);return()=>{}};
export const subscribeNotes=cb=>{setTimeout(()=>cb([note]),0);return()=>{}};
export const subscribeStudentForms=cb=>{setTimeout(()=>cb([studentForm,incompleteStudentForm,noLinkStudentForm,manualStudentForm,invalidYearStudentForm,lateRecordedStudentForm,dueTodayStudentForm,beforeStartStudentForm]),0);return()=>{}};
export const subscribeRecentAudit=cb=>{setTimeout(()=>cb([]),0);return()=>{}};
export const subscribeTransactions=cb=>{setTimeout(()=>cb([]),0);return()=>{}};
export const saveStudent=async()=>{};
export const saveTeacher=async()=>{};
export const saveTemplate=async data=>{window.__savedTemplate=data};
export const saveNote=async()=>{};
export const saveStudentForm=async data=>{window.__savedStudentForm=data};
export const saveSession=async()=>{window.__saveSessionCalls=(window.__saveSessionCalls||0)+1};
export const deleteStudent=async()=>{};
export const deleteTeacher=async()=>{};
export const deleteSession=async()=>{};
export const deleteWeek=async()=>{};
export const deleteStudentForm=async()=>{};
export const deleteMakeupTransaction=async()=>{};
export const purgeAllData=async()=>0;
export const removeRecord=async()=>{};
export const createWeek=async()=>week.id;
export const updateSessionStatus=async()=>{};
export const getTeacherAvailability=id=>id==="teacher-2"?({available:false,reason:"Giáo viên đã có lịch khác trùng giờ.",occupied:0,capacity:1}):({available:true,reason:"",occupied:5,capacity:6});
export const addMakeupSession=async()=>{};
export const seedData=async()=>{};
export const loadMonthReport=async()=>[reportSession,reportSession2];
`;

await page.route("**/happychild/js/auth.js*", route => route.fulfill({ contentType: "text/javascript", body: authMock }));
await page.route("**/happychild/js/store.js*", route => route.fulfill({ contentType: "text/javascript", body: storeMock }));
await page.goto("http://127.0.0.1:8080/happychild/", { waitUntil: "networkidle" });
await page.waitForSelector("#appView:not(.hidden)");
if (await page.locator('.brand-logo.small img[src*="happychild-logo.jpg"]').count() !== 1) throw new Error("Logo Happy Child chưa xuất hiện ở thanh bên");
if (!(await page.locator('.brand-logo.small img').evaluate(image=>image.complete&&image.naturalWidth>0))) throw new Error("Tệp logo Happy Child không tải được");
await page.waitForSelector("#briefingDialog[open]");
if (await page.locator("#briefingBody .brief-day").count() !== 2) throw new Error("Popup không đủ Hôm nay/Ngày mai");
await page.click("#briefingDone");

await page.click('a[href="#calendar"]');
await page.waitForSelector(".empty-slot.add-session");
if (await page.locator("details.time-slot[open]").count()) throw new Error("Khung giờ chưa mặc định thu gọn");
const sessionHardening=await page.evaluate(()=>{const card=[...document.querySelectorAll("[data-session]")].find(element=>element.dataset.session.startsWith("session-xss")),timeText=document.querySelector('[data-day-date="2026-08-16"] .slot-summary')?.textContent||"";return {marker:Boolean(document.querySelector("#stored-xss-marker")),executed:Boolean(window.__storedXss),found:Boolean(card),safeStatus:card?.classList.contains("scheduled"),inlineHandler:card?.hasAttribute("onclick")||card?.hasAttribute("onmouseover"),text:card?.textContent||"",timeText}});
if (sessionHardening.marker || sessionHardening.executed || !sessionHardening.found || !sessionHardening.safeStatus || sessionHardening.inlineHandler) throw new Error("Stored-XSS từ dữ liệu buổi học chưa được chặn");
if (sessionHardening.text.includes("<img") || sessionHardening.timeText.includes("<img") || !sessionHardening.timeText.includes("—")) throw new Error("Giờ học không hợp lệ chưa được thay bằng giá trị an toàn");
const monday=page.locator('[data-day-date="2026-08-10"]');
if (await monday.locator("details.time-slot").count() !== 1 || await monday.locator(".teacher-slot").count() !== 2) throw new Error("Khung giờ trùng nhau chưa được gom một tầng rồi chia theo giáo viên");
const mondaySummary=await monday.locator(".slot-summary").textContent();
if (!mondaySummary.includes("Cô Ngân") || !mondaySummary.includes("Cô Mai")) throw new Error("Tóm tắt khung giờ thiếu giáo viên thực tế");
const openGroupedSlot=monday.locator('[data-teacher-id="teacher-1"]');
if (!(await openGroupedSlot.locator(".teacher-slot-head small").textContent()).startsWith("5/6") || (await openGroupedSlot.locator(".slot-add").getAttribute("data-capacity")) !== "6") throw new Error("Sáu lịch thường capacity 1 chưa được gộp thành sức chứa 6");
if (await openGroupedSlot.locator(".slot-add").isDisabled()) throw new Error("Một học sinh xin nghỉ chưa giải phóng đúng một chỗ học bù");
const filledGroupedSlot=page.locator('[data-day-date="2026-08-11"] [data-teacher-id="teacher-1"]');
if (!(await filledGroupedSlot.locator(".teacher-slot-head small").textContent()).startsWith("6/6") || (await filledGroupedSlot.locator(".slot-add").getAttribute("data-capacity")) !== "6") throw new Error("Buổi học bù đã làm tăng sai sức chứa khung giờ");
if (!(await filledGroupedSlot.locator(".teacher-slot-head small").textContent()).includes("1 học bù") || !(await filledGroupedSlot.locator(".slot-add").isDisabled())) throw new Error("Chỗ nghỉ chưa được lấp đầy đúng bởi một buổi học bù");
if (await page.locator(".slot-add:not(:disabled)").count() !== 1) throw new Error("Số khung giờ còn một chỗ trống không đúng");
if (await page.locator("#deleteWeekBtn").count() !== 1) throw new Error("Thiếu nút xóa tuần");
const slotTeacherColor=await openGroupedSlot.evaluate(element=>getComputedStyle(element).getPropertyValue("--teacher").trim().toLowerCase());
if (slotTeacherColor !== "#7c5ce7") throw new Error("Khung giờ chưa dùng màu của giáo viên");
const teacher2ChildColor=await monday.locator('[data-session="same-time-teacher-2"]').evaluate(element=>getComputedStyle(element).getPropertyValue("--student").trim().toLowerCase());
if (teacher2ChildColor !== "#20a779") throw new Error("Màu học sinh trong lịch chưa lấy theo giáo viên của chính buổi học");
if (process.env.HAPPYCHILD_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_SCREENSHOT,fullPage:true});
await page.click(".slot-summary");
await page.click('[data-session="session-1"]');
await page.waitForSelector("#sessionDrawer:not(.hidden)");
await page.click(".makeup-candidate");
await page.waitForSelector("#formDialog[open]");
if (await page.locator('select[name="teacherId"] option:not(:disabled)').count() !== 1) throw new Error("Danh sách giáo viên trống không đúng");
if (await page.locator('select[name="teacherId"] option:disabled').count() !== 1) throw new Error("Không hiển thị giáo viên đang bận");
if (!(await page.locator("#dialogBody").textContent()).includes("5/6 chỗ đang dùng")) throw new Error("Form học bù chưa hiển thị đúng sức chứa gộp");
await page.click("#dialogCancel");
await openGroupedSlot.locator(".slot-add").click();
await page.waitForSelector("#formDialog[open]");
if ((await page.inputValue('input[name="capacity"]')) !== "1") throw new Error("Thêm lịch thường vào khung gộp đã lấy sai tổng capacity thay vì mặc định 1");
await page.click("#dialogCancel");
await page.click(".empty-slot.add-session");
await page.waitForSelector("#formDialog[open]");
if (await page.locator('select[name="studentId"]').count() !== 1) throw new Error("Thiếu chọn học sinh trong form buổi học");
if (await page.locator('select[name="teacherId"]').count() !== 1) throw new Error("Thiếu chọn giáo viên trong form buổi học");
await page.click("#dialogCancel");
if ((await page.evaluate(()=>window.__saveSessionCalls||0)) !== 0) throw new Error("Nút Hủy đã gọi lưu dữ liệu");

await page.click(".empty-slot.add-session");
await page.fill('input[name="startTime"]', "13:00");
await page.fill('input[name="endTime"]', "14:00");
await page.click("#dialogSubmit");
await page.waitForFunction(()=>window.__saveSessionCalls===1);

await page.click('a[href="#teachers"]');
await page.waitForSelector("#addTeacher");
if (await page.locator(".delete-teacher").count() !== 2) throw new Error("Thiếu thùng rác giáo viên");
if (await page.locator(".teacher-roster-group").count() !== 2) throw new Error("Trang giáo viên chưa nhóm danh sách học sinh theo từng cô");
if (await page.locator(".teacher-roster-group[open]").count() !== 1) throw new Error("Danh sách giáo viên chưa mặc định chỉ mở một nhóm");
if ((await page.locator('[data-teacher-id="teacher-1"] .teacher-student-count').textContent()).trim() !== "1 học sinh") throw new Error("Số học sinh cô phụ trách không đúng theo Link Form đầu tiên");
if ((await page.locator('[data-teacher-id="teacher-1"] [data-roster-student-id="student-1"] strong').textContent()).trim() !== "Bé An") throw new Error("Thiếu học sinh trong nhóm giáo viên phụ trách");
if ((await page.locator('[data-teacher-id="teacher-1"] .roster-number').textContent()).trim() !== "1") throw new Error("STT cục bộ trong nhóm giáo viên không bắt đầu từ 1");
await page.fill("#teacherRosterSearch", "Bé Bình");
if (await page.locator(".teacher-roster-group:visible").count() !== 1 || (await page.locator("#teacherRosterResultCount").textContent()).trim() !== "1 giáo viên") throw new Error("Tìm học sinh trên trang Giáo viên không lọc đúng cô phụ trách");
await page.fill("#teacherRosterSearch", "");
await page.setViewportSize({width:375,height:800});
const teacherMobileLayout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,columns:getComputedStyle(document.querySelector(".teacher-student-grid")).gridTemplateColumns}));
if (teacherMobileLayout.overflow>1 || teacherMobileLayout.columns.split(" ").length!==1) throw new Error("Danh sách giáo viên bị tràn hoặc chưa về một cột trên mobile");
await page.setViewportSize({width:1440,height:900});
await page.click("#addTeacher");
await page.waitForSelector('input[name="fullName"]');
if (await page.locator('input[name="birthday"]').count() !== 1) throw new Error("Form giáo viên thiếu ngày sinh");
await page.click("#dialogClose");

await page.click('a[href="#students"]');
await page.waitForSelector("#addStudent");
if (await page.locator(".delete-student").count() !== 2) throw new Error("Thiếu thùng rác học sinh");
const initialStudentNumbers=await page.locator(".student-table tbody tr[data-student-id] .student-index").allTextContents();
if (initialStudentNumbers.join(",") !== "1,2") throw new Error("Học sinh chưa được đánh STT global liên tục");
if ((await page.locator('[data-student-id="student-1"] [data-label="Giáo viên dạy"]').textContent()).trim() !== "Cô Ngân") throw new Error("Trang Học sinh chưa hiển thị đúng giáo viên từ Link Form");
await page.selectOption("#studentTeacherFilter", "teacher-2");
if (await page.locator(".student-table tbody tr[data-student-id]:visible").count() !== 1) throw new Error("Bộ lọc giáo viên trên trang Học sinh không đúng");
if ((await page.locator(".student-table tbody tr[data-student-id]:visible").getAttribute("data-student-index")) !== "2") throw new Error("Lọc giáo viên đã đánh lại STT thay vì giữ số global");
await page.selectOption("#studentTeacherFilter", "all");
if ((await page.locator("#studentResultCount").textContent()).trim() !== "2 học sinh") throw new Error("Bộ đếm học sinh không khôi phục sau khi bỏ lọc");
await page.setViewportSize({width:375,height:800});
const studentMobileLayout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,display:getComputedStyle(document.querySelector(".student-table tbody tr[data-student-id]")).display,label:getComputedStyle(document.querySelector('.student-table td[data-label="Giáo viên dạy"]'),"::before").content}));
if (studentMobileLayout.overflow>1 || studentMobileLayout.display!=="grid" || !studentMobileLayout.label.includes("Giáo viên dạy")) throw new Error("Danh sách học sinh bị tràn hoặc thiếu nhãn card trên mobile");
await page.setViewportSize({width:1440,height:900});
await page.click("#addStudent");
if (await page.locator('input[name="birthday"]').count() !== 1) throw new Error("Form học sinh thiếu ngày sinh");
await page.click("#dialogCancel");

await page.click('a[href="#forms"]');
await page.waitForSelector("#addStudentForm");
if (await page.locator(".form-teacher-group").count() !== 2) throw new Error("Link Form chưa nhóm theo giáo viên");
if (await page.locator(".form-teacher-group[open]").count() !== 1) throw new Error("Danh sách Link Form desktop chưa mặc định thu gọn");
if (await page.locator(".delete-student-form").count() !== 8) throw new Error("Thiếu thùng rác Link Form");
if (await page.locator(".form-page-warning").count() !== 1) throw new Error("Thiếu cảnh báo Link Form chưa có tiêu đề/thời gian");
if (!(await page.locator(".form-page-warning").textContent()).includes("3")) throw new Error("Không cảnh báo đủ mục thiếu link/năm hợp lệ");
if (await page.locator('.form-link[target="_blank"][rel~="noopener"]').count() !== 7) throw new Error("Link Form không mở an toàn ở tab mới");
if ((await page.locator('.form-row[data-id="form-2"] td[data-label="TG GV"]').textContent()).trim() !== "—") throw new Error("TG GV bằng 0 chưa hiển thị dạng trống");
const resultSummary=await page.locator(".form-result-kpi strong").allTextContents();
if (resultSummary.join(",") !== "8,2,1,3,2") throw new Error(`Tổng kết kết quả sai: ${resultSummary.join(",")}`);
if (await page.locator(".form-result-cell.result-late").count() !== 2) throw new Error("Không tô đúng hai ô kết quả trễ");
if (!(await page.locator('.form-row[data-id="form-3"] .form-result-cell').textContent()).includes("Cô trễ kết quả") || !(await page.locator('.form-row[data-id="form-3"] .form-result-cell').textContent()).includes("Chưa ghi nhận")) throw new Error("Thiếu cảnh báo đỏ cho Form quá hạn chưa ghi nhận");
if (!(await page.locator('.form-row[data-id="form-6"] .form-result-cell').textContent()).includes("trễ 1 ngày")) throw new Error("Ngày ghi nhận sau hạn chưa tính đúng số ngày trễ");
if (!(await page.locator('.form-row[data-id="form-1"] .form-result-cell').textContent()).includes("Đúng hạn")) throw new Error("Ngày ghi nhận trước hạn chưa được đánh dấu đúng hạn");
if (!(await page.locator('.form-row[data-id="form-7"] .form-result-cell').textContent()).includes("Đến hạn hôm nay")) throw new Error("Hạn đúng hôm nay bị tính trễ");
if (!(await page.locator('.form-row[data-id="form-2"] .form-result-cell').textContent()).includes("Cần kiểm tra")) throw new Error("Form thiếu ngày kết thúc chưa có trạng thái riêng");
if (!(await page.locator('.form-row[data-id="form-8"] .form-result-cell').textContent()).includes("trước ngày bắt đầu")) throw new Error("Ngày ghi nhận trước ngày bắt đầu chưa bị chặn");
if ((await page.locator('[data-teacher-group="teacher-1"] .form-late-visible-count').textContent()).trim() !== "2") throw new Error("Tổng trễ theo giáo viên không đúng");
const formTeacherColor=await page.locator('[data-teacher-group="teacher-1"]').evaluate(element=>getComputedStyle(element).getPropertyValue("--teacher").trim().toLowerCase());
if (formTeacherColor !== "#7c5ce7") throw new Error("Nhóm Link Form chưa dùng màu giáo viên");
await page.fill("#studentFormSearch", "Bé An 8/6");
if ((await page.locator(".form-row:visible").count()) !== 1) throw new Error("Tìm kiếm Link Form không lọc đúng học sinh");
await page.fill("#studentFormSearch", "");
await page.selectOption("#studentFormTeacherFilter", "teacher-2");
if ((await page.locator(".form-row:visible").count()) !== 3) throw new Error("Bộ lọc giáo viên Link Form không đúng");
await page.selectOption("#studentFormTeacherFilter", "all");
await page.selectOption("#studentFormResultFilter", "late");
if ((await page.locator(".form-row:visible").count()) !== 2 || !(await page.locator("#studentFormResultCount").textContent()).includes("2/8")) throw new Error("Bộ lọc trễ kết quả hoặc bộ đếm không đúng");
await page.selectOption("#studentFormResultFilter", "all");
if (process.env.HAPPYCHILD_FORMS_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_FORMS_SCREENSHOT,fullPage:true});

await page.click('.form-row[data-id="form-5"] .edit-student-form');
if ((await page.inputValue('input[name="courseStart"]')) !== "16/6" || (await page.inputValue('input[name="courseEnd"]')) !== "16/9" || (await page.inputValue('input[name="coursePeriod"]')) !== "16/6-16/9") throw new Error("Form Tiger không giữ đúng ngày/tháng đã tách để xác nhận");
const tigerHint=await page.locator("#formPeriodHint").textContent();
if (!tigerHint.includes("tạm giữ ngày/tháng") || tigerHint.includes("đã được xóa")) throw new Error("Thông báo Tiger mâu thuẫn với thời gian đang hiển thị");
await page.click("#dialogCancel");

await page.click('.form-row[data-id="form-1"] .edit-student-form');
await page.fill('input[name="formTitle"]', "Bé An không có khoảng ngày");
if ((await page.inputValue('input[name="courseStart"]')) !== "" || (await page.inputValue('input[name="courseEnd"]')) !== "" || (await page.inputValue('input[name="coursePeriod"]')) !== "") throw new Error("Đổi tiêu đề đã giữ sai thời gian tự động cũ");
if (!(await page.locator("#formPeriodHint").textContent()).includes("đã được xóa")) throw new Error("Thiếu cảnh báo đã xóa thời gian tự động cũ");
await page.evaluate(()=>{window.__savedStudentForm=null});
await page.click("#dialogSubmit");
await page.waitForFunction(()=>Boolean(window.__savedStudentForm));
const clearedStudentForm=await page.evaluate(()=>window.__savedStudentForm);
if (clearedStudentForm.courseStart || clearedStudentForm.courseEnd || clearedStudentForm.coursePeriod) throw new Error("Payload vẫn lưu thời gian tự động cũ sau khi đổi tiêu đề");

await page.click('.form-row[data-id="form-4"] .edit-student-form');
if (!(await page.locator("#formPeriodHint").textContent()).includes("thủ công")) throw new Error("Không nhận diện khoảng thời gian nhập thủ công");
await page.fill('input[name="formTitle"]', "Bé An khóa hè đã đổi tên");
if ((await page.inputValue('input[name="courseStart"]')) !== "10/6" || (await page.inputValue('input[name="courseEnd"]')) !== "10/9" || (await page.inputValue('input[name="coursePeriod"]')) !== "10/6-10/9") throw new Error("Đổi tiêu đề làm mất thời gian nhập thủ công");
if (!(await page.locator("#formPeriodHint").textContent()).includes("giữ thời gian nhập thủ công")) throw new Error("Thiếu nhãn giữ thời gian thủ công");
await page.click("#dialogCancel");

await page.evaluate(()=>{window.__savedStudentForm=null});
await page.click("#addStudentForm");
await page.waitForSelector('input[name="formTitle"]');
if ((await page.inputValue('input[name="resultRecordedDate"]')) !== "") throw new Error("Form mới tự điền sai ngày ghi nhận");
if (!(await page.locator("#formPeriodHint").textContent()).includes("tiêu đề Form")) throw new Error("Form Link thiếu hướng dẫn nhập tiêu đề");
await page.fill('input[name="formTitle"]', "Nam Hy 8/6 - 8/9");
if ((await page.inputValue('input[name="courseStart"]')) !== "8/6") throw new Error("Không tự tách ngày bắt đầu từ tiêu đề Form");
if ((await page.inputValue('input[name="courseEnd"]')) !== "8/9") throw new Error("Không tự tách ngày kết thúc từ tiêu đề Form");
if (!(await page.inputValue('input[name="coursePeriod"]')).includes("8/6") || !(await page.inputValue('input[name="coursePeriod"]')).includes("8/9")) throw new Error("Không tự điền thời gian Link Form");
await page.fill('input[name="formLink"]', "https://docs.google.com/forms/d/e/new-form/viewform");
await page.fill('input[name="teacherHours"]', "1.5");
await page.click("#dialogSubmit");
await page.waitForFunction(()=>Boolean(window.__savedStudentForm));
const savedStudentForm=await page.evaluate(()=>window.__savedStudentForm);
if (savedStudentForm.formLink !== "https://docs.google.com/forms/d/e/new-form/viewform") throw new Error("Không lưu đúng formLink");
if (savedStudentForm.courseStart !== "8/6" || savedStudentForm.courseEnd !== "8/9" || !savedStudentForm.coursePeriod.includes("8/9")) throw new Error("Payload Link Form thiếu thời gian đã tách");
if (!savedStudentForm.studentId || !savedStudentForm.teacherId) throw new Error("Payload Link Form thiếu liên kết học sinh/giáo viên");

await page.click('a[href="#templates"]');
await page.waitForSelector("#addTemplate");
if (await page.locator(".delete-template").count() !== 5) throw new Error("Thiếu thùng rác lịch mẫu");
if (await page.locator(".template-day-group").count() !== 3) throw new Error("Lịch mẫu chưa được nhóm theo thứ");
if (await page.locator(".template-slot-group").count() !== 3) throw new Error("Lịch mẫu chưa gộp đúng mỗi khung giờ thành một dropdown");
if (await page.locator(".template-teacher-group").count() !== 4) throw new Error("Lịch mẫu thiếu nhóm giáo viên bên trong khung giờ");
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Lịch mẫu chưa mặc định thu gọn hoàn toàn");
const mondayTemplateSlot=page.locator('.template-day-group[data-template-day="0"] .template-slot-group[data-start="13:00"][data-end="14:00"]');
if (await mondayTemplateSlot.count() !== 1 || await mondayTemplateSlot.locator(".template-teacher-group").count() !== 2) throw new Error("Hai cô cùng giờ chưa nằm trong một dropdown khung giờ");
const mondayTemplateSummary=await mondayTemplateSlot.locator("summary").textContent();
if (!mondayTemplateSummary.includes("Cô Ngân") || !mondayTemplateSummary.includes("Cô Mai") || !mondayTemplateSummary.includes("3 học sinh")) throw new Error("Tóm tắt lịch mẫu thiếu giờ, cô hoặc tổng học sinh");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "5/5 lịch") throw new Error("Bộ đếm lịch mẫu ban đầu không đúng");
if (!(await page.locator('.template-student-row[data-template-id="template-1"] .template-capacity').textContent()).includes("1 chỗ/lịch")) throw new Error("Lịch mẫu không hiển thị sức chứa mặc định 1 chỗ/lịch");
const templateTeacherColor=await mondayTemplateSlot.locator('.template-teacher-group[data-teacher="teacher-1"]').evaluate(element=>getComputedStyle(element).getPropertyValue("--teacher").trim());
if (templateTeacherColor.toLowerCase() !== "#7c5ce7") throw new Error("Khung lịch mẫu không dùng màu giáo viên");
const templateChildColor=await page.locator('.template-student-row[data-template-id="template-4"]').evaluate(element=>getComputedStyle(element).getPropertyValue("--student").trim().toLowerCase());
if (templateChildColor !== "#20a779") throw new Error("Màu học sinh trong lịch mẫu chưa theo giáo viên của từng buổi");
if (process.env.HAPPYCHILD_TEMPLATES_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_TEMPLATES_SCREENSHOT,fullPage:true});
await page.fill("#templateSearch","Bé Bình");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "3/5 lịch" || await page.locator('.template-student-row:not([hidden])').count() !== 3) throw new Error("Tìm học sinh trong lịch mẫu không đúng");
if (await page.locator('.template-day-group:not([hidden])[open]').count() !== 2 || await page.locator('.template-slot-group:not([hidden])[open]').count() !== 2) throw new Error("Tìm lịch mẫu không tự mở đúng ngày và khung giờ");
if (process.env.HAPPYCHILD_TEMPLATES_FILTERED_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_TEMPLATES_FILTERED_SCREENSHOT,fullPage:true});
await page.fill("#templateSearch","");
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Xóa bộ lọc chưa thu gọn lại lịch mẫu");
await page.selectOption("#templateTeacherFilter","teacher-2");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "2/5 lịch") throw new Error("Lọc lịch mẫu theo giáo viên không đúng");
await page.selectOption("#templateDayFilter","0");
await page.fill("#templateSearch","Bé Bình");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "1/5 lịch" || await page.locator('.template-day-group:not([hidden])[open]').count() !== 1 || await page.locator('.template-slot-group:not([hidden])[open]').count() !== 1) throw new Error("Kết hợp tìm kiếm, giáo viên và thứ chưa lọc/mở đúng khung giờ");
if (await mondayTemplateSlot.locator('.template-teacher-group[data-teacher="teacher-1"]:not([hidden])').count()) throw new Error("Nhóm cô không khớp vẫn hiện sau khi lọc kết hợp");
await page.fill("#templateSearch","");
await page.selectOption("#templateTeacherFilter","all");
await page.selectOption("#templateDayFilter","6");
if ((await page.locator("#templateResultCount").textContent()).trim() !== "1/5 lịch") throw new Error("Lọc lịch mẫu theo thứ không đúng");
await page.selectOption("#templateDayFilter","all");
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Lịch mẫu không thu gọn sau khi xóa toàn bộ bộ lọc");
await page.click("#expandTemplateGroups");
if (await page.locator(".template-day-group[open]").count() !== 3 || await page.locator(".template-slot-group[open]").count() !== 3) throw new Error("Nút Mở tất cả lịch mẫu không hoạt động");
await page.click("#collapseTemplateGroups");
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Nút Thu gọn lịch mẫu không hoạt động");
const templateHardening=await page.evaluate(()=>{const button=[...document.querySelectorAll(".edit-template")].find(element=>element.dataset.id.startsWith("template-xss")),row=button?.closest(".template-student-row");return {marker:Boolean(document.querySelector("#stored-xss-marker")),executed:Boolean(window.__storedXss),found:Boolean(button),inlineHandler:button?.hasAttribute("onclick"),text:row?.textContent||""}});
if (templateHardening.marker || templateHardening.executed || !templateHardening.found || templateHardening.inlineHandler || templateHardening.text.includes("<img")) throw new Error("Stored-XSS từ lịch mẫu chưa được chặn");
await page.evaluate(()=>{window.__savedTemplate=null});
await page.click("#addTemplate");
if (await page.locator('select[name="teacherId"]').count() !== 1) throw new Error("Lịch mẫu thiếu giáo viên");
await page.selectOption('select[name="studentId"]',"student-2");
await page.selectOption('select[name="dayOfWeek"]',"2");
await page.click("#dialogSubmit");
await page.waitForFunction(()=>Boolean(window.__savedTemplate));
const savedGroupedTemplate=await page.evaluate(()=>window.__savedTemplate);
if (savedGroupedTemplate.capacity !== 1 || savedGroupedTemplate.studentId !== "student-2") throw new Error("Lịch mẫu cùng khung giờ chưa giữ capacity mặc định 1");

await page.click('a[href="#notes"]');
await page.waitForSelector("#addNote");
if (await page.locator(".delete-note").count() !== 1) throw new Error("Thiếu thùng rác ghi chú");
await page.click("#addNote");
if (await page.locator('textarea[name="details"]').count() !== 1) throw new Error("Form ghi chú thiếu chi tiết");
await page.click("#dialogCancel");

await page.click('a[href="#reports"]');
await page.waitForFunction(()=>document.querySelector("#content")?.textContent.includes("Bé Bình"));
const teacherReport=await page.locator(".report-table").nth(1).textContent();
if (!teacherReport.includes("1 giờ") || teacherReport.includes("2 giờ")) throw new Error("Giờ giáo viên bị nhân theo số học sinh");

await page.setViewportSize({ width: 390, height: 844 });
await page.evaluate(()=>document.querySelector("#briefingDialog").showModal());
await page.click("#briefingDone");
await page.evaluate(()=>{location.hash="calendar"});
await page.waitForSelector(".calendar-grid");
if (await page.locator("details.day-column[open]").count() !== 1) throw new Error("Lịch mobile chưa thu gọn từng ngày");
const mobileCalendarLayout=await page.locator(".calendar-grid").evaluate(grid=>{const day=grid.querySelector(".day-column"),slot=grid.querySelector(".time-slot");return {overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,day:day?.getBoundingClientRect().width||0,slot:slot?.getBoundingClientRect().width||0}});
if (mobileCalendarLayout.overflow>1 || mobileCalendarLayout.slot>mobileCalendarLayout.day+1 || await page.locator("details.time-slot[open]").count()) throw new Error("Lịch tuần mobile bị tràn hoặc khung giờ chưa thu gọn");
await page.evaluate(()=>{location.hash="forms"});
await page.waitForSelector(".form-teacher-group");
if (await page.locator(".form-teacher-group[open]").count() !== 1) throw new Error("Nhóm Link Form mobile chưa thu gọn");
const mobileResultLayout=await page.locator('.form-row[data-id="form-1"]').evaluate(row=>{const cell=row.querySelector(".form-result-cell");return {row:row.getBoundingClientRect().width,cell:cell.getBoundingClientRect().width,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}});
if (mobileResultLayout.overflow>1 || mobileResultLayout.cell<mobileResultLayout.row*.9) throw new Error("Ô kết quả mobile chưa chiếm toàn chiều rộng hoặc bị tràn ngang");
await page.evaluate(()=>{location.hash="templates"});
await page.waitForSelector(".template-student-row",{state:"attached"});
if (await page.locator(".template-day-group[open],.template-slot-group[open]").count()) throw new Error("Lịch mẫu mobile chưa mặc định thu gọn hoàn toàn");
await page.fill("#templateSearch","Mang sách");
if (await page.locator(".template-day-group[open]").count() !== 1 || await page.locator(".template-slot-group[open]").count() !== 1) throw new Error("Tìm lịch mẫu mobile không tự mở đúng ngày và giờ");
const mobileTemplateLayout=await page.locator('.template-student-row[data-template-id="template-2"]').evaluate(row=>({row:row.getBoundingClientRect().width,parent:row.parentElement.getBoundingClientRect().width,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}));
if (mobileTemplateLayout.overflow>1 || mobileTemplateLayout.row>mobileTemplateLayout.parent+1) throw new Error("Lịch mẫu mobile bị tràn ngang");
if (process.env.HAPPYCHILD_TEMPLATES_MOBILE_SCREENSHOT) await page.screenshot({path:process.env.HAPPYCHILD_TEMPLATES_MOBILE_SCREENSHOT,fullPage:true});

const racePage=await browser.newPage({viewport:{width:1200,height:800}});
const raceErrors=[];
racePage.on("pageerror",error=>raceErrors.push(error.message));
const raceStoreMock=storeMock
  .replace(/const week=\{[^\n]+\};/, 'const week={id:"week-2026-08-10",weekNumber:1,label:"Tuần 1 (10/08/2026–16/08/2026)",startDate:ts("2026-08-10T12:00:00"),endDate:ts("2026-08-16T12:00:00"),status:"active"};\nconst week2={id:"week-2026-08-17",weekNumber:2,label:"Tuần 2 (17/08/2026–23/08/2026)",startDate:ts("2026-08-17T12:00:00"),endDate:ts("2026-08-23T12:00:00"),status:"active"};')
  .replace(/const session=\{[^\n]+\};/, match=>`${match}\nconst sessionB={...session,id:"session-b",date:ts("2026-08-17T12:00:00"),dateKey:"2026-08-17",dayOfWeek:0,status:"scheduled",note:"Tuần B"};`)
  .replace(/export const subscribe=\(name,cb\)=>\{[^\n]+\};/, 'export const subscribe=(name,cb)=>{setTimeout(()=>cb(name==="students"?[student,student2]:name==="teachers"?[teacher,teacher2]:name==="scheduleTemplates"?[template]:name==="weeks"?[week,week2]:[]),0);return()=>{}};')
  .replace(/export const subscribeSessions=\(id,cb\)=>\{[^\n]+\};/, 'let firstWeekCallback; export const subscribeSessions=(id,cb)=>{if(id===week.id){firstWeekCallback=cb;setTimeout(()=>cb([session]),0)}else{setTimeout(()=>firstWeekCallback?.([{...session,id:"stale-week-a"}]),250);setTimeout(()=>cb([sessionB]),700)}return()=>{}};')
  .replace('export const deleteWeek=async()=>{};', 'export const deleteWeek=async(id,sessions)=>{window.__deleteWeekCalls=(window.__deleteWeekCalls||0)+1;window.__deletedWeek={id,sessionIds:sessions.map(item=>item.id)}};');
await racePage.route("**/happychild/js/auth.js*",route=>route.fulfill({contentType:"text/javascript",body:authMock}));
await racePage.route("**/happychild/js/store.js*",route=>route.fulfill({contentType:"text/javascript",body:raceStoreMock}));
await racePage.goto("http://127.0.0.1:8080/happychild/#calendar",{waitUntil:"domcontentloaded"});
await racePage.waitForSelector("#briefingDialog[open]");
await racePage.click("#briefingDone");
await racePage.waitForSelector("#deleteWeekBtn:not([disabled])");
await racePage.selectOption("#weekSelect","week-2026-08-17");
if ((await racePage.inputValue("#weekSelect"))!=="week-2026-08-17") throw new Error("Chuyển tuần chậm không giữ đúng weekId mới");
if (!(await racePage.locator("#deleteWeekBtn").isDisabled()) || !(await racePage.locator("#addSessionTop").isDisabled()) || !(await racePage.locator(".week-sessions-loading").count())) throw new Error("Tuần mới chưa khóa thao tác khi sessions đang tải");
await racePage.locator("#deleteWeekBtn").dispatchEvent("click");
if (await racePage.evaluate(()=>window.__deleteWeekCalls||0)) throw new Error("Guard xóa tuần cho phép chạy trước snapshot");
await racePage.waitForTimeout(350);
if (!(await racePage.locator("#deleteWeekBtn").isDisabled()) || !(await racePage.locator(".week-sessions-loading").count())) throw new Error("Callback tuần cũ đã mở khóa nhầm tuần mới");
await racePage.waitForSelector("#deleteWeekBtn:not([disabled])",{timeout:3000});
if (!(await racePage.locator('[data-session="session-b"]').count()) || await racePage.locator('[data-session="stale-week-a"]').count()) throw new Error("Snapshot tuần mới bị trộn với callback tuần cũ");
racePage.once("dialog",dialog=>dialog.accept());
await racePage.click("#deleteWeekBtn");
await racePage.waitForFunction(()=>window.__deleteWeekCalls===1);
const deletedWeek=await racePage.evaluate(()=>window.__deletedWeek);
if (deletedWeek.id!=="week-2026-08-17" || JSON.stringify(deletedWeek.sessionIds)!==JSON.stringify(["session-b"])) throw new Error("Xóa tuần dùng sai weekId hoặc danh sách sessions");
if (raceErrors.length) throw new Error(`Race page errors: ${raceErrors.join(" | ")}`);
await racePage.close();

const seedPage=await browser.newPage({viewport:{width:1100,height:760}});
const seedErrors=[];
seedPage.on("pageerror",error=>seedErrors.push(error.message));
const ownerAuthMock=authMock.replace('uid:"test-user"','uid:"EplnbxgWTaal9N5QgflBWaT1LWG3"');
const delayedEmptyStoreMock=storeMock
  .replace(/export const subscribe=\(name,cb\)=>\{[^\n]+\};/, 'export const subscribe=(name,cb)=>{const delay=name==="students"?700:name==="teachers"?900:0;setTimeout(()=>cb([]),delay);return()=>{}};')
  .replace(/export const subscribeStudentForms=cb=>\{[^\n]+\};/, 'export const subscribeStudentForms=cb=>{setTimeout(()=>cb([]),1100);return()=>{}};');
await seedPage.route("**/happychild/js/auth.js*",route=>route.fulfill({contentType:"text/javascript",body:ownerAuthMock}));
await seedPage.route("**/happychild/js/store.js*",route=>route.fulfill({contentType:"text/javascript",body:delayedEmptyStoreMock}));
await seedPage.goto("http://127.0.0.1:8080/happychild/#settings",{waitUntil:"domcontentloaded"});
await seedPage.waitForSelector("#appView:not(.hidden)");
if (await seedPage.locator("#seedBtn").count()) throw new Error("Nút seed xuất hiện trước khi subscriptions tải xong");
await seedPage.waitForSelector("#seedBtn",{timeout:5000});
if (seedErrors.length) throw new Error(`Seed page errors: ${seedErrors.join(" | ")}`);
await seedPage.close();

if (errors.length) throw new Error(`Page errors: ${errors.join(" | ")}`);
console.log(JSON.stringify({status:"ok",checks:100,saveSessionCalls:await page.evaluate(()=>window.__saveSessionCalls||0)}));
await browser.close();
