import { db } from "./firebase.js?v=20260826-5";
import { collection,doc,addDoc,updateDoc,deleteDoc,getDoc,getDocs,onSnapshot,query,orderBy,where,serverTimestamp,Timestamp,writeBatch,runTransaction,increment,limit } from "https://www.gstatic.com/firebasejs/11.1.0/firebase-firestore.js";
import { addDays,isoDate,weekLabel,overlap,parseFormPeriod,elapsedSessionTarget,floorScheduleTime } from "./utils.js?v=20260829-1";
import {canonicalRosterKey,planRosterReconciliation} from "./roster-reconcile.js?v=20260903-2";

const withTimeout=(promise,ms,message)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(message)),ms))]);
const validDateKey=(value,label="Ngày")=>{const dateKey=String(value||"").trim();if(!dateKey)return "";if(!/^\d{4}-\d{2}-\d{2}$/.test(dateKey))throw new Error(`${label} phải có dạng YYYY-MM-DD.`);const date=new Date(`${dateKey}T12:00:00`);if(Number.isNaN(date.getTime())||isoDate(date)!==dateKey)throw new Error(`${label} không hợp lệ.`);return dateKey};
const activeSession=session=>!["absent","holiday","cancelled"].includes(session.status);
const limitedText=(value,label,max)=>{const result=String(value??"").trim();if(result.length>max)throw new Error(`${label} không được vượt quá ${max} ký tự.`);return result};
const validTime=(value,label)=>{const result=String(value||"").trim();if(!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(result))throw new Error(`${label} phải có dạng HH:mm hợp lệ.`);return result};
const wholeHour=(value,label)=>floorScheduleTime(validTime(value,label));
const validSessionType=value=>{const result=String(value||"regular");if(!["regular","makeup"].includes(result))throw new Error("Loại buổi học không hợp lệ.");return result};
const validSessionStatus=(value,type)=>{const allowed=type==="makeup"?["makeup_scheduled","makeup_completed","holiday","cancelled"]:["scheduled","attended","absent","holiday","cancelled"],result=String(value||(type==="makeup"?"makeup_scheduled":"scheduled"));if(!allowed.includes(result))throw new Error("Trạng thái không phù hợp với loại buổi học.");return result};
const storedCapacity=value=>{const result=Number(value);return Number.isInteger(result)&&result>=1&&result<=20?result:1};
export const MAX_SIMULTANEOUS_STUDENTS=7;
const regularSeatContribution=session=>String(session?.type||"regular")==="makeup"?0:storedCapacity(session?.capacity);
const groupedSlotCapacity=(sessions,fallback=1)=>{const regularSeats=sessions.reduce((total,session)=>total+regularSeatContribution(session),0);return regularSeats||storedCapacity(fallback)};
const dirtyWeekPatch=user=>({status:"active",summaryDirtyAt:serverTimestamp(),updatedAt:serverTimestamp(),updatedBy:user.uid});
const validColor=(value,fallback)=>{const color=String(value||fallback).trim();if(!/^#[0-9a-f]{6}$/i.test(color))throw new Error("Màu đại diện không hợp lệ.");return color};
const wholeNumber=(value,label,fallback=0)=>{const result=value==null||value===""?fallback:Number(value);if(!Number.isInteger(result)||result<0)throw new Error(`${label} phải là số nguyên không âm.`);return result};
const nonNegativeNumber=(value,label)=>{const result=value==null||value===""?0:Number(value);if(!Number.isFinite(result)||result<0||result>10000)throw new Error(`${label} phải là số từ 0 đến 10.000.`);return result};
const validFormLink=value=>{let link=limitedText(value,"Link Form",2048);if(!link)return "";if(/^www\./i.test(link))link=`https://${link}`;let url;try{url=new URL(link)}catch{throw new Error("Link Form không hợp lệ.")}if(!["http:","https:"].includes(url.protocol))throw new Error("Link Form phải bắt đầu bằng http:// hoặc https://.");return link};
const studentFormView=data=>({displayOrder:Number(data.displayOrder||0),studentId:String(data.studentId||""),teacherId:String(data.teacherId||""),formLink:String(data.formLink||""),formTitle:String(data.formTitle||""),courseStart:String(data.courseStart||""),courseEnd:String(data.courseEnd||""),coursePeriod:String(data.coursePeriod||""),resultRecordedDate:String(data.resultRecordedDate||""),teacherHours:Number(data.teacherHours||0),note:String(data.note||""),sourceRow:Number(data.sourceRow||0),historyCount:Array.isArray(data.linkHistory)?data.linkHistory.length:0});
const cleanFormHistory=value=>Array.isArray(value)?value.filter(item=>item&&typeof item==="object"&&String(item.formLink||"").trim()).slice(-49):[];
const formHistoryEntry=data=>({formLink:String(data.formLink||"").trim(),formTitle:String(data.formTitle||"").trim(),courseStart:String(data.courseStart||"").trim(),courseEnd:String(data.courseEnd||"").trim(),coursePeriod:String(data.coursePeriod||"").trim(),resultRecordedDate:String(data.resultRecordedDate||"").trim(),teacherHours:Number(data.teacherHours||0),note:String(data.note||"").trim(),archivedAt:Timestamp.now()});
function studentFormPayload(data={}){const studentId=limitedText(data.studentId,"Học sinh",160),teacherId=limitedText(data.teacherId,"Giáo viên",160),formLink=validFormLink(data.formLink),formTitle=limitedText(data.formTitle,"Tiêu đề Form",500),parsed=parseFormPeriod(formTitle),courseStart=limitedText(data.courseStart||parsed?.courseStart||"","Ngày bắt đầu",40),courseEnd=limitedText(data.courseEnd||parsed?.courseEnd||"","Ngày kết thúc",40),coursePeriod=limitedText(data.coursePeriod||(courseStart&&courseEnd?`${courseStart}-${courseEnd}`:parsed?.coursePeriod||""),"Khoảng thời gian",100),sourceRow=wholeNumber(data.sourceRow,"Dòng nguồn",0),displayOrder=wholeNumber(data.displayOrder,"Thứ tự hiển thị",sourceRow);if(!studentId)throw new Error("Vui lòng chọn học sinh cho Form.");if(!teacherId)throw new Error("Vui lòng chọn giáo viên phụ trách Form.");return {displayOrder,studentId,teacherId,formLink,formTitle,courseStart,courseEnd,coursePeriod,resultRecordedDate:validDateKey(data.resultRecordedDate,"Ngày ghi kết quả"),teacherHours:nonNegativeNumber(data.teacherHours,"Số giờ giáo viên"),note:limitedText(data.note,"Ghi chú",5000),sourceRow}}
function templatePayload(data={}){const studentId=limitedText(data.studentId,"Học sinh",160),teacherId=limitedText(data.teacherId,"Giáo viên",160),dayOfWeek=Number(data.dayOfWeek),capacity=Number(data.capacity||1),startTime=wholeHour(data.startTime,"Giờ bắt đầu"),endTime=wholeHour(data.endTime,"Giờ kết thúc");if(!studentId||!teacherId)throw new Error("Vui lòng chọn học sinh và giáo viên.");if(!Number.isInteger(dayOfWeek)||dayOfWeek<0||dayOfWeek>6)throw new Error("Thứ trong tuần không hợp lệ.");if(!Number.isInteger(capacity)||capacity<1||capacity>7)throw new Error("Sức chứa phải từ 1 đến 7 học sinh.");if(startTime>=endTime)throw new Error("Sau khi làm tròn xuống, giờ kết thúc phải sau giờ bắt đầu.");return {studentId,teacherId,dayOfWeek,startTime,endTime,capacity,active:data.active!==false,note:limitedText(data.note,"Ghi chú",5000)}}
export const subscribe=(name,cb,clauses=[])=>onSnapshot(query(collection(db,name),...clauses),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))),e=>cb(null,e));
export const subscribeSessions=(weekId,cb)=>onSnapshot(
  collection(db,"weeks",weekId,"sessions"),
  snapshot=>cb(snapshot.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{
    const dateCompare=String(a.dateKey||"").localeCompare(String(b.dateKey||""));
    return dateCompare||String(a.startTime||"").localeCompare(String(b.startTime||""));
  })),
  error=>cb(null,error)
);
export async function saveStudent(data,user,id){const payload={fullName:String(data.fullName||"").trim(),shortName:String(data.shortName||"").trim(),birthday:validDateKey(data.birthday,"Ngày sinh học sinh"),color:validColor(data.color,"#5754d9"),parentPhone:String(data.parentPhone||"").trim(),note:String(data.note||"").trim(),active:data.active!==false,updatedAt:serverTimestamp(),updatedBy:user.uid};if(!payload.fullName)throw new Error("Vui lòng nhập tên học sinh.");if(id)return updateDoc(doc(db,"students",id),payload);return addDoc(collection(db,"students"),{...payload,makeupBalance:0,createdAt:serverTimestamp(),createdBy:user.uid})}
export async function saveTeacher(data,user,id){const payload={fullName:String(data.fullName||"").trim(),shortName:String(data.shortName||"").trim(),birthday:validDateKey(data.birthday,"Ngày sinh giáo viên"),color:validColor(data.color,"#7c5ce7"),phone:String(data.phone||"").trim(),note:String(data.note||"").trim(),active:data.active!==false,updatedAt:serverTimestamp(),updatedBy:user.uid};if(!payload.fullName)throw new Error("Vui lòng nhập tên giáo viên.");if(id)return updateDoc(doc(db,"teachers",id),payload);return addDoc(collection(db,"teachers"),{...payload,createdAt:serverTimestamp(),createdBy:user.uid})}
export async function saveTeacherLeave(data,user,id){const teacherId=limitedText(data.teacherId,"Giáo viên",160),startDate=validDateKey(data.startDate,"Ngày bắt đầu"),endDate=validDateKey(data.endDate,"Ngày kết thúc"),leaveType=data.leaveType==="session"?"session":"full_day",startTime=leaveType==="session"?wholeHour(data.startTime,"Giờ bắt đầu"):"",endTime=leaveType==="session"?wholeHour(data.endTime,"Giờ kết thúc"):"",note=limitedText(data.note,"Lý do nghỉ phép",1000);if(!user?.uid||!teacherId)throw new Error("Vui lòng đăng nhập và chọn giáo viên.");if(!startDate||!endDate||startDate>endDate)throw new Error("Khoảng ngày nghỉ không hợp lệ.");if(leaveType==="session"&&startTime>=endTime)throw new Error("Khung giờ nghỉ không hợp lệ.");const payload={teacherId,startDate,endDate,leaveType,startTime,endTime,note,updatedAt:serverTimestamp(),updatedBy:user.uid};if(id)return updateDoc(doc(db,"teacherLeaves",id),payload);return addDoc(collection(db,"teacherLeaves"),{...payload,createdAt:serverTimestamp(),createdBy:user.uid})}
export async function deleteTeacherLeave(id,user){if(!user?.uid)throw new Error("Vui lòng đăng nhập lại.");return deleteDoc(doc(db,"teacherLeaves",limitedText(id,"Đơn nghỉ phép",160)))}
export const subscribeStudentForms=cb=>onSnapshot(collection(db,"studentForms"),snapshot=>cb(snapshot.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>{const order=Number(a.displayOrder||0)-Number(b.displayOrder||0);if(order)return order;const row=Number(a.sourceRow||0)-Number(b.sourceRow||0);return row||String(a.formTitle||"").localeCompare(String(b.formTitle||""),"vi")})),error=>cb(null,error));
export async function saveStudentForm(data,user,id){if(!user?.uid)throw new Error("Vui lòng đăng nhập lại.");const business=studentFormPayload(data),formRef=id?doc(db,"studentForms",id):doc(collection(db,"studentForms"));if(id){await withTimeout(runTransaction(db,async tx=>{const current=await tx.get(formRef);if(!current.exists())throw new Error("Không tìm thấy Form học sinh để cập nhật.");const previous=current.data(),history=cleanFormHistory(previous.linkHistory),linkChanged=Boolean(previous.formLink&&String(previous.formLink)!==business.formLink);if(linkChanged){const archived=formHistoryEntry(previous),duplicate=history.some(item=>String(item.formLink||"")===archived.formLink&&String(item.coursePeriod||"")===archived.coursePeriod);if(!duplicate)history.push(archived)}const update={...business,updatedAt:serverTimestamp(),updatedBy:user.uid};if(linkChanged||Array.isArray(previous.linkHistory))update.linkHistory=history.slice(-50);tx.update(formRef,update);tx.set(doc(collection(db,"auditLogs")),{entityType:"studentForm",entityId:formRef.id,action:linkChanged?"student_form_link_replaced":"student_form_updated",before:studentFormView(previous),after:{...business,historyCount:history.length},reason:linkChanged?"Thay mục tiêu và lưu Link Form cũ":"Cập nhật Form học sinh",userId:user.uid,createdAt:serverTimestamp()})}),12000,"Firebase không phản hồi khi lưu Form học sinh.");return formRef.id}const batch=writeBatch(db);batch.set(formRef,{...business,linkHistory:[],createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:user.uid,updatedBy:user.uid});batch.set(doc(collection(db,"auditLogs")),{entityType:"studentForm",entityId:formRef.id,action:"student_form_created",before:{},after:business,reason:"Tạo Form học sinh",userId:user.uid,createdAt:serverTimestamp()});await withTimeout(batch.commit(),12000,"Firebase không phản hồi khi lưu Form học sinh.");return formRef.id}
export async function deleteStudentForm(id,user){if(!user?.uid)throw new Error("Vui lòng đăng nhập lại.");const formRef=doc(db,"studentForms",id),deleted=await withTimeout(runTransaction(db,async tx=>{const current=await tx.get(formRef);if(!current.exists())return false;tx.delete(formRef);tx.set(doc(collection(db,"auditLogs")),{entityType:"studentForm",entityId:id,action:"student_form_deleted",before:studentFormView(current.data()),after:{},reason:"Xóa Form học sinh",userId:user.uid,createdAt:serverTimestamp()});return true}),12000,"Firebase không phản hồi khi xóa Form học sinh.");return deleted}
export const subscribeNotes=cb=>onSnapshot(query(collection(db,"notes"),orderBy("dateKey","asc")),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))),e=>cb(null,e));
export async function saveNote(data,user,id){const payload={dateKey:validDateKey(data.dateKey,"Ngày ghi chú"),title:String(data.title||"").trim(),details:String(data.details||"").trim(),updatedAt:serverTimestamp(),updatedBy:user.uid};if(!payload.dateKey)throw new Error("Vui lòng chọn ngày ghi chú.");if(!payload.details)throw new Error("Vui lòng nhập chi tiết ghi chú.");if(id)return updateDoc(doc(db,"notes",id),payload);return addDoc(collection(db,"notes"),{...payload,createdAt:serverTimestamp(),createdBy:user.uid})}
export async function saveTemplate(data,user,id){const payload={...templatePayload(data),updatedAt:serverTimestamp(),updatedBy:user.uid};if(payload.active){const snapshot=await getDocs(collection(db,"scheduleTemplates")),concurrent=snapshot.docs.filter(item=>item.id!==id&&item.data().active!==false&&Number(item.data().dayOfWeek)===payload.dayOfWeek&&overlap(item.data().startTime,item.data().endTime,payload.startTime,payload.endTime));if(concurrent.length>=MAX_SIMULTANEOUS_STUDENTS)throw new Error(`Khung giờ đã đủ ${MAX_SIMULTANEOUS_STUDENTS} học sinh.`)}if(id)return updateDoc(doc(db,"scheduleTemplates",id),payload);return addDoc(collection(db,"scheduleTemplates"),{...payload,createdAt:serverTimestamp(),createdBy:user.uid})}
export const removeRecord=(name,id)=>deleteDoc(doc(db,name,id));
async function hasSessionReference(field,id){const weeks=await getDocs(collection(db,"weeks")),checks=await Promise.all(weeks.docs.map(week=>getDocs(query(collection(db,"weeks",week.id,"sessions"),where(field,"==",id),limit(1)))));return checks.some(s=>!s.empty)}
export async function deleteStudent(studentId,user){const [templateSnap,ledgerSnap,formSnap,sessionUsed]=await Promise.all([getDocs(query(collection(db,"scheduleTemplates"),where("studentId","==",studentId),limit(1))),getDocs(query(collection(db,"makeupTransactions"),where("studentId","==",studentId),limit(1))),getDocs(query(collection(db,"studentForms"),where("studentId","==",studentId),limit(1))),hasSessionReference("studentId",studentId)]);if(!templateSnap.empty||!ledgerSnap.empty||!formSnap.empty||sessionUsed)throw new Error("Học sinh còn lịch, Form hoặc giao dịch liên quan. Hãy xóa dữ liệu liên quan trước, hoặc dùng Dọn dữ liệu thử nghiệm.");const batch=writeBatch(db);batch.delete(doc(db,"students",studentId));batch.set(doc(collection(db,"auditLogs")),{entityType:"student",entityId:studentId,action:"student_deleted",before:{},after:{},reason:"Xóa hồ sơ test không còn tham chiếu",userId:user.uid,createdAt:serverTimestamp()});return batch.commit()}
export async function deleteTeacher(teacherId,user){const [templateSnap,formSnap,sessionUsed]=await Promise.all([getDocs(query(collection(db,"scheduleTemplates"),where("teacherId","==",teacherId),limit(1))),getDocs(query(collection(db,"studentForms"),where("teacherId","==",teacherId),limit(1))),hasSessionReference("teacherId",teacherId)]);if(!templateSnap.empty||!formSnap.empty||sessionUsed)throw new Error("Giáo viên còn lịch hoặc Form liên quan. Hãy xóa dữ liệu liên quan trước, hoặc dùng Dọn dữ liệu thử nghiệm.");const batch=writeBatch(db);batch.delete(doc(db,"teachers",teacherId));batch.set(doc(collection(db,"auditLogs")),{entityType:"teacher",entityId:teacherId,action:"teacher_deleted",before:{},after:{},reason:"Xóa hồ sơ test không còn tham chiếu",userId:user.uid,createdAt:serverTimestamp()});return batch.commit()}
export async function createWeek({weekNumber,startDate},templates,weeks,user){
  const normalizedStartDate=validDateKey(startDate,"Ngày bắt đầu tuần"),start=new Date(`${normalizedStartDate}T12:00:00`),end=addDays(start,6),activeTemplates=templates.filter(t=>t.active).map(t=>({id:t.id,...templatePayload(t)}));
  if(Number.isNaN(start.getTime()))throw new Error("Ngày bắt đầu không hợp lệ.");
  if(start.getDay()!==1)throw new Error("Ngày bắt đầu tuần phải là Thứ Hai.");
  if(activeTemplates.length>450)throw new Error("Lịch mẫu vượt quá 450 buổi; hãy giảm số lượng trước khi tạo tuần.");
  activeTemplates.forEach((item,index)=>{const concurrent=activeTemplates.slice(0,index).filter(peer=>peer.dayOfWeek===item.dayOfWeek&&overlap(peer.startTime,peer.endTime,item.startTime,item.endTime));if(concurrent.length>=MAX_SIMULTANEOUS_STUDENTS)throw new Error(`Lịch mẫu có khung giờ vượt quá ${MAX_SIMULTANEOUS_STUDENTS} học sinh.`)});
  if(weeks.some(w=>{const a=w.startDate.toDate(),b=w.endDate.toDate();return start<=b&&end>=a}))throw new Error("Khoảng ngày này trùng với một tuần đã tồn tại.");
  // ID ổn định giúp việc thử lại an toàn nếu mạng ngắt giữa lúc tạo tuần.
  const weekRef=doc(db,"weeks",`week-${normalizedStartDate}`);const batch=writeBatch(db);
  if((await getDoc(weekRef)).exists())throw new Error("Tuần này đã tồn tại. Hãy tải lại trang.");
  batch.set(weekRef,{weekNumber:Number(weekNumber),startDate:Timestamp.fromDate(start),endDate:Timestamp.fromDate(end),label:weekLabel(weekNumber,start,end),status:"active",createdFromTemplateAt:serverTimestamp(),createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:user.uid,updatedBy:user.uid});
  activeTemplates.forEach(t=>{const date=addDays(start,t.dayOfWeek),ref=doc(db,"weeks",weekRef.id,"sessions",`template-${t.id}`);batch.set(ref,{studentId:t.studentId,teacherId:t.teacherId,date:Timestamp.fromDate(date),dateKey:isoDate(date),dayOfWeek:t.dayOfWeek,startTime:t.startTime,endTime:t.endTime,capacity:t.capacity,type:"regular",status:"scheduled",sourceTemplateId:t.id,note:t.note,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:user.uid,updatedBy:user.uid})});
  batch.set(doc(collection(db,"auditLogs")),{entityType:"week",entityId:weekRef.id,action:"week_created",before:{},after:{weekNumber:Number(weekNumber),startDate:normalizedStartDate,endDate:isoDate(end),sessions:activeTemplates.length},reason:"Tạo tuần từ lịch mẫu",userId:user.uid,createdAt:serverTimestamp()});
  await withTimeout(batch.commit(),12000,"Firebase không phản hồi sau 12 giây. Hãy kiểm tra Firestore Rules và kết nối mạng rồi thử lại.");return weekRef.id;
}
export async function finalizeWeekSummary(weekId,summary,user){
  if(!user?.uid)throw new Error("Vui lòng đăng nhập lại.");
  const id=limitedText(weekId,"Tuần",160);if(!id)throw new Error("Không tìm thấy tuần cần chốt.");
  const sourceFingerprint=limitedText(summary?.sourceFingerprint,"Mã đối chiếu",160),counts=summary?.counts||{},hours=summary?.hours||{},studentStats=Array.isArray(summary?.studentStats)?summary.studentStats.slice(0,500):[],teacherStats=Array.isArray(summary?.teacherStats)?summary.teacherStats.slice(0,100):[];
  const cleanCount=value=>Math.max(0,wholeNumber(value,"Số buổi",0)),cleanMinutes=value=>Math.max(0,wholeNumber(value,"Số phút",0));
  const payload={version:1,sourceFingerprint,counts:{total:cleanCount(counts.total),planned:cleanCount(counts.planned),learned:cleanCount(counts.learned),absent:cleanCount(counts.absent),makeupCompleted:cleanCount(counts.makeupCompleted),makeupPending:cleanCount(counts.makeupPending),scheduled:cleanCount(counts.scheduled),cancelled:cleanCount(counts.cancelled),holiday:cleanCount(counts.holiday)},hours:{plannedMinutes:cleanMinutes(hours.plannedMinutes),learnedMinutes:cleanMinutes(hours.learnedMinutes),absentMinutes:cleanMinutes(hours.absentMinutes),makeupMinutes:cleanMinutes(hours.makeupMinutes),teacherTaughtMinutes:cleanMinutes(hours.teacherTaughtMinutes)},studentStats:studentStats.map(item=>({studentId:limitedText(item.studentId,"Học sinh",160),plannedCount:cleanCount(item.plannedCount),plannedMinutes:cleanMinutes(item.plannedMinutes),learnedCount:cleanCount(item.learnedCount),learnedMinutes:cleanMinutes(item.learnedMinutes),absentCount:cleanCount(item.absentCount),absentMinutes:cleanMinutes(item.absentMinutes),makeupCount:cleanCount(item.makeupCount),makeupMinutes:cleanMinutes(item.makeupMinutes)})).filter(item=>item.studentId),teacherStats:teacherStats.map(item=>({teacherId:limitedText(item.teacherId,"Giáo viên",160),plannedCount:cleanCount(item.plannedCount),plannedMinutes:cleanMinutes(item.plannedMinutes),taughtCount:cleanCount(item.taughtCount),taughtMinutes:cleanMinutes(item.taughtMinutes),studentCount:cleanCount(item.studentCount)})).filter(item=>item.teacherId)};
  const weekRef=doc(db,"weeks",id),batch=writeBatch(db);batch.update(weekRef,{status:"closed",weekSummary:payload,summaryUpdatedAt:serverTimestamp(),summaryUpdatedBy:user.uid,updatedAt:serverTimestamp(),updatedBy:user.uid});batch.set(doc(collection(db,"auditLogs")),{entityType:"week",entityId:id,action:"week_summary_finalized",before:{},after:{sourceFingerprint,total:payload.counts.total,learned:payload.counts.learned,absent:payload.counts.absent,makeupCompleted:payload.counts.makeupCompleted},reason:"Chốt hoặc cập nhật lại thống kê tuần",userId:user.uid,createdAt:serverTimestamp()});await withTimeout(batch.commit(),12000,"Firebase không phản hồi khi chốt thống kê tuần.");
}
export async function updateSessionStatus(weekId,session,newStatus,user,reason=""){
  const weekRef=doc(db,"weeks",weekId),sessionRef=doc(db,"weeks",weekId,"sessions",session.id),studentRef=doc(db,"students",session.studentId);
  return runTransaction(db,async tx=>{
    const [sSnap,studentSnap]=await Promise.all([tx.get(sessionRef),tx.get(studentRef)]);if(!sSnap.exists()||!studentSnap.exists())throw new Error("Không tìm thấy buổi học hoặc học sinh.");
    const old=sSnap.data(),type=validSessionType(old.type),oldStatus=validSessionStatus(old.status,type),status=validSessionStatus(newStatus,type);
    const note=limitedText(reason,"Ghi chú buổi học",5000),statusChanged=oldStatus!==status,noteChanged=(old.note||"")!==note;if(!statusChanged&&!noteChanged)return false;
    const balanceEffect=status=>type==="regular"&&status==="absent"?1:type==="makeup"&&status==="makeup_completed"&&old.usesMakeupCredit!==false?-1:0;
    const current=Number(studentSnap.data().makeupBalance||0),delta=balanceEffect(status)-balanceEffect(oldStatus);if(current+delta<0)throw new Error("Học sinh không còn buổi cần bù.");
    tx.update(sessionRef,{status,note,updatedAt:serverTimestamp(),updatedBy:user.uid});
    tx.update(weekRef,dirtyWeekPatch(user));
    if(delta)tx.update(studentRef,{makeupBalance:increment(delta),updatedAt:serverTimestamp(),updatedBy:user.uid});
    if(delta){const ref=doc(collection(db,"makeupTransactions")),ledgerType=delta>0?(type==="regular"&&status==="absent"?"credit":"reversal"):(type==="makeup"&&status==="makeup_completed"?"debit":"reversal");tx.set(ref,{type:ledgerType,quantity:delta,idempotencyKey:`${weekId}:${session.id}:${oldStatus}:${status}:${Date.now()}`,studentId:session.studentId,sessionId:session.id,weekId,relatedSessionId:session.relatedAbsenceSessionId||null,reason:note||`Đổi trạng thái ${oldStatus} → ${status}`,createdAt:serverTimestamp(),createdBy:user.uid})}
    const log=doc(collection(db,"auditLogs"));tx.set(log,{entityType:"session",entityId:`${weekId}/${session.id}`,action:statusChanged?"status_changed":"note_changed",before:{status:oldStatus,note:old.note||""},after:{status,note},reason:note,userId:user.uid,createdAt:serverTimestamp()});return true;
  });
}
export async function markHolidayRange(startDate,endDate,reason,user){
  const start=validDateKey(startDate,"Ngày bắt đầu nghỉ lễ"),end=validDateKey(endDate,"Ngày kết thúc nghỉ lễ"),note=limitedText(reason||"Nghỉ lễ","Tên ngày lễ",500);if(!start||!end||start>end)throw new Error("Khoảng ngày nghỉ lễ không hợp lệ.");
  const weekSnaps=await getDocs(collection(db,"weeks")),targets=[];for(const weekDoc of weekSnaps.docs){const week=weekDoc.data(),weekStart=week.startDate?.toDate?isoDate(week.startDate.toDate()):"",weekEnd=week.endDate?.toDate?isoDate(week.endDate.toDate()):"";if(!weekStart||!weekEnd||weekEnd<start||weekStart>end)continue;const sessionSnaps=await getDocs(collection(db,"weeks",weekDoc.id,"sessions"));sessionSnaps.docs.forEach(sessionDoc=>{const data=sessionDoc.data(),dateKey=String(data.dateKey||"");if(dateKey>=start&&dateKey<=end)targets.push({weekId:weekDoc.id,session:{id:sessionDoc.id,...data}})})}
  let cursor=0,updated=0;const failed=[];const worker=async()=>{while(cursor<targets.length){const target=targets[cursor++];try{if(await updateSessionStatus(target.weekId,target.session,"holiday",user,note))updated++}catch(error){failed.push({id:target.session.id,message:error?.message||"Không thể đánh dấu nghỉ lễ."})}}};await Promise.all(Array.from({length:Math.min(4,targets.length)},worker));if(failed.length)throw new Error(`Đã cập nhật ${updated} buổi; ${failed.length} buổi lỗi. ${failed[0].message}`);return {updated,total:targets.length};
}
async function restoreHolidaySessions(holidayId,user){
  const weeks=await getDocs(collection(db,"weeks"));let restored=0;for(const week of weeks.docs){const sessions=await getDocs(collection(db,"weeks",week.id,"sessions"));for(const sessionDoc of sessions.docs){const session={id:sessionDoc.id,...sessionDoc.data()};if(session.holidayId!==holidayId)continue;const fallback=session.type==="makeup"?"makeup_scheduled":"scheduled",target=validSessionStatus(session.holidayOriginalStatus||fallback,session.type||"regular");await updateSessionStatus(week.id,session,target,user,session.holidayOriginalNote||"");await updateDoc(sessionDoc.ref,{holidayId:"",holidayOriginalStatus:"",holidayOriginalNote:"",updatedAt:serverTimestamp(),updatedBy:user.uid});restored++}}return restored;
}
async function applyHolidayToSessions(holidayId,start,end,name,user){
  const weeks=await getDocs(collection(db,"weeks"));let updated=0;for(const week of weeks.docs){const sessions=await getDocs(collection(db,"weeks",week.id,"sessions"));for(const sessionDoc of sessions.docs){const session={id:sessionDoc.id,...sessionDoc.data()},dateKey=String(session.dateKey||"");if(dateKey<start||dateKey>end)continue;const originalStatus=session.status==="holiday"?(session.holidayOriginalStatus||(session.type==="makeup"?"makeup_scheduled":"scheduled")):session.status,originalNote=session.status==="holiday"?(session.holidayOriginalNote||""):(session.note||"");await updateSessionStatus(week.id,session,"holiday",user,name);await updateDoc(sessionDoc.ref,{holidayId,holidayOriginalStatus:originalStatus,holidayOriginalNote:originalNote,updatedAt:serverTimestamp(),updatedBy:user.uid});updated++}}return updated;
}
export async function saveHoliday(data,user,id){
  if(!user?.uid)throw new Error("Vui lòng đăng nhập lại.");const name=limitedText(data.name||data.reason,"Tên ngày lễ",200),startDate=validDateKey(data.startDate,"Ngày bắt đầu"),endDate=validDateKey(data.endDate,"Ngày kết thúc");if(!name)throw new Error("Vui lòng nhập tên ngày lễ.");if(!startDate||!endDate||startDate>endDate)throw new Error("Khoảng ngày lễ không hợp lệ.");const ref=id?doc(db,"holidays",id):doc(collection(db,"holidays"));if(id){const current=await getDoc(ref);if(!current.exists())throw new Error("Ngày lễ không còn tồn tại.");await restoreHolidaySessions(id,user);await updateDoc(ref,{name,startDate,endDate,updatedAt:serverTimestamp(),updatedBy:user.uid})}else await setHolidayRecord(ref,{name,startDate,endDate},user);const updated=await applyHolidayToSessions(ref.id,startDate,endDate,name,user);return {id:ref.id,updated};
}
async function setHolidayRecord(ref,data,user){const batch=writeBatch(db);batch.set(ref,{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:user.uid,updatedBy:user.uid});batch.set(doc(collection(db,"auditLogs")),{entityType:"holiday",entityId:ref.id,action:"holiday_created",before:{},after:data,reason:"Tạo ngày lễ",userId:user.uid,createdAt:serverTimestamp()});await batch.commit()}
export async function deleteHoliday(id,user){if(!user?.uid)throw new Error("Vui lòng đăng nhập lại.");const ref=doc(db,"holidays",limitedText(id,"Ngày lễ",160)),current=await getDoc(ref);if(!current.exists())return 0;const restored=await restoreHolidaySessions(ref.id,user),batch=writeBatch(db);batch.delete(ref);batch.set(doc(collection(db,"auditLogs")),{entityType:"holiday",entityId:ref.id,action:"holiday_deleted",before:current.data(),after:{},reason:"Xóa ngày lễ và hoàn tác lịch",userId:user.uid,createdAt:serverTimestamp()});await batch.commit();return restored}
export async function autoCompleteElapsedSessions(weekId,sessions,user,now=new Date()){
  if(!user?.uid||!weekId||!Array.isArray(sessions))return {updated:0,failed:[]};const nowMs=now instanceof Date?now.getTime():new Date(now).getTime();if(!Number.isFinite(nowMs))throw new Error("Thời gian thiết bị không hợp lệ.");
  const candidates=sessions.map(item=>({item,target:elapsedSessionTarget(item,nowMs)})).filter(entry=>entry.target);
  let cursor=0,updated=0;const failed=[];const worker=async()=>{while(cursor<candidates.length){const {item,target}=candidates[cursor++];try{if(await updateSessionStatus(weekId,item,target,user,item.note||""))updated++}catch(error){failed.push({id:item.id,message:error?.message||"Không thể tự cập nhật buổi học."})}}};await Promise.all(Array.from({length:Math.min(4,candidates.length)},worker));return {updated,failed};
}
export function getTeacherAvailability(teacherId,sourceSession,allSessions=[]){
  const selectedTeacherId=String(teacherId||"").trim(),sameSlot=allSessions.filter(s=>s.dateKey===sourceSession.dateKey&&overlap(s.startTime,s.endTime,sourceSession.startTime,sourceSession.endTime)&&activeSession(s)),capacity=MAX_SIMULTANEOUS_STUDENTS;if(!selectedTeacherId)return {available:false,reason:"Vui lòng chọn giáo viên dạy.",occupied:sameSlot.length,capacity};
  const conflictingSession=allSessions.find(s=>activeSession(s)&&s.teacherId===selectedTeacherId&&s.dateKey===sourceSession.dateKey&&overlap(s.startTime,s.endTime,sourceSession.startTime,sourceSession.endTime)&&!(s.startTime===sourceSession.startTime&&s.endTime===sourceSession.endTime));if(conflictingSession)return {available:false,reason:"Giáo viên đã có lịch khác trùng giờ.",occupied:0,capacity,conflictingSession};
  const occupied=sameSlot.length;if(occupied>=capacity)return {available:false,reason:`Khung giờ đã đủ ${capacity} học sinh.`,occupied,capacity};
  const teachingSameSlot=sameSlot.some(s=>s.teacherId===selectedTeacherId&&s.startTime===sourceSession.startTime&&s.endTime===sourceSession.endTime);return {available:true,reason:"",occupied,capacity,teachingSameSlot};
}
export async function addMakeupSession(weekId,sourceSession,student,teacherId,allSessions,user,note="Xếp từ gợi ý học bù"){
  const selectedTeacherId=limitedText(teacherId,"Giáo viên",160),studentId=limitedText(student?.id,"Học sinh",160),dateKey=validDateKey(sourceSession?.dateKey,"Ngày học"),startTime=wholeHour(sourceSession?.startTime,"Giờ bắt đầu"),endTime=wholeHour(sourceSession?.endTime,"Giờ kết thúc"),dayOfWeek=Number(sourceSession?.dayOfWeek),liveSnapshot=await getDocs(collection(db,"weeks",weekId,"sessions")),liveSessions=liveSnapshot.docs.map(item=>({id:item.id,...item.data()})),availability=getTeacherAvailability(selectedTeacherId,{...sourceSession,dateKey,startTime,endTime},liveSessions);if(!availability.available)throw new Error(availability.reason);if(!studentId)throw new Error("Vui lòng chọn học sinh.");if(!Number.isInteger(dayOfWeek)||dayOfWeek<0||dayOfWeek>6||startTime>=endTime)throw new Error("Khung giờ học bù không hợp lệ.");
  if(!Number.isInteger(availability.capacity)||availability.capacity<1)throw new Error("Sức chứa khung giờ không hợp lệ.");const leaveSnapshot=await getDocs(query(collection(db,"teacherLeaves"),where("teacherId","==",selectedTeacherId))),onLeave=leaveSnapshot.docs.some(item=>{const leave=item.data();return dateKey>=leave.startDate&&dateKey<=leave.endDate&&(leave.leaveType==="full_day"||overlap(leave.startTime,leave.endTime,startTime,endTime))});if(onLeave)throw new Error("Giáo viên đã xin nghỉ phép trong khung giờ này.");
  if(liveSessions.some(s=>activeSession(s)&&s.studentId===student.id&&s.dateKey===sourceSession.dateKey&&overlap(s.startTime,s.endTime,sourceSession.startTime,sourceSession.endTime)))throw new Error("Học sinh đã có lịch trùng khung giờ này.");
  const usesMakeupCredit=Number(student.makeupBalance||0)>0,sessionNote=limitedText(note||"Xếp từ gợi ý học bù","Ghi chú học bù",5000),sessionRef=doc(collection(db,"weeks",weekId,"sessions")),batch=writeBatch(db);batch.set(sessionRef,{studentId,teacherId:selectedTeacherId,date:sourceSession.date,dateKey,dayOfWeek,startTime,endTime,capacity:1,type:"makeup",status:"makeup_scheduled",usesMakeupCredit,relatedAbsenceSessionId:null,note:sessionNote,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:user.uid,updatedBy:user.uid});batch.update(doc(db,"weeks",weekId),dirtyWeekPatch(user));batch.set(doc(collection(db,"auditLogs")),{entityType:"session",entityId:`${weekId}/${sessionRef.id}`,action:"makeup_session_created",before:{},after:{studentId,teacherId:selectedTeacherId,dateKey,startTime,endTime,usesMakeupCredit},reason:sessionNote,userId:user.uid,createdAt:serverTimestamp()});await batch.commit();return sessionRef.id;
}
export async function saveSession(weekId,data,allSessions,user,id){
  const dateKey=validDateKey(data.dateKey,"Ngày học"),sessionDate=new Date(`${dateKey}T12:00:00`),studentId=limitedText(data.studentId,"Học sinh",160),teacherId=limitedText(data.teacherId,"Giáo viên",160),startTime=wholeHour(data.startTime,"Giờ bắt đầu"),endTime=wholeHour(data.endTime,"Giờ kết thúc"),type=validSessionType(data.type),status=validSessionStatus(data.status,type),dayOfWeek=Number(data.dayOfWeek);if(startTime>=endTime)throw new Error("Sau khi làm tròn xuống, giờ kết thúc phải sau giờ bắt đầu.");if(!studentId||!teacherId)throw new Error("Vui lòng chọn học sinh và giáo viên.");if(!Number.isInteger(dayOfWeek)||dayOfWeek<0||dayOfWeek>6)throw new Error("Thứ trong tuần không hợp lệ.");
  const conflict=allSessions.find(s=>s.id!==id&&s.dateKey===dateKey&&overlap(s.startTime,s.endTime,startTime,endTime)&&((s.status!=="cancelled"&&s.studentId===studentId)||(teacherId&&!['absent','cancelled'].includes(s.status)&&s.teacherId===teacherId&&!(s.startTime===startTime&&s.endTime===endTime))));
  if(conflict)throw new Error(conflict.studentId===studentId?"Học sinh đã có lịch trùng giờ.":"Giáo viên đã có lịch khác trùng giờ.");
  const leaveSnapshot=await getDocs(query(collection(db,"teacherLeaves"),where("teacherId","==",teacherId))),teacherOnLeave=leaveSnapshot.docs.some(item=>{const leave=item.data();return dateKey>=leave.startDate&&dateKey<=leave.endDate&&(leave.leaveType==="full_day"||overlap(leave.startTime,leave.endTime,startTime,endTime))});
  if(teacherOnLeave)throw new Error("Giáo viên đã xin nghỉ phép trong ngày hoặc khung giờ này.");
  const requestedCapacity=Number(data.capacity||1);if(!Number.isInteger(requestedCapacity)||requestedCapacity<1||requestedCapacity>7)throw new Error("Số chỗ của mỗi lịch phải từ 1 đến 7 học sinh.");const capacity=type==="regular"?requestedCapacity:1,slotPeers=allSessions.filter(s=>s.id!==id&&s.dateKey===dateKey&&overlap(s.startTime,s.endTime,startTime,endTime)),occupied=slotPeers.filter(activeSession).length+(activeSession({status})?1:0);if(occupied>MAX_SIMULTANEOUS_STUDENTS)throw new Error(`Khung giờ đã đủ ${MAX_SIMULTANEOUS_STUDENTS} học sinh.`);
  const payload={studentId,teacherId,date:Timestamp.fromDate(sessionDate),dateKey,dayOfWeek,startTime,endTime,capacity,type,status,note:limitedText(data.note,"Ghi chú buổi học",5000),updatedAt:serverTimestamp(),updatedBy:user.uid};
  const ref=id?doc(db,"weeks",weekId,"sessions",id):doc(collection(db,"weeks",weekId,"sessions")),batch=writeBatch(db);if(id)batch.update(ref,payload);else batch.set(ref,{...payload,createdAt:serverTimestamp(),createdBy:user.uid});batch.update(doc(db,"weeks",weekId),dirtyWeekPatch(user));batch.set(doc(collection(db,"auditLogs")),{entityType:"session",entityId:`${weekId}/${ref.id}`,action:id?"session_updated":"session_created",before:{},after:{studentId,teacherId,dateKey,startTime,endTime,type,status},reason:payload.note||(id?"Sửa buổi học":"Thêm buổi học thủ công"),userId:user.uid,createdAt:serverTimestamp()});await withTimeout(batch.commit(),12000,"Firebase không phản hồi. Hãy kiểm tra Firestore Rules.");return ref.id;
}
export async function deleteSession(weekId,session,user){
  const weekRef=doc(db,"weeks",weekId),sessionRef=doc(db,"weeks",weekId,"sessions",session.id),studentRef=doc(db,"students",session.studentId);
    return runTransaction(db,async tx=>{const [sSnap,studentSnap]=await Promise.all([tx.get(sessionRef),tx.get(studentRef)]);if(!sSnap.exists())return;const current=sSnap.data(),balance=studentSnap.exists()?Number(studentSnap.data().makeupBalance||0):0;let delta=0;if(current.status==="absent")delta=-1;if(current.status==="makeup_completed"&&current.usesMakeupCredit!==false)delta=1;if(balance+delta<0)throw new Error("Không thể xóa vì số dư học bù sẽ âm.");tx.delete(sessionRef);tx.update(weekRef,dirtyWeekPatch(user));if(delta&&studentSnap.exists())tx.update(studentRef,{makeupBalance:increment(delta),updatedAt:serverTimestamp(),updatedBy:user.uid});if(delta){tx.set(doc(collection(db,"makeupTransactions")),{studentId:current.studentId,sessionId:session.id,weekId,type:"reversal",quantity:delta,reason:"Xóa buổi học và hoàn tác số dư",idempotencyKey:`delete:${session.id}`,createdAt:serverTimestamp(),createdBy:user.uid})}tx.set(doc(collection(db,"auditLogs")),{entityType:"session",entityId:`${weekId}/${session.id}`,action:"session_deleted",before:{status:current.status,studentId:current.studentId,dateKey:current.dateKey,startTime:current.startTime,endTime:current.endTime},after:{},reason:"Xóa buổi học",userId:user.uid,createdAt:serverTimestamp()})});
}
async function deleteRefsInChunks(refs){for(let i=0;i<refs.length;i+=400){const batch=writeBatch(db);refs.slice(i,i+400).forEach(ref=>batch.delete(ref));await batch.commit()}}
export async function deleteWeek(weekId,sessions,students,user){
  const deltas=new Map();sessions.forEach(s=>{const delta=s.status==="absent"?-1:s.status==="makeup_completed"&&s.usesMakeupCredit!==false?1:0;if(delta)deltas.set(s.studentId,(deltas.get(s.studentId)||0)+delta)});const balanceUpdates=[];for(const [studentId,delta] of deltas){const student=students.find(s=>s.id===studentId);if(!student)continue;const next=Number(student.makeupBalance||0)+delta;if(next<0)throw new Error(`Không thể xóa tuần vì số dư học bù của ${student.fullName} sẽ âm.`);balanceUpdates.push({studentId,delta,next})}
  const sessionRefs=sessions.map(s=>doc(db,"weeks",weekId,"sessions",s.id)),writeCount=sessionRefs.length+balanceUpdates.length*2+2;if(writeCount<=450){const batch=writeBatch(db);sessionRefs.forEach(ref=>batch.delete(ref));balanceUpdates.forEach(({studentId,delta,next})=>{batch.update(doc(db,"students",studentId),{makeupBalance:next,updatedAt:serverTimestamp(),updatedBy:user.uid});batch.set(doc(collection(db,"makeupTransactions")),{studentId,weekId,type:"reversal",quantity:delta,reason:"Xóa tuần và hoàn tác số dư",idempotencyKey:`delete-week:${weekId}:${studentId}`,createdAt:serverTimestamp(),createdBy:user.uid})});batch.delete(doc(db,"weeks",weekId));batch.set(doc(collection(db,"auditLogs")),{entityType:"week",entityId:weekId,action:"week_deleted",before:{sessions:sessions.length},after:{},reason:"Xóa tuần",userId:user.uid,createdAt:serverTimestamp()});return batch.commit()}
  throw new Error("Tuần có quá nhiều dữ liệu để xóa an toàn trong một giao dịch. Hãy sao lưu và dùng công cụ quản trị để xử lý.");
}
export async function deleteMakeupTransaction(ledgerRecord,user){
  const transactionRef=doc(db,"makeupTransactions",ledgerRecord.id);return runTransaction(db,async tx=>{const ledgerSnap=await tx.get(transactionRef);if(!ledgerSnap.exists())return;const ledger=ledgerSnap.data(),studentRef=doc(db,"students",ledger.studentId),sessionRef=ledger.weekId&&ledger.sessionId?doc(db,"weeks",ledger.weekId,"sessions",ledger.sessionId):null,[studentSnap,sessionSnap]=await Promise.all([tx.get(studentRef),sessionRef?tx.get(sessionRef):Promise.resolve(null)]);if(sessionSnap?.exists())throw new Error("Giao dịch còn gắn với một buổi học. Hãy hoàn tác hoặc xóa buổi học trước.");const quantity=Number(ledger.quantity||0);if(studentSnap.exists()){const current=Number(studentSnap.data().makeupBalance||0),next=current-quantity;if(next<0)throw new Error("Không thể xóa giao dịch vì số dư học bù sẽ âm.");tx.update(studentRef,{makeupBalance:next,updatedAt:serverTimestamp(),updatedBy:user.uid})}tx.delete(transactionRef);tx.set(doc(collection(db,"auditLogs")),{entityType:"makeupTransaction",entityId:ledgerRecord.id,action:"transaction_deleted",before:{studentId:ledger.studentId,quantity},after:{},reason:"Xóa giao dịch test không còn buổi học",userId:user.uid,createdAt:serverTimestamp()})});
}
export async function purgeAllData(user){
  if(user.uid!=="EplnbxgWTaal9N5QgflBWaT1LWG3")throw new Error("Chỉ chủ sở hữu được dọn toàn bộ dữ liệu.");
  const refs=[];const weekSnaps=await getDocs(collection(db,"weeks"));for(const weekDoc of weekSnaps.docs){const sessionSnaps=await getDocs(collection(db,"weeks",weekDoc.id,"sessions"));sessionSnaps.docs.forEach(s=>refs.push(s.ref));refs.push(weekDoc.ref)}
  for(const name of ["scheduleTemplates","studentForms","students","teachers","notes","holidays","teacherLeaves","makeupTransactions","auditLogs"]){const snap=await getDocs(collection(db,name));snap.docs.forEach(d=>refs.push(d.ref))}
  await deleteRefsInChunks(refs);return refs.length;
}
export async function normalizeAllScheduleHours(user){
  if(!user?.uid)throw new Error("Cần đăng nhập để chuẩn hóa giờ học.");
  const operations=[],changedWeeks=new Set();let templateCount=0,sessionCount=0;const templates=await getDocs(collection(db,"scheduleTemplates"));
  templates.docs.forEach(item=>{const data=item.data(),startTime=floorScheduleTime(data.startTime),endTime=floorScheduleTime(data.endTime);if(startTime&&endTime&&startTime<endTime&&(startTime!==data.startTime||endTime!==data.endTime)){operations.push({ref:item.ref,data:{startTime,endTime,updatedAt:serverTimestamp(),updatedBy:user.uid}});templateCount++}});
  const weeks=await getDocs(collection(db,"weeks"));for(const week of weeks.docs){const sessions=await getDocs(collection(db,"weeks",week.id,"sessions"));sessions.docs.forEach(item=>{const data=item.data(),startTime=floorScheduleTime(data.startTime),endTime=floorScheduleTime(data.endTime);if(startTime&&endTime&&startTime<endTime&&(startTime!==data.startTime||endTime!==data.endTime)){operations.push({ref:item.ref,data:{startTime,endTime,updatedAt:serverTimestamp(),updatedBy:user.uid}});changedWeeks.add(week.id);sessionCount++}})}
  for(const weekId of changedWeeks)operations.push({ref:doc(db,"weeks",weekId),data:{summaryDirtyAt:serverTimestamp(),updatedAt:serverTimestamp(),updatedBy:user.uid}});
  for(let index=0;index<operations.length;index+=400){const batch=writeBatch(db);operations.slice(index,index+400).forEach(operation=>batch.update(operation.ref,operation.data));await batch.commit()}
  return {templates:templateCount,sessions:sessionCount,weeks:changedWeeks.size};
}
export async function syncScheduleTemplatesFromSource(sourceTemplates,user,sourceVersion="",sourceTeachers=[],sourceStudentProfiles=[]){
  if(!user?.uid)throw new Error("Cần đăng nhập để cập nhật lịch mẫu.");
  if(!Array.isArray(sourceTemplates)||!sourceTemplates.length)throw new Error("Nguồn lịch mẫu đang trống.");
  const [studentSnapshot,teacherSnapshot,templateSnapshot,formSnapshot]=await Promise.all([getDocs(collection(db,"students")),getDocs(collection(db,"teachers")),getDocs(collection(db,"scheduleTemplates")),getDocs(collection(db,"studentForms"))]);
  const existingTeachers=new Map(teacherSnapshot.docs.map(item=>[item.id,item.data()])),teacherIds=new Set(existingTeachers.keys()),createdTeachers=[],updatedTeachers=[];
  if(Array.isArray(sourceTeachers)&&sourceTeachers.length){const teacherBatch=writeBatch(db);let teacherWrites=0;for(const sourceTeacher of sourceTeachers){const id=limitedText(sourceTeacher.id,"Mã giáo viên T9",160),fullName=limitedText(sourceTeacher.fullName,"Tên giáo viên T9",200),shortName=limitedText(sourceTeacher.shortName||sourceTeacher.fullName,"Tên hiển thị giáo viên T9",100),legalName=limitedText(sourceTeacher.legalName||"","Họ tên giáo viên theo hợp đồng",200),birthday=sourceTeacher.birthday?validDateKey(sourceTeacher.birthday,"Ngày sinh giáo viên T9"):"",phone=limitedText(sourceTeacher.phone||"","Số điện thoại giáo viên T9",30),color=validColor(sourceTeacher.color,"#7c5ce7"),sourceProfile={...(legalName?{legalName}:{}),...(birthday?{birthday}:{}),...(phone?{phone}:{})};if(!id||!fullName)throw new Error("Nguồn T9 có giáo viên không hợp lệ.");const current=existingTeachers.get(id),same=current&&current.fullName===fullName&&current.shortName===shortName&&String(current.color||"").toLowerCase()===color&&current.active!==false&&Object.entries(sourceProfile).every(([field,value])=>current[field]===value);if(!same){teacherBatch.set(doc(db,"teachers",id),{fullName,shortName,color,active:true,updatedAt:serverTimestamp(),updatedBy:user.uid,...(current?{}:{birthday:"",phone:"",note:"Tự tạo khi cập nhật lịch mẫu từ T9 (2).xlsx",createdAt:serverTimestamp(),createdBy:user.uid}),...sourceProfile},{merge:true});teacherWrites++;(current?updatedTeachers:createdTeachers).push({id,fullName})}teacherIds.add(id)}if(teacherWrites)await withTimeout(teacherBatch.commit(),12000,"Firebase không phản hồi khi cập nhật giáo viên từ T9.")}
  const studentIds=new Set(studentSnapshot.docs.map(item=>item.id)),studentsByName=new Map();
  studentSnapshot.docs.forEach(item=>{const key=canonicalRosterKey(item.data().fullName||item.data().shortName);if(key&&!studentsByName.has(key))studentsByName.set(key,item.id)});
  const sourceStudents=new Map();
  for(const item of sourceTemplates){const studentKey=canonicalRosterKey(item.studentKey||item.studentName);if(!studentKey)throw new Error("Nguồn T9 có học sinh không hợp lệ.");if(!sourceStudents.has(studentKey))sourceStudents.set(studentKey,{studentName:String(item.studentName||item.studentKey).trim(),studentIdHint:String(item.studentIdHint||"").trim()})}
  const createdStudents=[];const studentBatch=writeBatch(db);const fallbackColors=["#5754d9","#e879a9","#4f86e8","#27a778","#9b6be8","#e69b32"];
  for(const [studentKey,sourceStudent] of sourceStudents){if(studentsByName.has(studentKey))continue;const studentId=limitedText(sourceStudent.studentIdHint,"Mã học sinh T9",160);if(!studentId)throw new Error(`Thiếu mã cho học sinh ${sourceStudent.studentName}.`);const color=fallbackColors[createdStudents.length%fallbackColors.length];studentBatch.set(doc(db,"students",studentId),{fullName:sourceStudent.studentName,shortName:sourceStudent.studentName,birthday:"",color,parentPhone:"",note:"Tự tạo khi cập nhật lịch mẫu từ T9.xlsx",active:true,makeupBalance:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:user.uid,updatedBy:user.uid},{merge:true});studentsByName.set(studentKey,studentId);studentIds.add(studentId);createdStudents.push({id:studentId,fullName:sourceStudent.studentName})}
  if(createdStudents.length)await withTimeout(studentBatch.commit(),12000,"Firebase không phản hồi khi thêm học sinh mới từ T9.");
  let updatedStudentProfiles=0;if(Array.isArray(sourceStudentProfiles)&&sourceStudentProfiles.length){const profileBatch=writeBatch(db);for(const sourceProfile of sourceStudentProfiles){const studentKey=canonicalRosterKey(sourceProfile.studentKey||sourceProfile.studentName),studentId=studentsByName.get(studentKey);if(!studentId)continue;const birthday=validDateKey(sourceProfile.birthday,"Ngày sinh học sinh T9");if(!birthday)continue;const current=studentSnapshot.docs.find(item=>item.id===studentId)?.data();if(current?.birthday===birthday)continue;profileBatch.set(doc(db,"students",studentId),{birthday,updatedAt:serverTimestamp(),updatedBy:user.uid},{merge:true});updatedStudentProfiles++}if(updatedStudentProfiles)await withTimeout(profileBatch.commit(),12000,"Firebase không phản hồi khi cập nhật ngày sinh học sinh.")}
  const existingById=new Map(templateSnapshot.docs.map(item=>[item.id,item.data()])),desiredIds=new Set(),desired=[];
  for(const item of sourceTemplates){const id=limitedText(item.id,"Mã lịch T9",160),studentKey=canonicalRosterKey(item.studentKey||item.studentName),studentId=studentIds.has(String(item.studentIdHint||""))?String(item.studentIdHint):studentsByName.get(studentKey),teacherId=limitedText(item.teacherId,"Giáo viên",160);if(!id||desiredIds.has(id))throw new Error(`Mã lịch T9 bị trùng hoặc trống: ${id||"(trống)"}.`);if(!studentId)throw new Error(`Không thể ghép học sinh ${item.studentName||item.studentKey}.`);if(!teacherIds.has(teacherId))throw new Error(`Không tìm thấy giáo viên ${teacherId} trong Firebase.`);desiredIds.add(id);desired.push({id,payload:templatePayload({...item,studentId,teacherId,capacity:1})})}
  let upserted=0;for(let index=0;index<desired.length;index+=350){const batch=writeBatch(db);let batchWrites=0;for(const {id,payload} of desired.slice(index,index+350)){const current=existingById.get(id),same=current&&["studentId","teacherId","dayOfWeek","startTime","endTime","capacity","active","note"].every(field=>current[field]===payload[field]);if(same)continue;batch.set(doc(db,"scheduleTemplates",id),{...payload,updatedAt:serverTimestamp(),updatedBy:user.uid,...(current?{}:{createdAt:serverTimestamp(),createdBy:user.uid})},{merge:true});upserted++;batchWrites++}if(batchWrites)await withTimeout(batch.commit(),12000,"Firebase không phản hồi khi ghi lịch mẫu T9.")}
  const obsolete=templateSnapshot.docs.filter(item=>!desiredIds.has(item.id));for(let index=0;index<obsolete.length;index+=400){const batch=writeBatch(db);obsolete.slice(index,index+400).forEach(item=>batch.delete(item.ref));await withTimeout(batch.commit(),12000,"Firebase không phản hồi khi xóa lịch mẫu cũ.")}
  const teacherScores=new Map();for(const {payload} of desired){const key=`${payload.studentId}|${payload.teacherId}`,score=teacherScores.get(key)||{studentId:payload.studentId,teacherId:payload.teacherId,count:0,firstDay:7,firstTime:"99:99"};score.count++;if(payload.dayOfWeek<score.firstDay||(payload.dayOfWeek===score.firstDay&&payload.startTime<score.firstTime)){score.firstDay=payload.dayOfWeek;score.firstTime=payload.startTime}teacherScores.set(key,score)}const primaryByStudent=new Map();for(const score of teacherScores.values()){const current=primaryByStudent.get(score.studentId);if(!current||score.count>current.count||(score.count===current.count&&(score.firstDay<current.firstDay||(score.firstDay===current.firstDay&&score.firstTime<current.firstTime))))primaryByStudent.set(score.studentId,score)}
  const responsibilityOps=[];for(const score of primaryByStudent.values())responsibilityOps.push({ref:doc(db,"students",score.studentId),data:{primaryTeacherId:score.teacherId,responsibilitySource:"T9 (2).xlsx",updatedAt:serverTimestamp(),updatedBy:user.uid}});for(const formDoc of formSnapshot.docs){const score=primaryByStudent.get(formDoc.data().studentId);if(score&&formDoc.data().teacherId!==score.teacherId)responsibilityOps.push({ref:formDoc.ref,data:{teacherId:score.teacherId,responsibilitySource:"T9 (2).xlsx",updatedAt:serverTimestamp(),updatedBy:user.uid}})}for(let index=0;index<responsibilityOps.length;index+=400){const batch=writeBatch(db);responsibilityOps.slice(index,index+400).forEach(operation=>batch.update(operation.ref,operation.data));await withTimeout(batch.commit(),12000,"Firebase không phản hồi khi cập nhật cô phụ trách.")}
  await addDoc(collection(db,"auditLogs"),{entityType:"scheduleTemplate",entityId:"t9-template-set",action:"templates_replaced_from_t9",before:{templateCount:templateSnapshot.size},after:{templateCount:desired.length,createdStudents:createdStudents.length,createdTeachers:createdTeachers.length,updatedTeachers:updatedTeachers.length,responsibilitiesUpdated:responsibilityOps.length,sourceVersion:String(sourceVersion||"")},reason:"Cập nhật lịch mẫu và cô phụ trách theo màu trong T9 (2).xlsx",userId:user.uid,createdAt:serverTimestamp()});
  return {templates:desired.length,updated:upserted,deleted:obsolete.length,createdStudents,createdTeachers,updatedTeachers,updatedStudentProfiles,responsibilitiesUpdated:responsibilityOps.length};
}
export async function reconcileStudentRosterFromSource(sourceTemplates,user,sourceVersion=""){
  if(!user?.uid)throw new Error("Cần đăng nhập để cập nhật danh sách học sinh.");
  if(!Array.isArray(sourceTemplates)||!sourceTemplates.length)throw new Error("Nguồn danh sách tháng 9 đang trống.");
  const [studentSnapshot,formSnapshot,templateSnapshot,transactionSnapshot,weekSnapshot]=await Promise.all([getDocs(collection(db,"students")),getDocs(collection(db,"studentForms")),getDocs(collection(db,"scheduleTemplates")),getDocs(collection(db,"makeupTransactions")),getDocs(collection(db,"weeks"))]);
  const students=studentSnapshot.docs.map(item=>({id:item.id,...item.data()})),plan=planRosterReconciliation(students,sourceTemplates);if(plan.missing.length)throw new Error(`Còn ${plan.missing.length} học sinh tháng 9 chưa có hồ sơ sau khi nhập lịch.`);
  const sessionGroups=await Promise.all(weekSnapshot.docs.map(async week=>({weekId:week.id,docs:(await getDocs(collection(db,"weeks",week.id,"sessions"))).docs}))),sessions=sessionGroups.flatMap(group=>group.docs.map(item=>({weekId:group.weekId,ref:item.ref,data:item.data()})));
  const forms=formSnapshot.docs.map(item=>({ref:item.ref,data:item.data()})),templates=templateSnapshot.docs.map(item=>({ref:item.ref,data:item.data()})),transactions=transactionSnapshot.docs.map(item=>({ref:item.ref,data:item.data()})),studentById=new Map(students.map(item=>[item.id,item]));
  const referenceOps=[],studentOps=[],changedWeeks=new Set(),removed=[],archived=[],merged=[];
  const updateReferences=(fromId,toId)=>{
    sessions.filter(item=>item.data.studentId===fromId).forEach(item=>{referenceOps.push({type:"update",ref:item.ref,data:{studentId:toId,updatedAt:serverTimestamp(),updatedBy:user.uid}});changedWeeks.add(item.weekId)});
    forms.filter(item=>item.data.studentId===fromId).forEach(item=>referenceOps.push({type:"update",ref:item.ref,data:{studentId:toId,updatedAt:serverTimestamp(),updatedBy:user.uid}}));
    templates.filter(item=>item.data.studentId===fromId).forEach(item=>referenceOps.push({type:"update",ref:item.ref,data:{studentId:toId,updatedAt:serverTimestamp(),updatedBy:user.uid}}));
  };
  const duplicatesByKeeper=new Map();for(const item of plan.duplicates){if(!duplicatesByKeeper.has(item.keeperId))duplicatesByKeeper.set(item.keeperId,[]);duplicatesByKeeper.get(item.keeperId).push(item)}
  for(const keeper of plan.keepers){const duplicateRows=duplicatesByKeeper.get(keeper.studentId)||[],groupIds=[keeper.studentId,...duplicateRows.map(item=>item.studentId)],balance=groupIds.reduce((total,id)=>total+Math.max(0,Math.trunc(Number(studentById.get(id)?.makeupBalance)||0)),0);studentOps.push({type:"update",ref:doc(db,"students",keeper.studentId),data:{active:true,archived:false,mergedIntoStudentId:"",makeupBalance:balance,updatedAt:serverTimestamp(),updatedBy:user.uid}});for(const duplicate of duplicateRows){updateReferences(duplicate.studentId,keeper.studentId);const hasTransactions=transactions.some(item=>item.data.studentId===duplicate.studentId);if(hasTransactions){studentOps.push({type:"update",ref:doc(db,"students",duplicate.studentId),data:{active:false,archived:true,archivedReason:`Đã gộp vào ${keeper.studentName} theo danh sách T9`,mergedIntoStudentId:keeper.studentId,makeupBalance:0,updatedAt:serverTimestamp(),updatedBy:user.uid}});archived.push(duplicate.studentName)}else{studentOps.push({type:"delete",ref:doc(db,"students",duplicate.studentId)});removed.push(duplicate.studentName)}merged.push({from:duplicate.studentName,to:keeper.studentName})}}
  for(const stale of plan.stale){forms.filter(item=>item.data.studentId===stale.studentId).forEach(item=>referenceOps.push({type:"delete",ref:item.ref}));templates.filter(item=>item.data.studentId===stale.studentId).forEach(item=>referenceOps.push({type:"delete",ref:item.ref}));const hasHistory=sessions.some(item=>item.data.studentId===stale.studentId)||transactions.some(item=>item.data.studentId===stale.studentId);if(hasHistory){studentOps.push({type:"update",ref:doc(db,"students",stale.studentId),data:{active:false,archived:true,archivedReason:"Không còn trong danh sách T9; giữ hồ sơ ẩn để bảo toàn lịch sử",mergedIntoStudentId:"",updatedAt:serverTimestamp(),updatedBy:user.uid}});archived.push(stale.studentName)}else{studentOps.push({type:"delete",ref:doc(db,"students",stale.studentId)});removed.push(stale.studentName)}}
  changedWeeks.forEach(weekId=>referenceOps.push({type:"update",ref:doc(db,"weeks",weekId),data:{summaryDirtyAt:serverTimestamp(),updatedAt:serverTimestamp(),updatedBy:user.uid}}));
  const commitOps=async operations=>{for(let index=0;index<operations.length;index+=350){const batch=writeBatch(db);operations.slice(index,index+350).forEach(operation=>operation.type==="delete"?batch.delete(operation.ref):batch.update(operation.ref,operation.data));await withTimeout(batch.commit(),12000,"Firebase không phản hồi khi đồng bộ danh sách tháng 9.")}};
  await commitOps(referenceOps);await commitOps(studentOps);
  await addDoc(collection(db,"auditLogs"),{entityType:"studentRoster",entityId:"t9-roster",action:"roster_reconciled_from_t9",before:{studentCount:studentSnapshot.size},after:{studentCount:plan.keepers.length,removed:removed.length,archived:archived.length,merged:merged.length,sourceVersion:String(sourceVersion||"")},reason:"Giữ một hồ sơ cho mỗi bé trong T9; loại bé không còn trong danh sách và bảo toàn lịch sử cũ",userId:user.uid,createdAt:serverTimestamp()});
  return {students:plan.keepers.length,removed,archived,merged,stale:plan.stale.map(item=>item.studentName),duplicates:plan.duplicates.map(item=>item.studentName)};
}
export async function loadMonthReport(monthKey){
  const key=String(monthKey||"").trim();if(!/^\d{4}-\d{2}$/.test(key))throw new Error("Tháng báo cáo phải có dạng YYYY-MM.");const [yearText,monthText]=key.split("-"),year=Number(yearText),month=Number(monthText);if(month<1||month>12)throw new Error("Tháng báo cáo không hợp lệ.");
  const monthStart=new Date(year,month-1,1,0,0,0,0),monthEnd=new Date(year,month,0,23,59,59,999),weekSnaps=await getDocs(collection(db,"weeks"));const intersectingWeeks=weekSnaps.docs.filter(weekDoc=>{const week=weekDoc.data(),start=week.startDate?.toDate?week.startDate.toDate():new Date(week.startDate),end=week.endDate?.toDate?week.endDate.toDate():new Date(week.endDate);return !Number.isNaN(start.getTime())&&!Number.isNaN(end.getTime())&&start<=monthEnd&&end>=monthStart});
  const groups=await Promise.all(intersectingWeeks.map(async weekDoc=>{const week=weekDoc.data(),sessionSnaps=await getDocs(collection(db,"weeks",weekDoc.id,"sessions"));return sessionSnaps.docs.map(sessionDoc=>{const session=sessionDoc.data(),dateValue=session.date?.toDate?session.date.toDate():session.date,dateKey=session.dateKey||(dateValue?isoDate(dateValue):"");return {id:sessionDoc.id,...session,dateKey,weekId:weekDoc.id,weekNumber:week.weekNumber,weekLabel:week.label||"",weekStatus:week.status||"active",weekSummaryUpdatedAt:week.summaryUpdatedAt||null}}).filter(session=>session.dateKey.startsWith(`${key}-`))}));
  return groups.flat().sort((a,b)=>String(a.dateKey).localeCompare(String(b.dateKey))||String(a.startTime||"").localeCompare(String(b.startTime||""))||String(a.studentId||"").localeCompare(String(b.studentId||"")));
}
export async function loadStudentHistory(studentId){
  const id=limitedText(studentId,"Học sinh",160);if(!id)throw new Error("Không tìm thấy học sinh cần xem.");const weekSnaps=await getDocs(collection(db,"weeks"));const groups=await Promise.all(weekSnaps.docs.map(async weekDoc=>{const week=weekDoc.data(),sessionSnaps=await getDocs(query(collection(db,"weeks",weekDoc.id,"sessions"),where("studentId","==",id)));return sessionSnaps.docs.map(sessionDoc=>({id:sessionDoc.id,...sessionDoc.data(),weekId:weekDoc.id,weekNumber:Number(week.weekNumber||0),weekLabel:String(week.label||""),weekStartDate:week.startDate,weekEndDate:week.endDate}))}));return groups.flat().sort((a,b)=>String(a.dateKey||"").localeCompare(String(b.dateKey||""))||String(a.startTime||"").localeCompare(String(b.startTime||"")));
}
export async function loadWeekSchedule(weekId){
  const targetWeek=limitedText(weekId,"Tuần",160);if(!targetWeek)throw new Error("Không tìm thấy tuần cần xem.");const sessionSnaps=await getDocs(collection(db,"weeks",targetWeek,"sessions"));return sessionSnaps.docs.map(sessionDoc=>({id:sessionDoc.id,...sessionDoc.data(),weekId:targetWeek})).sort((a,b)=>String(a.dateKey||"").localeCompare(String(b.dateKey||""))||String(a.startTime||"").localeCompare(String(b.startTime||"")));
}
export async function loadTeacherWeekSchedule(teacherId,weekId){
  const id=limitedText(teacherId,"Giáo viên",160),targetWeek=limitedText(weekId,"Tuần",160);if(!id||!targetWeek)throw new Error("Không tìm thấy giáo viên hoặc tuần cần xem.");
  const [weekSnap,sessionSnaps]=await Promise.all([getDoc(doc(db,"weeks",targetWeek)),getDocs(query(collection(db,"weeks",targetWeek,"sessions"),where("teacherId","==",id)))]);if(!weekSnap.exists())throw new Error("Tuần hiện tại chưa được tạo.");const week=weekSnap.data();return sessionSnaps.docs.map(sessionDoc=>({id:sessionDoc.id,...sessionDoc.data(),weekId:targetWeek,weekNumber:Number(week.weekNumber||0),weekLabel:String(week.label||""),weekStartDate:week.startDate,weekEndDate:week.endDate})).sort((a,b)=>String(a.dateKey||"").localeCompare(String(b.dateKey||""))||String(a.startTime||"").localeCompare(String(b.startTime||"")));
}
export async function seedData(user){const ids={mai:"sample-mai-anh",minh:"sample-minh-quang",bao:"sample-bao-bao",my:"sample-thien-my",khoa:"sample-dang-khoa"},teacherId="sample-co-ngan";const students=[['mai','Mai Anh','#e879a9'],['minh','Minh Quang','#4f86e8'],['bao','Bảo Bảo','#27a778'],['my','Thiên Mỹ','#9b6be8'],['khoa','Đăng Khoa','#e69b32']];const templates=[['minh',1,'13:00','14:00'],['mai',5,'15:00','16:00'],['bao',3,'16:00','17:00'],['my',2,'17:00','18:00'],['khoa',4,'18:00','19:00']];const batch=writeBatch(db);students.forEach(([key,name,color])=>batch.set(doc(db,"students",ids[key]),{fullName:name,shortName:name,birthday:"",color,active:true,makeupBalance:0,parentPhone:"",note:"Dữ liệu mẫu",createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:user.uid,updatedBy:user.uid},{merge:true}));batch.set(doc(db,"teachers",teacherId),{fullName:"Cô Ngân",shortName:"Cô Ngân",birthday:"",color:"#7c5ce7",phone:"",active:true,note:"Giáo viên mẫu",createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:user.uid,updatedBy:user.uid},{merge:true});templates.forEach(([key,day,start,end],i)=>batch.set(doc(db,"scheduleTemplates",`sample-template-${i+1}`),{studentId:ids[key],teacherId,dayOfWeek:day,startTime:start,endTime:end,capacity:1,active:true,note:"Dữ liệu mẫu",createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:user.uid,updatedBy:user.uid},{merge:true}));return batch.commit()}
export const subscribeRecentAudit=cb=>onSnapshot(query(collection(db,"auditLogs"),orderBy("createdAt","desc"),limit(100)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))),e=>cb(null,e));
export const subscribeTransactions=cb=>onSnapshot(query(collection(db,"makeupTransactions"),orderBy("createdAt","desc"),limit(200)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))),e=>cb(null,e));
